/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libScePngDec", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global scePngDecCreate\n"
    ".type scePngDecCreate @function\n"
    "scePngDecCreate:\n"
    "jmp qword ptr [rip + __ptr_scePngDecCreate]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_scePngDecCreate\n"
    ".type __load_and_call_scePngDecCreate @function\n"
    "__load_and_call_scePngDecCreate:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_scePngDecCreate\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_scePngDecCreate]\n");

void __load_and_call_scePngDecCreate();
static __attribute__ ((used)) void* __ptr_scePngDecCreate = &__load_and_call_scePngDecCreate;

static __attribute__ ((used)) void
__load_scePngDecCreate(void) {
  sprx_dlsym(__handle, "scePngDecCreate", &__ptr_scePngDecCreate);
}

asm(".intel_syntax noprefix\n"
    ".global scePngDecDecode\n"
    ".type scePngDecDecode @function\n"
    "scePngDecDecode:\n"
    "jmp qword ptr [rip + __ptr_scePngDecDecode]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_scePngDecDecode\n"
    ".type __load_and_call_scePngDecDecode @function\n"
    "__load_and_call_scePngDecDecode:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_scePngDecDecode\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_scePngDecDecode]\n");

void __load_and_call_scePngDecDecode();
static __attribute__ ((used)) void* __ptr_scePngDecDecode = &__load_and_call_scePngDecDecode;

static __attribute__ ((used)) void
__load_scePngDecDecode(void) {
  sprx_dlsym(__handle, "scePngDecDecode", &__ptr_scePngDecDecode);
}

asm(".intel_syntax noprefix\n"
    ".global scePngDecDecodeWithInputControl\n"
    ".type scePngDecDecodeWithInputControl @function\n"
    "scePngDecDecodeWithInputControl:\n"
    "jmp qword ptr [rip + __ptr_scePngDecDecodeWithInputControl]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_scePngDecDecodeWithInputControl\n"
    ".type __load_and_call_scePngDecDecodeWithInputControl @function\n"
    "__load_and_call_scePngDecDecodeWithInputControl:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_scePngDecDecodeWithInputControl\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_scePngDecDecodeWithInputControl]\n");

void __load_and_call_scePngDecDecodeWithInputControl();
static __attribute__ ((used)) void* __ptr_scePngDecDecodeWithInputControl = &__load_and_call_scePngDecDecodeWithInputControl;

static __attribute__ ((used)) void
__load_scePngDecDecodeWithInputControl(void) {
  sprx_dlsym(__handle, "scePngDecDecodeWithInputControl", &__ptr_scePngDecDecodeWithInputControl);
}

asm(".intel_syntax noprefix\n"
    ".global scePngDecDelete\n"
    ".type scePngDecDelete @function\n"
    "scePngDecDelete:\n"
    "jmp qword ptr [rip + __ptr_scePngDecDelete]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_scePngDecDelete\n"
    ".type __load_and_call_scePngDecDelete @function\n"
    "__load_and_call_scePngDecDelete:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_scePngDecDelete\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_scePngDecDelete]\n");

void __load_and_call_scePngDecDelete();
static __attribute__ ((used)) void* __ptr_scePngDecDelete = &__load_and_call_scePngDecDelete;

static __attribute__ ((used)) void
__load_scePngDecDelete(void) {
  sprx_dlsym(__handle, "scePngDecDelete", &__ptr_scePngDecDelete);
}

asm(".intel_syntax noprefix\n"
    ".global scePngDecParseHeader\n"
    ".type scePngDecParseHeader @function\n"
    "scePngDecParseHeader:\n"
    "jmp qword ptr [rip + __ptr_scePngDecParseHeader]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_scePngDecParseHeader\n"
    ".type __load_and_call_scePngDecParseHeader @function\n"
    "__load_and_call_scePngDecParseHeader:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_scePngDecParseHeader\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_scePngDecParseHeader]\n");

void __load_and_call_scePngDecParseHeader();
static __attribute__ ((used)) void* __ptr_scePngDecParseHeader = &__load_and_call_scePngDecParseHeader;

static __attribute__ ((used)) void
__load_scePngDecParseHeader(void) {
  sprx_dlsym(__handle, "scePngDecParseHeader", &__ptr_scePngDecParseHeader);
}

asm(".intel_syntax noprefix\n"
    ".global scePngDecQueryMemorySize\n"
    ".type scePngDecQueryMemorySize @function\n"
    "scePngDecQueryMemorySize:\n"
    "jmp qword ptr [rip + __ptr_scePngDecQueryMemorySize]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_scePngDecQueryMemorySize\n"
    ".type __load_and_call_scePngDecQueryMemorySize @function\n"
    "__load_and_call_scePngDecQueryMemorySize:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_scePngDecQueryMemorySize\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_scePngDecQueryMemorySize]\n");

void __load_and_call_scePngDecQueryMemorySize();
static __attribute__ ((used)) void* __ptr_scePngDecQueryMemorySize = &__load_and_call_scePngDecQueryMemorySize;

static __attribute__ ((used)) void
__load_scePngDecQueryMemorySize(void) {
  sprx_dlsym(__handle, "scePngDecQueryMemorySize", &__ptr_scePngDecQueryMemorySize);
}
