/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceDseehx", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceDseehxConvert\n"
    ".type sceDseehxConvert @function\n"
    "sceDseehxConvert:\n"
    "jmp qword ptr [rip + __ptr_sceDseehxConvert]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceDseehxConvert\n"
    ".type __load_and_call_sceDseehxConvert @function\n"
    "__load_and_call_sceDseehxConvert:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceDseehxConvert\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceDseehxConvert]\n");

void __load_and_call_sceDseehxConvert();
static __attribute__ ((used)) void* __ptr_sceDseehxConvert = &__load_and_call_sceDseehxConvert;

static __attribute__ ((used)) void
__load_sceDseehxConvert(void) {
  sprx_dlsym(__handle, "sceDseehxConvert", &__ptr_sceDseehxConvert);
}

asm(".intel_syntax noprefix\n"
    ".global sceDseehxExtInit\n"
    ".type sceDseehxExtInit @function\n"
    "sceDseehxExtInit:\n"
    "jmp qword ptr [rip + __ptr_sceDseehxExtInit]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceDseehxExtInit\n"
    ".type __load_and_call_sceDseehxExtInit @function\n"
    "__load_and_call_sceDseehxExtInit:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceDseehxExtInit\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceDseehxExtInit]\n");

void __load_and_call_sceDseehxExtInit();
static __attribute__ ((used)) void* __ptr_sceDseehxExtInit = &__load_and_call_sceDseehxExtInit;

static __attribute__ ((used)) void
__load_sceDseehxExtInit(void) {
  sprx_dlsym(__handle, "sceDseehxExtInit", &__ptr_sceDseehxExtInit);
}

asm(".intel_syntax noprefix\n"
    ".global sceDseehxFlush\n"
    ".type sceDseehxFlush @function\n"
    "sceDseehxFlush:\n"
    "jmp qword ptr [rip + __ptr_sceDseehxFlush]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceDseehxFlush\n"
    ".type __load_and_call_sceDseehxFlush @function\n"
    "__load_and_call_sceDseehxFlush:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceDseehxFlush\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceDseehxFlush]\n");

void __load_and_call_sceDseehxFlush();
static __attribute__ ((used)) void* __ptr_sceDseehxFlush = &__load_and_call_sceDseehxFlush;

static __attribute__ ((used)) void
__load_sceDseehxFlush(void) {
  sprx_dlsym(__handle, "sceDseehxFlush", &__ptr_sceDseehxFlush);
}

asm(".intel_syntax noprefix\n"
    ".global sceDseehxInit\n"
    ".type sceDseehxInit @function\n"
    "sceDseehxInit:\n"
    "jmp qword ptr [rip + __ptr_sceDseehxInit]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceDseehxInit\n"
    ".type __load_and_call_sceDseehxInit @function\n"
    "__load_and_call_sceDseehxInit:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceDseehxInit\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceDseehxInit]\n");

void __load_and_call_sceDseehxInit();
static __attribute__ ((used)) void* __ptr_sceDseehxInit = &__load_and_call_sceDseehxInit;

static __attribute__ ((used)) void
__load_sceDseehxInit(void) {
  sprx_dlsym(__handle, "sceDseehxInit", &__ptr_sceDseehxInit);
}
