/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceSigninDialog", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceSigninDialogClose\n"
    ".type sceSigninDialogClose @function\n"
    "sceSigninDialogClose:\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogClose]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSigninDialogClose\n"
    ".type __load_and_call_sceSigninDialogClose @function\n"
    "__load_and_call_sceSigninDialogClose:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSigninDialogClose\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogClose]\n");

void __load_and_call_sceSigninDialogClose();
static __attribute__ ((used)) void* __ptr_sceSigninDialogClose = &__load_and_call_sceSigninDialogClose;

static __attribute__ ((used)) void
__load_sceSigninDialogClose(void) {
  sprx_dlsym(__handle, "sceSigninDialogClose", &__ptr_sceSigninDialogClose);
}

asm(".intel_syntax noprefix\n"
    ".global sceSigninDialogGetResult\n"
    ".type sceSigninDialogGetResult @function\n"
    "sceSigninDialogGetResult:\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogGetResult]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSigninDialogGetResult\n"
    ".type __load_and_call_sceSigninDialogGetResult @function\n"
    "__load_and_call_sceSigninDialogGetResult:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSigninDialogGetResult\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogGetResult]\n");

void __load_and_call_sceSigninDialogGetResult();
static __attribute__ ((used)) void* __ptr_sceSigninDialogGetResult = &__load_and_call_sceSigninDialogGetResult;

static __attribute__ ((used)) void
__load_sceSigninDialogGetResult(void) {
  sprx_dlsym(__handle, "sceSigninDialogGetResult", &__ptr_sceSigninDialogGetResult);
}

asm(".intel_syntax noprefix\n"
    ".global sceSigninDialogGetStatus\n"
    ".type sceSigninDialogGetStatus @function\n"
    "sceSigninDialogGetStatus:\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogGetStatus]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSigninDialogGetStatus\n"
    ".type __load_and_call_sceSigninDialogGetStatus @function\n"
    "__load_and_call_sceSigninDialogGetStatus:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSigninDialogGetStatus\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogGetStatus]\n");

void __load_and_call_sceSigninDialogGetStatus();
static __attribute__ ((used)) void* __ptr_sceSigninDialogGetStatus = &__load_and_call_sceSigninDialogGetStatus;

static __attribute__ ((used)) void
__load_sceSigninDialogGetStatus(void) {
  sprx_dlsym(__handle, "sceSigninDialogGetStatus", &__ptr_sceSigninDialogGetStatus);
}

asm(".intel_syntax noprefix\n"
    ".global sceSigninDialogInitialize\n"
    ".type sceSigninDialogInitialize @function\n"
    "sceSigninDialogInitialize:\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogInitialize]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSigninDialogInitialize\n"
    ".type __load_and_call_sceSigninDialogInitialize @function\n"
    "__load_and_call_sceSigninDialogInitialize:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSigninDialogInitialize\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogInitialize]\n");

void __load_and_call_sceSigninDialogInitialize();
static __attribute__ ((used)) void* __ptr_sceSigninDialogInitialize = &__load_and_call_sceSigninDialogInitialize;

static __attribute__ ((used)) void
__load_sceSigninDialogInitialize(void) {
  sprx_dlsym(__handle, "sceSigninDialogInitialize", &__ptr_sceSigninDialogInitialize);
}

asm(".intel_syntax noprefix\n"
    ".global sceSigninDialogOpen\n"
    ".type sceSigninDialogOpen @function\n"
    "sceSigninDialogOpen:\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogOpen]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSigninDialogOpen\n"
    ".type __load_and_call_sceSigninDialogOpen @function\n"
    "__load_and_call_sceSigninDialogOpen:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSigninDialogOpen\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogOpen]\n");

void __load_and_call_sceSigninDialogOpen();
static __attribute__ ((used)) void* __ptr_sceSigninDialogOpen = &__load_and_call_sceSigninDialogOpen;

static __attribute__ ((used)) void
__load_sceSigninDialogOpen(void) {
  sprx_dlsym(__handle, "sceSigninDialogOpen", &__ptr_sceSigninDialogOpen);
}

asm(".intel_syntax noprefix\n"
    ".global sceSigninDialogTerminate\n"
    ".type sceSigninDialogTerminate @function\n"
    "sceSigninDialogTerminate:\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogTerminate]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSigninDialogTerminate\n"
    ".type __load_and_call_sceSigninDialogTerminate @function\n"
    "__load_and_call_sceSigninDialogTerminate:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSigninDialogTerminate\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogTerminate]\n");

void __load_and_call_sceSigninDialogTerminate();
static __attribute__ ((used)) void* __ptr_sceSigninDialogTerminate = &__load_and_call_sceSigninDialogTerminate;

static __attribute__ ((used)) void
__load_sceSigninDialogTerminate(void) {
  sprx_dlsym(__handle, "sceSigninDialogTerminate", &__ptr_sceSigninDialogTerminate);
}

asm(".intel_syntax noprefix\n"
    ".global sceSigninDialogUpdateStatus\n"
    ".type sceSigninDialogUpdateStatus @function\n"
    "sceSigninDialogUpdateStatus:\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogUpdateStatus]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSigninDialogUpdateStatus\n"
    ".type __load_and_call_sceSigninDialogUpdateStatus @function\n"
    "__load_and_call_sceSigninDialogUpdateStatus:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSigninDialogUpdateStatus\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSigninDialogUpdateStatus]\n");

void __load_and_call_sceSigninDialogUpdateStatus();
static __attribute__ ((used)) void* __ptr_sceSigninDialogUpdateStatus = &__load_and_call_sceSigninDialogUpdateStatus;

static __attribute__ ((used)) void
__load_sceSigninDialogUpdateStatus(void) {
  sprx_dlsym(__handle, "sceSigninDialogUpdateStatus", &__ptr_sceSigninDialogUpdateStatus);
}
