/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceAudiodec", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceAudiodecClearContext\n"
    ".type sceAudiodecClearContext @function\n"
    "sceAudiodecClearContext:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecClearContext]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecClearContext\n"
    ".type __load_and_call_sceAudiodecClearContext @function\n"
    "__load_and_call_sceAudiodecClearContext:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecClearContext\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecClearContext]\n");

void __load_and_call_sceAudiodecClearContext();
static __attribute__ ((used)) void* __ptr_sceAudiodecClearContext = &__load_and_call_sceAudiodecClearContext;

static __attribute__ ((used)) void
__load_sceAudiodecClearContext(void) {
  sprx_dlsym(__handle, "sceAudiodecClearContext", &__ptr_sceAudiodecClearContext);
}

asm(".intel_syntax noprefix\n"
    ".global sceAudiodecCreateDecoder\n"
    ".type sceAudiodecCreateDecoder @function\n"
    "sceAudiodecCreateDecoder:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecCreateDecoder]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecCreateDecoder\n"
    ".type __load_and_call_sceAudiodecCreateDecoder @function\n"
    "__load_and_call_sceAudiodecCreateDecoder:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecCreateDecoder\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecCreateDecoder]\n");

void __load_and_call_sceAudiodecCreateDecoder();
static __attribute__ ((used)) void* __ptr_sceAudiodecCreateDecoder = &__load_and_call_sceAudiodecCreateDecoder;

static __attribute__ ((used)) void
__load_sceAudiodecCreateDecoder(void) {
  sprx_dlsym(__handle, "sceAudiodecCreateDecoder", &__ptr_sceAudiodecCreateDecoder);
}

asm(".intel_syntax noprefix\n"
    ".global sceAudiodecDecode\n"
    ".type sceAudiodecDecode @function\n"
    "sceAudiodecDecode:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDecode]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecDecode\n"
    ".type __load_and_call_sceAudiodecDecode @function\n"
    "__load_and_call_sceAudiodecDecode:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecDecode\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDecode]\n");

void __load_and_call_sceAudiodecDecode();
static __attribute__ ((used)) void* __ptr_sceAudiodecDecode = &__load_and_call_sceAudiodecDecode;

static __attribute__ ((used)) void
__load_sceAudiodecDecode(void) {
  sprx_dlsym(__handle, "sceAudiodecDecode", &__ptr_sceAudiodecDecode);
}

asm(".intel_syntax noprefix\n"
    ".global sceAudiodecDecode2\n"
    ".type sceAudiodecDecode2 @function\n"
    "sceAudiodecDecode2:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDecode2]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecDecode2\n"
    ".type __load_and_call_sceAudiodecDecode2 @function\n"
    "__load_and_call_sceAudiodecDecode2:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecDecode2\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDecode2]\n");

void __load_and_call_sceAudiodecDecode2();
static __attribute__ ((used)) void* __ptr_sceAudiodecDecode2 = &__load_and_call_sceAudiodecDecode2;

static __attribute__ ((used)) void
__load_sceAudiodecDecode2(void) {
  sprx_dlsym(__handle, "sceAudiodecDecode2", &__ptr_sceAudiodecDecode2);
}

asm(".intel_syntax noprefix\n"
    ".global sceAudiodecDecode2WithPriority\n"
    ".type sceAudiodecDecode2WithPriority @function\n"
    "sceAudiodecDecode2WithPriority:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDecode2WithPriority]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecDecode2WithPriority\n"
    ".type __load_and_call_sceAudiodecDecode2WithPriority @function\n"
    "__load_and_call_sceAudiodecDecode2WithPriority:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecDecode2WithPriority\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDecode2WithPriority]\n");

void __load_and_call_sceAudiodecDecode2WithPriority();
static __attribute__ ((used)) void* __ptr_sceAudiodecDecode2WithPriority = &__load_and_call_sceAudiodecDecode2WithPriority;

static __attribute__ ((used)) void
__load_sceAudiodecDecode2WithPriority(void) {
  sprx_dlsym(__handle, "sceAudiodecDecode2WithPriority", &__ptr_sceAudiodecDecode2WithPriority);
}

asm(".intel_syntax noprefix\n"
    ".global sceAudiodecDecodeWithPriority\n"
    ".type sceAudiodecDecodeWithPriority @function\n"
    "sceAudiodecDecodeWithPriority:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDecodeWithPriority]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecDecodeWithPriority\n"
    ".type __load_and_call_sceAudiodecDecodeWithPriority @function\n"
    "__load_and_call_sceAudiodecDecodeWithPriority:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecDecodeWithPriority\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDecodeWithPriority]\n");

void __load_and_call_sceAudiodecDecodeWithPriority();
static __attribute__ ((used)) void* __ptr_sceAudiodecDecodeWithPriority = &__load_and_call_sceAudiodecDecodeWithPriority;

static __attribute__ ((used)) void
__load_sceAudiodecDecodeWithPriority(void) {
  sprx_dlsym(__handle, "sceAudiodecDecodeWithPriority", &__ptr_sceAudiodecDecodeWithPriority);
}

asm(".intel_syntax noprefix\n"
    ".global sceAudiodecDeleteDecoder\n"
    ".type sceAudiodecDeleteDecoder @function\n"
    "sceAudiodecDeleteDecoder:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDeleteDecoder]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecDeleteDecoder\n"
    ".type __load_and_call_sceAudiodecDeleteDecoder @function\n"
    "__load_and_call_sceAudiodecDeleteDecoder:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecDeleteDecoder\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecDeleteDecoder]\n");

void __load_and_call_sceAudiodecDeleteDecoder();
static __attribute__ ((used)) void* __ptr_sceAudiodecDeleteDecoder = &__load_and_call_sceAudiodecDeleteDecoder;

static __attribute__ ((used)) void
__load_sceAudiodecDeleteDecoder(void) {
  sprx_dlsym(__handle, "sceAudiodecDeleteDecoder", &__ptr_sceAudiodecDeleteDecoder);
}

asm(".intel_syntax noprefix\n"
    ".global sceAudiodecInitLibrary\n"
    ".type sceAudiodecInitLibrary @function\n"
    "sceAudiodecInitLibrary:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecInitLibrary]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecInitLibrary\n"
    ".type __load_and_call_sceAudiodecInitLibrary @function\n"
    "__load_and_call_sceAudiodecInitLibrary:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecInitLibrary\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecInitLibrary]\n");

void __load_and_call_sceAudiodecInitLibrary();
static __attribute__ ((used)) void* __ptr_sceAudiodecInitLibrary = &__load_and_call_sceAudiodecInitLibrary;

static __attribute__ ((used)) void
__load_sceAudiodecInitLibrary(void) {
  sprx_dlsym(__handle, "sceAudiodecInitLibrary", &__ptr_sceAudiodecInitLibrary);
}

asm(".intel_syntax noprefix\n"
    ".global sceAudiodecTermLibrary\n"
    ".type sceAudiodecTermLibrary @function\n"
    "sceAudiodecTermLibrary:\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecTermLibrary]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAudiodecTermLibrary\n"
    ".type __load_and_call_sceAudiodecTermLibrary @function\n"
    "__load_and_call_sceAudiodecTermLibrary:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAudiodecTermLibrary\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAudiodecTermLibrary]\n");

void __load_and_call_sceAudiodecTermLibrary();
static __attribute__ ((used)) void* __ptr_sceAudiodecTermLibrary = &__load_and_call_sceAudiodecTermLibrary;

static __attribute__ ((used)) void
__load_sceAudiodecTermLibrary(void) {
  sprx_dlsym(__handle, "sceAudiodecTermLibrary", &__ptr_sceAudiodecTermLibrary);
}
