/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceSystemLogger2Delivery", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceSystemLogger2DeliveryGetBatchResult\n"
    ".type sceSystemLogger2DeliveryGetBatchResult @function\n"
    "sceSystemLogger2DeliveryGetBatchResult:\n"
    "jmp qword ptr [rip + __ptr_sceSystemLogger2DeliveryGetBatchResult]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSystemLogger2DeliveryGetBatchResult\n"
    ".type __load_and_call_sceSystemLogger2DeliveryGetBatchResult @function\n"
    "__load_and_call_sceSystemLogger2DeliveryGetBatchResult:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSystemLogger2DeliveryGetBatchResult\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSystemLogger2DeliveryGetBatchResult]\n");

void __load_and_call_sceSystemLogger2DeliveryGetBatchResult();
static __attribute__ ((used)) void* __ptr_sceSystemLogger2DeliveryGetBatchResult = &__load_and_call_sceSystemLogger2DeliveryGetBatchResult;

static __attribute__ ((used)) void
__load_sceSystemLogger2DeliveryGetBatchResult(void) {
  sprx_dlsym(__handle, "sceSystemLogger2DeliveryGetBatchResult", &__ptr_sceSystemLogger2DeliveryGetBatchResult);
}

asm(".intel_syntax noprefix\n"
    ".global sceSystemLogger2DeliveryGetResult\n"
    ".type sceSystemLogger2DeliveryGetResult @function\n"
    "sceSystemLogger2DeliveryGetResult:\n"
    "jmp qword ptr [rip + __ptr_sceSystemLogger2DeliveryGetResult]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSystemLogger2DeliveryGetResult\n"
    ".type __load_and_call_sceSystemLogger2DeliveryGetResult @function\n"
    "__load_and_call_sceSystemLogger2DeliveryGetResult:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSystemLogger2DeliveryGetResult\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSystemLogger2DeliveryGetResult]\n");

void __load_and_call_sceSystemLogger2DeliveryGetResult();
static __attribute__ ((used)) void* __ptr_sceSystemLogger2DeliveryGetResult = &__load_and_call_sceSystemLogger2DeliveryGetResult;

static __attribute__ ((used)) void
__load_sceSystemLogger2DeliveryGetResult(void) {
  sprx_dlsym(__handle, "sceSystemLogger2DeliveryGetResult", &__ptr_sceSystemLogger2DeliveryGetResult);
}

asm(".intel_syntax noprefix\n"
    ".global sceSystemLogger2DeliverySetBatchDeliveryEvent\n"
    ".type sceSystemLogger2DeliverySetBatchDeliveryEvent @function\n"
    "sceSystemLogger2DeliverySetBatchDeliveryEvent:\n"
    "jmp qword ptr [rip + __ptr_sceSystemLogger2DeliverySetBatchDeliveryEvent]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSystemLogger2DeliverySetBatchDeliveryEvent\n"
    ".type __load_and_call_sceSystemLogger2DeliverySetBatchDeliveryEvent @function\n"
    "__load_and_call_sceSystemLogger2DeliverySetBatchDeliveryEvent:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSystemLogger2DeliverySetBatchDeliveryEvent\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSystemLogger2DeliverySetBatchDeliveryEvent]\n");

void __load_and_call_sceSystemLogger2DeliverySetBatchDeliveryEvent();
static __attribute__ ((used)) void* __ptr_sceSystemLogger2DeliverySetBatchDeliveryEvent = &__load_and_call_sceSystemLogger2DeliverySetBatchDeliveryEvent;

static __attribute__ ((used)) void
__load_sceSystemLogger2DeliverySetBatchDeliveryEvent(void) {
  sprx_dlsym(__handle, "sceSystemLogger2DeliverySetBatchDeliveryEvent", &__ptr_sceSystemLogger2DeliverySetBatchDeliveryEvent);
}

asm(".intel_syntax noprefix\n"
    ".global sceSystemLogger2DeliveryTerminate\n"
    ".type sceSystemLogger2DeliveryTerminate @function\n"
    "sceSystemLogger2DeliveryTerminate:\n"
    "jmp qword ptr [rip + __ptr_sceSystemLogger2DeliveryTerminate]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceSystemLogger2DeliveryTerminate\n"
    ".type __load_and_call_sceSystemLogger2DeliveryTerminate @function\n"
    "__load_and_call_sceSystemLogger2DeliveryTerminate:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceSystemLogger2DeliveryTerminate\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceSystemLogger2DeliveryTerminate]\n");

void __load_and_call_sceSystemLogger2DeliveryTerminate();
static __attribute__ ((used)) void* __ptr_sceSystemLogger2DeliveryTerminate = &__load_and_call_sceSystemLogger2DeliveryTerminate;

static __attribute__ ((used)) void
__load_sceSystemLogger2DeliveryTerminate(void) {
  sprx_dlsym(__handle, "sceSystemLogger2DeliveryTerminate", &__ptr_sceSystemLogger2DeliveryTerminate);
}
