/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceIdu", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceIduGetEnv\n"
    ".type sceIduGetEnv @function\n"
    "sceIduGetEnv:\n"
    "jmp qword ptr [rip + __ptr_sceIduGetEnv]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceIduGetEnv\n"
    ".type __load_and_call_sceIduGetEnv @function\n"
    "__load_and_call_sceIduGetEnv:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceIduGetEnv\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceIduGetEnv]\n");

void __load_and_call_sceIduGetEnv();
static __attribute__ ((used)) void* __ptr_sceIduGetEnv = &__load_and_call_sceIduGetEnv;

static __attribute__ ((used)) void
__load_sceIduGetEnv(void) {
  sprx_dlsym(__handle, "sceIduGetEnv", &__ptr_sceIduGetEnv);
}

asm(".intel_syntax noprefix\n"
    ".global sceIduInit\n"
    ".type sceIduInit @function\n"
    "sceIduInit:\n"
    "jmp qword ptr [rip + __ptr_sceIduInit]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceIduInit\n"
    ".type __load_and_call_sceIduInit @function\n"
    "__load_and_call_sceIduInit:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceIduInit\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceIduInit]\n");

void __load_and_call_sceIduInit();
static __attribute__ ((used)) void* __ptr_sceIduInit = &__load_and_call_sceIduInit;

static __attribute__ ((used)) void
__load_sceIduInit(void) {
  sprx_dlsym(__handle, "sceIduInit", &__ptr_sceIduInit);
}

asm(".intel_syntax noprefix\n"
    ".global sceIduInstallPkg\n"
    ".type sceIduInstallPkg @function\n"
    "sceIduInstallPkg:\n"
    "jmp qword ptr [rip + __ptr_sceIduInstallPkg]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceIduInstallPkg\n"
    ".type __load_and_call_sceIduInstallPkg @function\n"
    "__load_and_call_sceIduInstallPkg:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceIduInstallPkg\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceIduInstallPkg]\n");

void __load_and_call_sceIduInstallPkg();
static __attribute__ ((used)) void* __ptr_sceIduInstallPkg = &__load_and_call_sceIduInstallPkg;

static __attribute__ ((used)) void
__load_sceIduInstallPkg(void) {
  sprx_dlsym(__handle, "sceIduInstallPkg", &__ptr_sceIduInstallPkg);
}

asm(".intel_syntax noprefix\n"
    ".global sceIduIsAppInstalled\n"
    ".type sceIduIsAppInstalled @function\n"
    "sceIduIsAppInstalled:\n"
    "jmp qword ptr [rip + __ptr_sceIduIsAppInstalled]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceIduIsAppInstalled\n"
    ".type __load_and_call_sceIduIsAppInstalled @function\n"
    "__load_and_call_sceIduIsAppInstalled:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceIduIsAppInstalled\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceIduIsAppInstalled]\n");

void __load_and_call_sceIduIsAppInstalled();
static __attribute__ ((used)) void* __ptr_sceIduIsAppInstalled = &__load_and_call_sceIduIsAppInstalled;

static __attribute__ ((used)) void
__load_sceIduIsAppInstalled(void) {
  sprx_dlsym(__handle, "sceIduIsAppInstalled", &__ptr_sceIduIsAppInstalled);
}

asm(".intel_syntax noprefix\n"
    ".global sceIduIsRifInstalled\n"
    ".type sceIduIsRifInstalled @function\n"
    "sceIduIsRifInstalled:\n"
    "jmp qword ptr [rip + __ptr_sceIduIsRifInstalled]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceIduIsRifInstalled\n"
    ".type __load_and_call_sceIduIsRifInstalled @function\n"
    "__load_and_call_sceIduIsRifInstalled:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceIduIsRifInstalled\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceIduIsRifInstalled]\n");

void __load_and_call_sceIduIsRifInstalled();
static __attribute__ ((used)) void* __ptr_sceIduIsRifInstalled = &__load_and_call_sceIduIsRifInstalled;

static __attribute__ ((used)) void
__load_sceIduIsRifInstalled(void) {
  sprx_dlsym(__handle, "sceIduIsRifInstalled", &__ptr_sceIduIsRifInstalled);
}

asm(".intel_syntax noprefix\n"
    ".global sceIduIsStaffMode\n"
    ".type sceIduIsStaffMode @function\n"
    "sceIduIsStaffMode:\n"
    "jmp qword ptr [rip + __ptr_sceIduIsStaffMode]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceIduIsStaffMode\n"
    ".type __load_and_call_sceIduIsStaffMode @function\n"
    "__load_and_call_sceIduIsStaffMode:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceIduIsStaffMode\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceIduIsStaffMode]\n");

void __load_and_call_sceIduIsStaffMode();
static __attribute__ ((used)) void* __ptr_sceIduIsStaffMode = &__load_and_call_sceIduIsStaffMode;

static __attribute__ ((used)) void
__load_sceIduIsStaffMode(void) {
  sprx_dlsym(__handle, "sceIduIsStaffMode", &__ptr_sceIduIsStaffMode);
}

asm(".intel_syntax noprefix\n"
    ".global sceIduReboot\n"
    ".type sceIduReboot @function\n"
    "sceIduReboot:\n"
    "jmp qword ptr [rip + __ptr_sceIduReboot]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceIduReboot\n"
    ".type __load_and_call_sceIduReboot @function\n"
    "__load_and_call_sceIduReboot:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceIduReboot\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceIduReboot]\n");

void __load_and_call_sceIduReboot();
static __attribute__ ((used)) void* __ptr_sceIduReboot = &__load_and_call_sceIduReboot;

static __attribute__ ((used)) void
__load_sceIduReboot(void) {
  sprx_dlsym(__handle, "sceIduReboot", &__ptr_sceIduReboot);
}

asm(".intel_syntax noprefix\n"
    ".global sceIduTerm\n"
    ".type sceIduTerm @function\n"
    "sceIduTerm:\n"
    "jmp qword ptr [rip + __ptr_sceIduTerm]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceIduTerm\n"
    ".type __load_and_call_sceIduTerm @function\n"
    "__load_and_call_sceIduTerm:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceIduTerm\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceIduTerm]\n");

void __load_and_call_sceIduTerm();
static __attribute__ ((used)) void* __ptr_sceIduTerm = &__load_and_call_sceIduTerm;

static __attribute__ ((used)) void
__load_sceIduTerm(void) {
  sprx_dlsym(__handle, "sceIduTerm", &__ptr_sceIduTerm);
}
