/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceAcm", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceAcmBatchStartBuffer\n"
    ".type sceAcmBatchStartBuffer @function\n"
    "sceAcmBatchStartBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchStartBuffer]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcmBatchStartBuffer\n"
    ".type __load_and_call_sceAcmBatchStartBuffer @function\n"
    "__load_and_call_sceAcmBatchStartBuffer:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcmBatchStartBuffer\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchStartBuffer]\n");

void __load_and_call_sceAcmBatchStartBuffer();
static __attribute__ ((used)) void* __ptr_sceAcmBatchStartBuffer = &__load_and_call_sceAcmBatchStartBuffer;

static __attribute__ ((used)) void
__load_sceAcmBatchStartBuffer(void) {
  sprx_dlsym(__handle, "sceAcmBatchStartBuffer", &__ptr_sceAcmBatchStartBuffer);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcmBatchStartBuffers\n"
    ".type sceAcmBatchStartBuffers @function\n"
    "sceAcmBatchStartBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchStartBuffers]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcmBatchStartBuffers\n"
    ".type __load_and_call_sceAcmBatchStartBuffers @function\n"
    "__load_and_call_sceAcmBatchStartBuffers:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcmBatchStartBuffers\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchStartBuffers]\n");

void __load_and_call_sceAcmBatchStartBuffers();
static __attribute__ ((used)) void* __ptr_sceAcmBatchStartBuffers = &__load_and_call_sceAcmBatchStartBuffers;

static __attribute__ ((used)) void
__load_sceAcmBatchStartBuffers(void) {
  sprx_dlsym(__handle, "sceAcmBatchStartBuffers", &__ptr_sceAcmBatchStartBuffers);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcmBatchWait\n"
    ".type sceAcmBatchWait @function\n"
    "sceAcmBatchWait:\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchWait]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcmBatchWait\n"
    ".type __load_and_call_sceAcmBatchWait @function\n"
    "__load_and_call_sceAcmBatchWait:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcmBatchWait\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcmBatchWait]\n");

void __load_and_call_sceAcmBatchWait();
static __attribute__ ((used)) void* __ptr_sceAcmBatchWait = &__load_and_call_sceAcmBatchWait;

static __attribute__ ((used)) void
__load_sceAcmBatchWait(void) {
  sprx_dlsym(__handle, "sceAcmBatchWait", &__ptr_sceAcmBatchWait);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcmContextCreate\n"
    ".type sceAcmContextCreate @function\n"
    "sceAcmContextCreate:\n"
    "jmp qword ptr [rip + __ptr_sceAcmContextCreate]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcmContextCreate\n"
    ".type __load_and_call_sceAcmContextCreate @function\n"
    "__load_and_call_sceAcmContextCreate:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcmContextCreate\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcmContextCreate]\n");

void __load_and_call_sceAcmContextCreate();
static __attribute__ ((used)) void* __ptr_sceAcmContextCreate = &__load_and_call_sceAcmContextCreate;

static __attribute__ ((used)) void
__load_sceAcmContextCreate(void) {
  sprx_dlsym(__handle, "sceAcmContextCreate", &__ptr_sceAcmContextCreate);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcmContextDestroy\n"
    ".type sceAcmContextDestroy @function\n"
    "sceAcmContextDestroy:\n"
    "jmp qword ptr [rip + __ptr_sceAcmContextDestroy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcmContextDestroy\n"
    ".type __load_and_call_sceAcmContextDestroy @function\n"
    "__load_and_call_sceAcmContextDestroy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcmContextDestroy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcmContextDestroy]\n");

void __load_and_call_sceAcmContextDestroy();
static __attribute__ ((used)) void* __ptr_sceAcmContextDestroy = &__load_and_call_sceAcmContextDestroy;

static __attribute__ ((used)) void
__load_sceAcmContextDestroy(void) {
  sprx_dlsym(__handle, "sceAcmContextDestroy", &__ptr_sceAcmContextDestroy);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcm_ConvReverb_SharedInput\n"
    ".type sceAcm_ConvReverb_SharedInput @function\n"
    "sceAcm_ConvReverb_SharedInput:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_ConvReverb_SharedInput]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcm_ConvReverb_SharedInput\n"
    ".type __load_and_call_sceAcm_ConvReverb_SharedInput @function\n"
    "__load_and_call_sceAcm_ConvReverb_SharedInput:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcm_ConvReverb_SharedInput\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcm_ConvReverb_SharedInput]\n");

void __load_and_call_sceAcm_ConvReverb_SharedInput();
static __attribute__ ((used)) void* __ptr_sceAcm_ConvReverb_SharedInput = &__load_and_call_sceAcm_ConvReverb_SharedInput;

static __attribute__ ((used)) void
__load_sceAcm_ConvReverb_SharedInput(void) {
  sprx_dlsym(__handle, "sceAcm_ConvReverb_SharedInput", &__ptr_sceAcm_ConvReverb_SharedInput);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcm_ConvReverb_SharedIr\n"
    ".type sceAcm_ConvReverb_SharedIr @function\n"
    "sceAcm_ConvReverb_SharedIr:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_ConvReverb_SharedIr]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcm_ConvReverb_SharedIr\n"
    ".type __load_and_call_sceAcm_ConvReverb_SharedIr @function\n"
    "__load_and_call_sceAcm_ConvReverb_SharedIr:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcm_ConvReverb_SharedIr\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcm_ConvReverb_SharedIr]\n");

void __load_and_call_sceAcm_ConvReverb_SharedIr();
static __attribute__ ((used)) void* __ptr_sceAcm_ConvReverb_SharedIr = &__load_and_call_sceAcm_ConvReverb_SharedIr;

static __attribute__ ((used)) void
__load_sceAcm_ConvReverb_SharedIr(void) {
  sprx_dlsym(__handle, "sceAcm_ConvReverb_SharedIr", &__ptr_sceAcm_ConvReverb_SharedIr);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcm_FFT\n"
    ".type sceAcm_FFT @function\n"
    "sceAcm_FFT:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_FFT]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcm_FFT\n"
    ".type __load_and_call_sceAcm_FFT @function\n"
    "__load_and_call_sceAcm_FFT:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcm_FFT\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcm_FFT]\n");

void __load_and_call_sceAcm_FFT();
static __attribute__ ((used)) void* __ptr_sceAcm_FFT = &__load_and_call_sceAcm_FFT;

static __attribute__ ((used)) void
__load_sceAcm_FFT(void) {
  sprx_dlsym(__handle, "sceAcm_FFT", &__ptr_sceAcm_FFT);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcm_IFFT\n"
    ".type sceAcm_IFFT @function\n"
    "sceAcm_IFFT:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_IFFT]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcm_IFFT\n"
    ".type __load_and_call_sceAcm_IFFT @function\n"
    "__load_and_call_sceAcm_IFFT:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcm_IFFT\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcm_IFFT]\n");

void __load_and_call_sceAcm_IFFT();
static __attribute__ ((used)) void* __ptr_sceAcm_IFFT = &__load_and_call_sceAcm_IFFT;

static __attribute__ ((used)) void
__load_sceAcm_IFFT(void) {
  sprx_dlsym(__handle, "sceAcm_IFFT", &__ptr_sceAcm_IFFT);
}

asm(".intel_syntax noprefix\n"
    ".global sceAcm_Panner\n"
    ".type sceAcm_Panner @function\n"
    "sceAcm_Panner:\n"
    "jmp qword ptr [rip + __ptr_sceAcm_Panner]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAcm_Panner\n"
    ".type __load_and_call_sceAcm_Panner @function\n"
    "__load_and_call_sceAcm_Panner:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAcm_Panner\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAcm_Panner]\n");

void __load_and_call_sceAcm_Panner();
static __attribute__ ((used)) void* __ptr_sceAcm_Panner = &__load_and_call_sceAcm_Panner;

static __attribute__ ((used)) void
__load_sceAcm_Panner(void) {
  sprx_dlsym(__handle, "sceAcm_Panner", &__ptr_sceAcm_Panner);
}
