/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceMbus", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceMbusAcquireControl\n"
    ".type sceMbusAcquireControl @function\n"
    "sceMbusAcquireControl:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControl]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAcquireControl\n"
    ".type __load_and_call_sceMbusAcquireControl @function\n"
    "__load_and_call_sceMbusAcquireControl:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAcquireControl\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControl]\n");

void __load_and_call_sceMbusAcquireControl();
static __attribute__ ((used)) void* __ptr_sceMbusAcquireControl = &__load_and_call_sceMbusAcquireControl;

static __attribute__ ((used)) void
__load_sceMbusAcquireControl(void) {
  sprx_dlsym(__handle, "sceMbusAcquireControl", &__ptr_sceMbusAcquireControl);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAcquireControlList\n"
    ".type sceMbusAcquireControlList @function\n"
    "sceMbusAcquireControlList:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControlList]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAcquireControlList\n"
    ".type __load_and_call_sceMbusAcquireControlList @function\n"
    "__load_and_call_sceMbusAcquireControlList:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAcquireControlList\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControlList]\n");

void __load_and_call_sceMbusAcquireControlList();
static __attribute__ ((used)) void* __ptr_sceMbusAcquireControlList = &__load_and_call_sceMbusAcquireControlList;

static __attribute__ ((used)) void
__load_sceMbusAcquireControlList(void) {
  sprx_dlsym(__handle, "sceMbusAcquireControlList", &__ptr_sceMbusAcquireControlList);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAcquireControlWithState\n"
    ".type sceMbusAcquireControlWithState @function\n"
    "sceMbusAcquireControlWithState:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControlWithState]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAcquireControlWithState\n"
    ".type __load_and_call_sceMbusAcquireControlWithState @function\n"
    "__load_and_call_sceMbusAcquireControlWithState:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAcquireControlWithState\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControlWithState]\n");

void __load_and_call_sceMbusAcquireControlWithState();
static __attribute__ ((used)) void* __ptr_sceMbusAcquireControlWithState = &__load_and_call_sceMbusAcquireControlWithState;

static __attribute__ ((used)) void
__load_sceMbusAcquireControlWithState(void) {
  sprx_dlsym(__handle, "sceMbusAcquireControlWithState", &__ptr_sceMbusAcquireControlWithState);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAcquireControlWithState2\n"
    ".type sceMbusAcquireControlWithState2 @function\n"
    "sceMbusAcquireControlWithState2:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControlWithState2]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAcquireControlWithState2\n"
    ".type __load_and_call_sceMbusAcquireControlWithState2 @function\n"
    "__load_and_call_sceMbusAcquireControlWithState2:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAcquireControlWithState2\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControlWithState2]\n");

void __load_and_call_sceMbusAcquireControlWithState2();
static __attribute__ ((used)) void* __ptr_sceMbusAcquireControlWithState2 = &__load_and_call_sceMbusAcquireControlWithState2;

static __attribute__ ((used)) void
__load_sceMbusAcquireControlWithState2(void) {
  sprx_dlsym(__handle, "sceMbusAcquireControlWithState2", &__ptr_sceMbusAcquireControlWithState2);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAcquireControlWithStateFlag\n"
    ".type sceMbusAcquireControlWithStateFlag @function\n"
    "sceMbusAcquireControlWithStateFlag:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControlWithStateFlag]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAcquireControlWithStateFlag\n"
    ".type __load_and_call_sceMbusAcquireControlWithStateFlag @function\n"
    "__load_and_call_sceMbusAcquireControlWithStateFlag:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAcquireControlWithStateFlag\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAcquireControlWithStateFlag]\n");

void __load_and_call_sceMbusAcquireControlWithStateFlag();
static __attribute__ ((used)) void* __ptr_sceMbusAcquireControlWithStateFlag = &__load_and_call_sceMbusAcquireControlWithStateFlag;

static __attribute__ ((used)) void
__load_sceMbusAcquireControlWithStateFlag(void) {
  sprx_dlsym(__handle, "sceMbusAcquireControlWithStateFlag", &__ptr_sceMbusAcquireControlWithStateFlag);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAddHandle\n"
    ".type sceMbusAddHandle @function\n"
    "sceMbusAddHandle:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandle]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAddHandle\n"
    ".type __load_and_call_sceMbusAddHandle @function\n"
    "__load_and_call_sceMbusAddHandle:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAddHandle\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandle]\n");

void __load_and_call_sceMbusAddHandle();
static __attribute__ ((used)) void* __ptr_sceMbusAddHandle = &__load_and_call_sceMbusAddHandle;

static __attribute__ ((used)) void
__load_sceMbusAddHandle(void) {
  sprx_dlsym(__handle, "sceMbusAddHandle", &__ptr_sceMbusAddHandle);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAddHandleByDeviceId\n"
    ".type sceMbusAddHandleByDeviceId @function\n"
    "sceMbusAddHandleByDeviceId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandleByDeviceId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAddHandleByDeviceId\n"
    ".type __load_and_call_sceMbusAddHandleByDeviceId @function\n"
    "__load_and_call_sceMbusAddHandleByDeviceId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAddHandleByDeviceId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandleByDeviceId]\n");

void __load_and_call_sceMbusAddHandleByDeviceId();
static __attribute__ ((used)) void* __ptr_sceMbusAddHandleByDeviceId = &__load_and_call_sceMbusAddHandleByDeviceId;

static __attribute__ ((used)) void
__load_sceMbusAddHandleByDeviceId(void) {
  sprx_dlsym(__handle, "sceMbusAddHandleByDeviceId", &__ptr_sceMbusAddHandleByDeviceId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAddHandleByUserId\n"
    ".type sceMbusAddHandleByUserId @function\n"
    "sceMbusAddHandleByUserId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandleByUserId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAddHandleByUserId\n"
    ".type __load_and_call_sceMbusAddHandleByUserId @function\n"
    "__load_and_call_sceMbusAddHandleByUserId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAddHandleByUserId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandleByUserId]\n");

void __load_and_call_sceMbusAddHandleByUserId();
static __attribute__ ((used)) void* __ptr_sceMbusAddHandleByUserId = &__load_and_call_sceMbusAddHandleByUserId;

static __attribute__ ((used)) void
__load_sceMbusAddHandleByUserId(void) {
  sprx_dlsym(__handle, "sceMbusAddHandleByUserId", &__ptr_sceMbusAddHandleByUserId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAddHandleByVidPid\n"
    ".type sceMbusAddHandleByVidPid @function\n"
    "sceMbusAddHandleByVidPid:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandleByVidPid]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAddHandleByVidPid\n"
    ".type __load_and_call_sceMbusAddHandleByVidPid @function\n"
    "__load_and_call_sceMbusAddHandleByVidPid:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAddHandleByVidPid\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandleByVidPid]\n");

void __load_and_call_sceMbusAddHandleByVidPid();
static __attribute__ ((used)) void* __ptr_sceMbusAddHandleByVidPid = &__load_and_call_sceMbusAddHandleByVidPid;

static __attribute__ ((used)) void
__load_sceMbusAddHandleByVidPid(void) {
  sprx_dlsym(__handle, "sceMbusAddHandleByVidPid", &__ptr_sceMbusAddHandleByVidPid);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAddHandleWithModuleId\n"
    ".type sceMbusAddHandleWithModuleId @function\n"
    "sceMbusAddHandleWithModuleId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandleWithModuleId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAddHandleWithModuleId\n"
    ".type __load_and_call_sceMbusAddHandleWithModuleId @function\n"
    "__load_and_call_sceMbusAddHandleWithModuleId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAddHandleWithModuleId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAddHandleWithModuleId]\n");

void __load_and_call_sceMbusAddHandleWithModuleId();
static __attribute__ ((used)) void* __ptr_sceMbusAddHandleWithModuleId = &__load_and_call_sceMbusAddHandleWithModuleId;

static __attribute__ ((used)) void
__load_sceMbusAddHandleWithModuleId(void) {
  sprx_dlsym(__handle, "sceMbusAddHandleWithModuleId", &__ptr_sceMbusAddHandleWithModuleId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusAttachToApplicationByPid\n"
    ".type sceMbusAttachToApplicationByPid @function\n"
    "sceMbusAttachToApplicationByPid:\n"
    "jmp qword ptr [rip + __ptr_sceMbusAttachToApplicationByPid]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusAttachToApplicationByPid\n"
    ".type __load_and_call_sceMbusAttachToApplicationByPid @function\n"
    "__load_and_call_sceMbusAttachToApplicationByPid:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusAttachToApplicationByPid\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusAttachToApplicationByPid]\n");

void __load_and_call_sceMbusAttachToApplicationByPid();
static __attribute__ ((used)) void* __ptr_sceMbusAttachToApplicationByPid = &__load_and_call_sceMbusAttachToApplicationByPid;

static __attribute__ ((used)) void
__load_sceMbusAttachToApplicationByPid(void) {
  sprx_dlsym(__handle, "sceMbusAttachToApplicationByPid", &__ptr_sceMbusAttachToApplicationByPid);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusBindDeviceWithUserId\n"
    ".type sceMbusBindDeviceWithUserId @function\n"
    "sceMbusBindDeviceWithUserId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusBindDeviceWithUserId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusBindDeviceWithUserId\n"
    ".type __load_and_call_sceMbusBindDeviceWithUserId @function\n"
    "__load_and_call_sceMbusBindDeviceWithUserId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusBindDeviceWithUserId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusBindDeviceWithUserId]\n");

void __load_and_call_sceMbusBindDeviceWithUserId();
static __attribute__ ((used)) void* __ptr_sceMbusBindDeviceWithUserId = &__load_and_call_sceMbusBindDeviceWithUserId;

static __attribute__ ((used)) void
__load_sceMbusBindDeviceWithUserId(void) {
  sprx_dlsym(__handle, "sceMbusBindDeviceWithUserId", &__ptr_sceMbusBindDeviceWithUserId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusChangeAppModuleState\n"
    ".type sceMbusChangeAppModuleState @function\n"
    "sceMbusChangeAppModuleState:\n"
    "jmp qword ptr [rip + __ptr_sceMbusChangeAppModuleState]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusChangeAppModuleState\n"
    ".type __load_and_call_sceMbusChangeAppModuleState @function\n"
    "__load_and_call_sceMbusChangeAppModuleState:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusChangeAppModuleState\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusChangeAppModuleState]\n");

void __load_and_call_sceMbusChangeAppModuleState();
static __attribute__ ((used)) void* __ptr_sceMbusChangeAppModuleState = &__load_and_call_sceMbusChangeAppModuleState;

static __attribute__ ((used)) void
__load_sceMbusChangeAppModuleState(void) {
  sprx_dlsym(__handle, "sceMbusChangeAppModuleState", &__ptr_sceMbusChangeAppModuleState);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusCheckDriverCallback\n"
    ".type sceMbusCheckDriverCallback @function\n"
    "sceMbusCheckDriverCallback:\n"
    "jmp qword ptr [rip + __ptr_sceMbusCheckDriverCallback]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusCheckDriverCallback\n"
    ".type __load_and_call_sceMbusCheckDriverCallback @function\n"
    "__load_and_call_sceMbusCheckDriverCallback:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusCheckDriverCallback\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusCheckDriverCallback]\n");

void __load_and_call_sceMbusCheckDriverCallback();
static __attribute__ ((used)) void* __ptr_sceMbusCheckDriverCallback = &__load_and_call_sceMbusCheckDriverCallback;

static __attribute__ ((used)) void
__load_sceMbusCheckDriverCallback(void) {
  sprx_dlsym(__handle, "sceMbusCheckDriverCallback", &__ptr_sceMbusCheckDriverCallback);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusConvertToLocalDeviceId\n"
    ".type sceMbusConvertToLocalDeviceId @function\n"
    "sceMbusConvertToLocalDeviceId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusConvertToLocalDeviceId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusConvertToLocalDeviceId\n"
    ".type __load_and_call_sceMbusConvertToLocalDeviceId @function\n"
    "__load_and_call_sceMbusConvertToLocalDeviceId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusConvertToLocalDeviceId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusConvertToLocalDeviceId]\n");

void __load_and_call_sceMbusConvertToLocalDeviceId();
static __attribute__ ((used)) void* __ptr_sceMbusConvertToLocalDeviceId = &__load_and_call_sceMbusConvertToLocalDeviceId;

static __attribute__ ((used)) void
__load_sceMbusConvertToLocalDeviceId(void) {
  sprx_dlsym(__handle, "sceMbusConvertToLocalDeviceId", &__ptr_sceMbusConvertToLocalDeviceId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusConvertToLocalDeviceId2\n"
    ".type sceMbusConvertToLocalDeviceId2 @function\n"
    "sceMbusConvertToLocalDeviceId2:\n"
    "jmp qword ptr [rip + __ptr_sceMbusConvertToLocalDeviceId2]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusConvertToLocalDeviceId2\n"
    ".type __load_and_call_sceMbusConvertToLocalDeviceId2 @function\n"
    "__load_and_call_sceMbusConvertToLocalDeviceId2:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusConvertToLocalDeviceId2\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusConvertToLocalDeviceId2]\n");

void __load_and_call_sceMbusConvertToLocalDeviceId2();
static __attribute__ ((used)) void* __ptr_sceMbusConvertToLocalDeviceId2 = &__load_and_call_sceMbusConvertToLocalDeviceId2;

static __attribute__ ((used)) void
__load_sceMbusConvertToLocalDeviceId2(void) {
  sprx_dlsym(__handle, "sceMbusConvertToLocalDeviceId2", &__ptr_sceMbusConvertToLocalDeviceId2);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusConvertToMbusDeviceId\n"
    ".type sceMbusConvertToMbusDeviceId @function\n"
    "sceMbusConvertToMbusDeviceId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusConvertToMbusDeviceId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusConvertToMbusDeviceId\n"
    ".type __load_and_call_sceMbusConvertToMbusDeviceId @function\n"
    "__load_and_call_sceMbusConvertToMbusDeviceId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusConvertToMbusDeviceId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusConvertToMbusDeviceId]\n");

void __load_and_call_sceMbusConvertToMbusDeviceId();
static __attribute__ ((used)) void* __ptr_sceMbusConvertToMbusDeviceId = &__load_and_call_sceMbusConvertToMbusDeviceId;

static __attribute__ ((used)) void
__load_sceMbusConvertToMbusDeviceId(void) {
  sprx_dlsym(__handle, "sceMbusConvertToMbusDeviceId", &__ptr_sceMbusConvertToMbusDeviceId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDetachFromApplicationByPid\n"
    ".type sceMbusDetachFromApplicationByPid @function\n"
    "sceMbusDetachFromApplicationByPid:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDetachFromApplicationByPid]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDetachFromApplicationByPid\n"
    ".type __load_and_call_sceMbusDetachFromApplicationByPid @function\n"
    "__load_and_call_sceMbusDetachFromApplicationByPid:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDetachFromApplicationByPid\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDetachFromApplicationByPid]\n");

void __load_and_call_sceMbusDetachFromApplicationByPid();
static __attribute__ ((used)) void* __ptr_sceMbusDetachFromApplicationByPid = &__load_and_call_sceMbusDetachFromApplicationByPid;

static __attribute__ ((used)) void
__load_sceMbusDetachFromApplicationByPid(void) {
  sprx_dlsym(__handle, "sceMbusDetachFromApplicationByPid", &__ptr_sceMbusDetachFromApplicationByPid);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDisableBgmForShellUi\n"
    ".type sceMbusDisableBgmForShellUi @function\n"
    "sceMbusDisableBgmForShellUi:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDisableBgmForShellUi]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDisableBgmForShellUi\n"
    ".type __load_and_call_sceMbusDisableBgmForShellUi @function\n"
    "__load_and_call_sceMbusDisableBgmForShellUi:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDisableBgmForShellUi\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDisableBgmForShellUi]\n");

void __load_and_call_sceMbusDisableBgmForShellUi();
static __attribute__ ((used)) void* __ptr_sceMbusDisableBgmForShellUi = &__load_and_call_sceMbusDisableBgmForShellUi;

static __attribute__ ((used)) void
__load_sceMbusDisableBgmForShellUi(void) {
  sprx_dlsym(__handle, "sceMbusDisableBgmForShellUi", &__ptr_sceMbusDisableBgmForShellUi);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDisableChat\n"
    ".type sceMbusDisableChat @function\n"
    "sceMbusDisableChat:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDisableChat]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDisableChat\n"
    ".type __load_and_call_sceMbusDisableChat @function\n"
    "__load_and_call_sceMbusDisableChat:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDisableChat\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDisableChat]\n");

void __load_and_call_sceMbusDisableChat();
static __attribute__ ((used)) void* __ptr_sceMbusDisableChat = &__load_and_call_sceMbusDisableChat;

static __attribute__ ((used)) void
__load_sceMbusDisableChat(void) {
  sprx_dlsym(__handle, "sceMbusDisableChat", &__ptr_sceMbusDisableChat);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDisconnectDevice\n"
    ".type sceMbusDisconnectDevice @function\n"
    "sceMbusDisconnectDevice:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDisconnectDevice]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDisconnectDevice\n"
    ".type __load_and_call_sceMbusDisconnectDevice @function\n"
    "__load_and_call_sceMbusDisconnectDevice:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDisconnectDevice\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDisconnectDevice]\n");

void __load_and_call_sceMbusDisconnectDevice();
static __attribute__ ((used)) void* __ptr_sceMbusDisconnectDevice = &__load_and_call_sceMbusDisconnectDevice;

static __attribute__ ((used)) void
__load_sceMbusDisconnectDevice(void) {
  sprx_dlsym(__handle, "sceMbusDisconnectDevice", &__ptr_sceMbusDisconnectDevice);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpAppInfo\n"
    ".type sceMbusDumpAppInfo @function\n"
    "sceMbusDumpAppInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpAppInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpAppInfo\n"
    ".type __load_and_call_sceMbusDumpAppInfo @function\n"
    "__load_and_call_sceMbusDumpAppInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpAppInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpAppInfo]\n");

void __load_and_call_sceMbusDumpAppInfo();
static __attribute__ ((used)) void* __ptr_sceMbusDumpAppInfo = &__load_and_call_sceMbusDumpAppInfo;

static __attribute__ ((used)) void
__load_sceMbusDumpAppInfo(void) {
  sprx_dlsym(__handle, "sceMbusDumpAppInfo", &__ptr_sceMbusDumpAppInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpDeviceInfo\n"
    ".type sceMbusDumpDeviceInfo @function\n"
    "sceMbusDumpDeviceInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpDeviceInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpDeviceInfo\n"
    ".type __load_and_call_sceMbusDumpDeviceInfo @function\n"
    "__load_and_call_sceMbusDumpDeviceInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpDeviceInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpDeviceInfo]\n");

void __load_and_call_sceMbusDumpDeviceInfo();
static __attribute__ ((used)) void* __ptr_sceMbusDumpDeviceInfo = &__load_and_call_sceMbusDumpDeviceInfo;

static __attribute__ ((used)) void
__load_sceMbusDumpDeviceInfo(void) {
  sprx_dlsym(__handle, "sceMbusDumpDeviceInfo", &__ptr_sceMbusDumpDeviceInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpHandleStatusInfo\n"
    ".type sceMbusDumpHandleStatusInfo @function\n"
    "sceMbusDumpHandleStatusInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpHandleStatusInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpHandleStatusInfo\n"
    ".type __load_and_call_sceMbusDumpHandleStatusInfo @function\n"
    "__load_and_call_sceMbusDumpHandleStatusInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpHandleStatusInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpHandleStatusInfo]\n");

void __load_and_call_sceMbusDumpHandleStatusInfo();
static __attribute__ ((used)) void* __ptr_sceMbusDumpHandleStatusInfo = &__load_and_call_sceMbusDumpHandleStatusInfo;

static __attribute__ ((used)) void
__load_sceMbusDumpHandleStatusInfo(void) {
  sprx_dlsym(__handle, "sceMbusDumpHandleStatusInfo", &__ptr_sceMbusDumpHandleStatusInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpHandleStatusInfoAll\n"
    ".type sceMbusDumpHandleStatusInfoAll @function\n"
    "sceMbusDumpHandleStatusInfoAll:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpHandleStatusInfoAll]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpHandleStatusInfoAll\n"
    ".type __load_and_call_sceMbusDumpHandleStatusInfoAll @function\n"
    "__load_and_call_sceMbusDumpHandleStatusInfoAll:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpHandleStatusInfoAll\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpHandleStatusInfoAll]\n");

void __load_and_call_sceMbusDumpHandleStatusInfoAll();
static __attribute__ ((used)) void* __ptr_sceMbusDumpHandleStatusInfoAll = &__load_and_call_sceMbusDumpHandleStatusInfoAll;

static __attribute__ ((used)) void
__load_sceMbusDumpHandleStatusInfoAll(void) {
  sprx_dlsym(__handle, "sceMbusDumpHandleStatusInfoAll", &__ptr_sceMbusDumpHandleStatusInfoAll);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpModuleStateInfo\n"
    ".type sceMbusDumpModuleStateInfo @function\n"
    "sceMbusDumpModuleStateInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpModuleStateInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpModuleStateInfo\n"
    ".type __load_and_call_sceMbusDumpModuleStateInfo @function\n"
    "__load_and_call_sceMbusDumpModuleStateInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpModuleStateInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpModuleStateInfo]\n");

void __load_and_call_sceMbusDumpModuleStateInfo();
static __attribute__ ((used)) void* __ptr_sceMbusDumpModuleStateInfo = &__load_and_call_sceMbusDumpModuleStateInfo;

static __attribute__ ((used)) void
__load_sceMbusDumpModuleStateInfo(void) {
  sprx_dlsym(__handle, "sceMbusDumpModuleStateInfo", &__ptr_sceMbusDumpModuleStateInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpModuleStateInfoAll\n"
    ".type sceMbusDumpModuleStateInfoAll @function\n"
    "sceMbusDumpModuleStateInfoAll:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpModuleStateInfoAll]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpModuleStateInfoAll\n"
    ".type __load_and_call_sceMbusDumpModuleStateInfoAll @function\n"
    "__load_and_call_sceMbusDumpModuleStateInfoAll:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpModuleStateInfoAll\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpModuleStateInfoAll]\n");

void __load_and_call_sceMbusDumpModuleStateInfoAll();
static __attribute__ ((used)) void* __ptr_sceMbusDumpModuleStateInfoAll = &__load_and_call_sceMbusDumpModuleStateInfoAll;

static __attribute__ ((used)) void
__load_sceMbusDumpModuleStateInfoAll(void) {
  sprx_dlsym(__handle, "sceMbusDumpModuleStateInfoAll", &__ptr_sceMbusDumpModuleStateInfoAll);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpPlayerInfo\n"
    ".type sceMbusDumpPlayerInfo @function\n"
    "sceMbusDumpPlayerInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpPlayerInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpPlayerInfo\n"
    ".type __load_and_call_sceMbusDumpPlayerInfo @function\n"
    "__load_and_call_sceMbusDumpPlayerInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpPlayerInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpPlayerInfo]\n");

void __load_and_call_sceMbusDumpPlayerInfo();
static __attribute__ ((used)) void* __ptr_sceMbusDumpPlayerInfo = &__load_and_call_sceMbusDumpPlayerInfo;

static __attribute__ ((used)) void
__load_sceMbusDumpPlayerInfo(void) {
  sprx_dlsym(__handle, "sceMbusDumpPlayerInfo", &__ptr_sceMbusDumpPlayerInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpPortHandleInfo\n"
    ".type sceMbusDumpPortHandleInfo @function\n"
    "sceMbusDumpPortHandleInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpPortHandleInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpPortHandleInfo\n"
    ".type __load_and_call_sceMbusDumpPortHandleInfo @function\n"
    "__load_and_call_sceMbusDumpPortHandleInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpPortHandleInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpPortHandleInfo]\n");

void __load_and_call_sceMbusDumpPortHandleInfo();
static __attribute__ ((used)) void* __ptr_sceMbusDumpPortHandleInfo = &__load_and_call_sceMbusDumpPortHandleInfo;

static __attribute__ ((used)) void
__load_sceMbusDumpPortHandleInfo(void) {
  sprx_dlsym(__handle, "sceMbusDumpPortHandleInfo", &__ptr_sceMbusDumpPortHandleInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpProcMediaInfo\n"
    ".type sceMbusDumpProcMediaInfo @function\n"
    "sceMbusDumpProcMediaInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpProcMediaInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpProcMediaInfo\n"
    ".type __load_and_call_sceMbusDumpProcMediaInfo @function\n"
    "__load_and_call_sceMbusDumpProcMediaInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpProcMediaInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpProcMediaInfo]\n");

void __load_and_call_sceMbusDumpProcMediaInfo();
static __attribute__ ((used)) void* __ptr_sceMbusDumpProcMediaInfo = &__load_and_call_sceMbusDumpProcMediaInfo;

static __attribute__ ((used)) void
__load_sceMbusDumpProcMediaInfo(void) {
  sprx_dlsym(__handle, "sceMbusDumpProcMediaInfo", &__ptr_sceMbusDumpProcMediaInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpProcMediaInfoAll\n"
    ".type sceMbusDumpProcMediaInfoAll @function\n"
    "sceMbusDumpProcMediaInfoAll:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpProcMediaInfoAll]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpProcMediaInfoAll\n"
    ".type __load_and_call_sceMbusDumpProcMediaInfoAll @function\n"
    "__load_and_call_sceMbusDumpProcMediaInfoAll:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpProcMediaInfoAll\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpProcMediaInfoAll]\n");

void __load_and_call_sceMbusDumpProcMediaInfoAll();
static __attribute__ ((used)) void* __ptr_sceMbusDumpProcMediaInfoAll = &__load_and_call_sceMbusDumpProcMediaInfoAll;

static __attribute__ ((used)) void
__load_sceMbusDumpProcMediaInfoAll(void) {
  sprx_dlsym(__handle, "sceMbusDumpProcMediaInfoAll", &__ptr_sceMbusDumpProcMediaInfoAll);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusDumpUserMediaInfo\n"
    ".type sceMbusDumpUserMediaInfo @function\n"
    "sceMbusDumpUserMediaInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpUserMediaInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusDumpUserMediaInfo\n"
    ".type __load_and_call_sceMbusDumpUserMediaInfo @function\n"
    "__load_and_call_sceMbusDumpUserMediaInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusDumpUserMediaInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusDumpUserMediaInfo]\n");

void __load_and_call_sceMbusDumpUserMediaInfo();
static __attribute__ ((used)) void* __ptr_sceMbusDumpUserMediaInfo = &__load_and_call_sceMbusDumpUserMediaInfo;

static __attribute__ ((used)) void
__load_sceMbusDumpUserMediaInfo(void) {
  sprx_dlsym(__handle, "sceMbusDumpUserMediaInfo", &__ptr_sceMbusDumpUserMediaInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusEnableChat\n"
    ".type sceMbusEnableChat @function\n"
    "sceMbusEnableChat:\n"
    "jmp qword ptr [rip + __ptr_sceMbusEnableChat]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusEnableChat\n"
    ".type __load_and_call_sceMbusEnableChat @function\n"
    "__load_and_call_sceMbusEnableChat:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusEnableChat\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusEnableChat]\n");

void __load_and_call_sceMbusEnableChat();
static __attribute__ ((used)) void* __ptr_sceMbusEnableChat = &__load_and_call_sceMbusEnableChat;

static __attribute__ ((used)) void
__load_sceMbusEnableChat(void) {
  sprx_dlsym(__handle, "sceMbusEnableChat", &__ptr_sceMbusEnableChat);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusEnterAudioOutAutoAttenuation\n"
    ".type sceMbusEnterAudioOutAutoAttenuation @function\n"
    "sceMbusEnterAudioOutAutoAttenuation:\n"
    "jmp qword ptr [rip + __ptr_sceMbusEnterAudioOutAutoAttenuation]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusEnterAudioOutAutoAttenuation\n"
    ".type __load_and_call_sceMbusEnterAudioOutAutoAttenuation @function\n"
    "__load_and_call_sceMbusEnterAudioOutAutoAttenuation:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusEnterAudioOutAutoAttenuation\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusEnterAudioOutAutoAttenuation]\n");

void __load_and_call_sceMbusEnterAudioOutAutoAttenuation();
static __attribute__ ((used)) void* __ptr_sceMbusEnterAudioOutAutoAttenuation = &__load_and_call_sceMbusEnterAudioOutAutoAttenuation;

static __attribute__ ((used)) void
__load_sceMbusEnterAudioOutAutoAttenuation(void) {
  sprx_dlsym(__handle, "sceMbusEnterAudioOutAutoAttenuation", &__ptr_sceMbusEnterAudioOutAutoAttenuation);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusEventBusStatusChangeSubscribe\n"
    ".type sceMbusEventBusStatusChangeSubscribe @function\n"
    "sceMbusEventBusStatusChangeSubscribe:\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventBusStatusChangeSubscribe]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusEventBusStatusChangeSubscribe\n"
    ".type __load_and_call_sceMbusEventBusStatusChangeSubscribe @function\n"
    "__load_and_call_sceMbusEventBusStatusChangeSubscribe:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusEventBusStatusChangeSubscribe\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventBusStatusChangeSubscribe]\n");

void __load_and_call_sceMbusEventBusStatusChangeSubscribe();
static __attribute__ ((used)) void* __ptr_sceMbusEventBusStatusChangeSubscribe = &__load_and_call_sceMbusEventBusStatusChangeSubscribe;

static __attribute__ ((used)) void
__load_sceMbusEventBusStatusChangeSubscribe(void) {
  sprx_dlsym(__handle, "sceMbusEventBusStatusChangeSubscribe", &__ptr_sceMbusEventBusStatusChangeSubscribe);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusEventBusStatusChangeUnsubscribe\n"
    ".type sceMbusEventBusStatusChangeUnsubscribe @function\n"
    "sceMbusEventBusStatusChangeUnsubscribe:\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventBusStatusChangeUnsubscribe]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusEventBusStatusChangeUnsubscribe\n"
    ".type __load_and_call_sceMbusEventBusStatusChangeUnsubscribe @function\n"
    "__load_and_call_sceMbusEventBusStatusChangeUnsubscribe:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusEventBusStatusChangeUnsubscribe\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventBusStatusChangeUnsubscribe]\n");

void __load_and_call_sceMbusEventBusStatusChangeUnsubscribe();
static __attribute__ ((used)) void* __ptr_sceMbusEventBusStatusChangeUnsubscribe = &__load_and_call_sceMbusEventBusStatusChangeUnsubscribe;

static __attribute__ ((used)) void
__load_sceMbusEventBusStatusChangeUnsubscribe(void) {
  sprx_dlsym(__handle, "sceMbusEventBusStatusChangeUnsubscribe", &__ptr_sceMbusEventBusStatusChangeUnsubscribe);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusEventCallbackFuncsInit_\n"
    ".type sceMbusEventCallbackFuncsInit_ @function\n"
    "sceMbusEventCallbackFuncsInit_:\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventCallbackFuncsInit_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusEventCallbackFuncsInit_\n"
    ".type __load_and_call_sceMbusEventCallbackFuncsInit_ @function\n"
    "__load_and_call_sceMbusEventCallbackFuncsInit_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusEventCallbackFuncsInit_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventCallbackFuncsInit_]\n");

void __load_and_call_sceMbusEventCallbackFuncsInit_();
static __attribute__ ((used)) void* __ptr_sceMbusEventCallbackFuncsInit_ = &__load_and_call_sceMbusEventCallbackFuncsInit_;

static __attribute__ ((used)) void
__load_sceMbusEventCallbackFuncsInit_(void) {
  sprx_dlsym(__handle, "sceMbusEventCallbackFuncsInit_", &__ptr_sceMbusEventCallbackFuncsInit_);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusEventCreate_\n"
    ".type sceMbusEventCreate_ @function\n"
    "sceMbusEventCreate_:\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventCreate_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusEventCreate_\n"
    ".type __load_and_call_sceMbusEventCreate_ @function\n"
    "__load_and_call_sceMbusEventCreate_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusEventCreate_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventCreate_]\n");

void __load_and_call_sceMbusEventCreate_();
static __attribute__ ((used)) void* __ptr_sceMbusEventCreate_ = &__load_and_call_sceMbusEventCreate_;

static __attribute__ ((used)) void
__load_sceMbusEventCreate_(void) {
  sprx_dlsym(__handle, "sceMbusEventCreate_", &__ptr_sceMbusEventCreate_);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusEventDestroy\n"
    ".type sceMbusEventDestroy @function\n"
    "sceMbusEventDestroy:\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventDestroy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusEventDestroy\n"
    ".type __load_and_call_sceMbusEventDestroy @function\n"
    "__load_and_call_sceMbusEventDestroy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusEventDestroy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventDestroy]\n");

void __load_and_call_sceMbusEventDestroy();
static __attribute__ ((used)) void* __ptr_sceMbusEventDestroy = &__load_and_call_sceMbusEventDestroy;

static __attribute__ ((used)) void
__load_sceMbusEventDestroy(void) {
  sprx_dlsym(__handle, "sceMbusEventDestroy", &__ptr_sceMbusEventDestroy);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusEventReceive\n"
    ".type sceMbusEventReceive @function\n"
    "sceMbusEventReceive:\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventReceive]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusEventReceive\n"
    ".type __load_and_call_sceMbusEventReceive @function\n"
    "__load_and_call_sceMbusEventReceive:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusEventReceive\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusEventReceive]\n");

void __load_and_call_sceMbusEventReceive();
static __attribute__ ((used)) void* __ptr_sceMbusEventReceive = &__load_and_call_sceMbusEventReceive;

static __attribute__ ((used)) void
__load_sceMbusEventReceive(void) {
  sprx_dlsym(__handle, "sceMbusEventReceive", &__ptr_sceMbusEventReceive);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetControlStatus\n"
    ".type sceMbusGetControlStatus @function\n"
    "sceMbusGetControlStatus:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetControlStatus]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetControlStatus\n"
    ".type __load_and_call_sceMbusGetControlStatus @function\n"
    "__load_and_call_sceMbusGetControlStatus:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetControlStatus\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetControlStatus]\n");

void __load_and_call_sceMbusGetControlStatus();
static __attribute__ ((used)) void* __ptr_sceMbusGetControlStatus = &__load_and_call_sceMbusGetControlStatus;

static __attribute__ ((used)) void
__load_sceMbusGetControlStatus(void) {
  sprx_dlsym(__handle, "sceMbusGetControlStatus", &__ptr_sceMbusGetControlStatus);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetDeviceDescription\n"
    ".type sceMbusGetDeviceDescription @function\n"
    "sceMbusGetDeviceDescription:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceDescription]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetDeviceDescription\n"
    ".type __load_and_call_sceMbusGetDeviceDescription @function\n"
    "__load_and_call_sceMbusGetDeviceDescription:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetDeviceDescription\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceDescription]\n");

void __load_and_call_sceMbusGetDeviceDescription();
static __attribute__ ((used)) void* __ptr_sceMbusGetDeviceDescription = &__load_and_call_sceMbusGetDeviceDescription;

static __attribute__ ((used)) void
__load_sceMbusGetDeviceDescription(void) {
  sprx_dlsym(__handle, "sceMbusGetDeviceDescription", &__ptr_sceMbusGetDeviceDescription);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetDeviceInfoByBusId_\n"
    ".type sceMbusGetDeviceInfoByBusId_ @function\n"
    "sceMbusGetDeviceInfoByBusId_:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceInfoByBusId_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetDeviceInfoByBusId_\n"
    ".type __load_and_call_sceMbusGetDeviceInfoByBusId_ @function\n"
    "__load_and_call_sceMbusGetDeviceInfoByBusId_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetDeviceInfoByBusId_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceInfoByBusId_]\n");

void __load_and_call_sceMbusGetDeviceInfoByBusId_();
static __attribute__ ((used)) void* __ptr_sceMbusGetDeviceInfoByBusId_ = &__load_and_call_sceMbusGetDeviceInfoByBusId_;

static __attribute__ ((used)) void
__load_sceMbusGetDeviceInfoByBusId_(void) {
  sprx_dlsym(__handle, "sceMbusGetDeviceInfoByBusId_", &__ptr_sceMbusGetDeviceInfoByBusId_);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetDeviceInfoByConditionForDeviceService\n"
    ".type sceMbusGetDeviceInfoByConditionForDeviceService @function\n"
    "sceMbusGetDeviceInfoByConditionForDeviceService:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceInfoByConditionForDeviceService]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetDeviceInfoByConditionForDeviceService\n"
    ".type __load_and_call_sceMbusGetDeviceInfoByConditionForDeviceService @function\n"
    "__load_and_call_sceMbusGetDeviceInfoByConditionForDeviceService:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetDeviceInfoByConditionForDeviceService\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceInfoByConditionForDeviceService]\n");

void __load_and_call_sceMbusGetDeviceInfoByConditionForDeviceService();
static __attribute__ ((used)) void* __ptr_sceMbusGetDeviceInfoByConditionForDeviceService = &__load_and_call_sceMbusGetDeviceInfoByConditionForDeviceService;

static __attribute__ ((used)) void
__load_sceMbusGetDeviceInfoByConditionForDeviceService(void) {
  sprx_dlsym(__handle, "sceMbusGetDeviceInfoByConditionForDeviceService", &__ptr_sceMbusGetDeviceInfoByConditionForDeviceService);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetDeviceInfoByCondition_\n"
    ".type sceMbusGetDeviceInfoByCondition_ @function\n"
    "sceMbusGetDeviceInfoByCondition_:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceInfoByCondition_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetDeviceInfoByCondition_\n"
    ".type __load_and_call_sceMbusGetDeviceInfoByCondition_ @function\n"
    "__load_and_call_sceMbusGetDeviceInfoByCondition_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetDeviceInfoByCondition_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceInfoByCondition_]\n");

void __load_and_call_sceMbusGetDeviceInfoByCondition_();
static __attribute__ ((used)) void* __ptr_sceMbusGetDeviceInfoByCondition_ = &__load_and_call_sceMbusGetDeviceInfoByCondition_;

static __attribute__ ((used)) void
__load_sceMbusGetDeviceInfoByCondition_(void) {
  sprx_dlsym(__handle, "sceMbusGetDeviceInfoByCondition_", &__ptr_sceMbusGetDeviceInfoByCondition_);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetDeviceInfo_\n"
    ".type sceMbusGetDeviceInfo_ @function\n"
    "sceMbusGetDeviceInfo_:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceInfo_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetDeviceInfo_\n"
    ".type __load_and_call_sceMbusGetDeviceInfo_ @function\n"
    "__load_and_call_sceMbusGetDeviceInfo_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetDeviceInfo_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetDeviceInfo_]\n");

void __load_and_call_sceMbusGetDeviceInfo_();
static __attribute__ ((used)) void* __ptr_sceMbusGetDeviceInfo_ = &__load_and_call_sceMbusGetDeviceInfo_;

static __attribute__ ((used)) void
__load_sceMbusGetDeviceInfo_(void) {
  sprx_dlsym(__handle, "sceMbusGetDeviceInfo_", &__ptr_sceMbusGetDeviceInfo_);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetSimulatedBusUsableStatusByBusType\n"
    ".type sceMbusGetSimulatedBusUsableStatusByBusType @function\n"
    "sceMbusGetSimulatedBusUsableStatusByBusType:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetSimulatedBusUsableStatusByBusType]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetSimulatedBusUsableStatusByBusType\n"
    ".type __load_and_call_sceMbusGetSimulatedBusUsableStatusByBusType @function\n"
    "__load_and_call_sceMbusGetSimulatedBusUsableStatusByBusType:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetSimulatedBusUsableStatusByBusType\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetSimulatedBusUsableStatusByBusType]\n");

void __load_and_call_sceMbusGetSimulatedBusUsableStatusByBusType();
static __attribute__ ((used)) void* __ptr_sceMbusGetSimulatedBusUsableStatusByBusType = &__load_and_call_sceMbusGetSimulatedBusUsableStatusByBusType;

static __attribute__ ((used)) void
__load_sceMbusGetSimulatedBusUsableStatusByBusType(void) {
  sprx_dlsym(__handle, "sceMbusGetSimulatedBusUsableStatusByBusType", &__ptr_sceMbusGetSimulatedBusUsableStatusByBusType);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetSimulatedHandleStatusInfo\n"
    ".type sceMbusGetSimulatedHandleStatusInfo @function\n"
    "sceMbusGetSimulatedHandleStatusInfo:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetSimulatedHandleStatusInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetSimulatedHandleStatusInfo\n"
    ".type __load_and_call_sceMbusGetSimulatedHandleStatusInfo @function\n"
    "__load_and_call_sceMbusGetSimulatedHandleStatusInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetSimulatedHandleStatusInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetSimulatedHandleStatusInfo]\n");

void __load_and_call_sceMbusGetSimulatedHandleStatusInfo();
static __attribute__ ((used)) void* __ptr_sceMbusGetSimulatedHandleStatusInfo = &__load_and_call_sceMbusGetSimulatedHandleStatusInfo;

static __attribute__ ((used)) void
__load_sceMbusGetSimulatedHandleStatusInfo(void) {
  sprx_dlsym(__handle, "sceMbusGetSimulatedHandleStatusInfo", &__ptr_sceMbusGetSimulatedHandleStatusInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetSimulatedHandleStatusInfo2\n"
    ".type sceMbusGetSimulatedHandleStatusInfo2 @function\n"
    "sceMbusGetSimulatedHandleStatusInfo2:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetSimulatedHandleStatusInfo2]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetSimulatedHandleStatusInfo2\n"
    ".type __load_and_call_sceMbusGetSimulatedHandleStatusInfo2 @function\n"
    "__load_and_call_sceMbusGetSimulatedHandleStatusInfo2:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetSimulatedHandleStatusInfo2\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetSimulatedHandleStatusInfo2]\n");

void __load_and_call_sceMbusGetSimulatedHandleStatusInfo2();
static __attribute__ ((used)) void* __ptr_sceMbusGetSimulatedHandleStatusInfo2 = &__load_and_call_sceMbusGetSimulatedHandleStatusInfo2;

static __attribute__ ((used)) void
__load_sceMbusGetSimulatedHandleStatusInfo2(void) {
  sprx_dlsym(__handle, "sceMbusGetSimulatedHandleStatusInfo2", &__ptr_sceMbusGetSimulatedHandleStatusInfo2);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusGetSparkState\n"
    ".type sceMbusGetSparkState @function\n"
    "sceMbusGetSparkState:\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetSparkState]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusGetSparkState\n"
    ".type __load_and_call_sceMbusGetSparkState @function\n"
    "__load_and_call_sceMbusGetSparkState:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusGetSparkState\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusGetSparkState]\n");

void __load_and_call_sceMbusGetSparkState();
static __attribute__ ((used)) void* __ptr_sceMbusGetSparkState = &__load_and_call_sceMbusGetSparkState;

static __attribute__ ((used)) void
__load_sceMbusGetSparkState(void) {
  sprx_dlsym(__handle, "sceMbusGetSparkState", &__ptr_sceMbusGetSparkState);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusInit\n"
    ".type sceMbusInit @function\n"
    "sceMbusInit:\n"
    "jmp qword ptr [rip + __ptr_sceMbusInit]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusInit\n"
    ".type __load_and_call_sceMbusInit @function\n"
    "__load_and_call_sceMbusInit:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusInit\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusInit]\n");

void __load_and_call_sceMbusInit();
static __attribute__ ((used)) void* __ptr_sceMbusInit = &__load_and_call_sceMbusInit;

static __attribute__ ((used)) void
__load_sceMbusInit(void) {
  sprx_dlsym(__handle, "sceMbusInit", &__ptr_sceMbusInit);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusIsBgmProhibited\n"
    ".type sceMbusIsBgmProhibited @function\n"
    "sceMbusIsBgmProhibited:\n"
    "jmp qword ptr [rip + __ptr_sceMbusIsBgmProhibited]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusIsBgmProhibited\n"
    ".type __load_and_call_sceMbusIsBgmProhibited @function\n"
    "__load_and_call_sceMbusIsBgmProhibited:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusIsBgmProhibited\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusIsBgmProhibited]\n");

void __load_and_call_sceMbusIsBgmProhibited();
static __attribute__ ((used)) void* __ptr_sceMbusIsBgmProhibited = &__load_and_call_sceMbusIsBgmProhibited;

static __attribute__ ((used)) void
__load_sceMbusIsBgmProhibited(void) {
  sprx_dlsym(__handle, "sceMbusIsBgmProhibited", &__ptr_sceMbusIsBgmProhibited);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusIsUsingDevice\n"
    ".type sceMbusIsUsingDevice @function\n"
    "sceMbusIsUsingDevice:\n"
    "jmp qword ptr [rip + __ptr_sceMbusIsUsingDevice]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusIsUsingDevice\n"
    ".type __load_and_call_sceMbusIsUsingDevice @function\n"
    "__load_and_call_sceMbusIsUsingDevice:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusIsUsingDevice\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusIsUsingDevice]\n");

void __load_and_call_sceMbusIsUsingDevice();
static __attribute__ ((used)) void* __ptr_sceMbusIsUsingDevice = &__load_and_call_sceMbusIsUsingDevice;

static __attribute__ ((used)) void
__load_sceMbusIsUsingDevice(void) {
  sprx_dlsym(__handle, "sceMbusIsUsingDevice", &__ptr_sceMbusIsUsingDevice);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusLeaveAudioOutAutoAttenuation\n"
    ".type sceMbusLeaveAudioOutAutoAttenuation @function\n"
    "sceMbusLeaveAudioOutAutoAttenuation:\n"
    "jmp qword ptr [rip + __ptr_sceMbusLeaveAudioOutAutoAttenuation]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusLeaveAudioOutAutoAttenuation\n"
    ".type __load_and_call_sceMbusLeaveAudioOutAutoAttenuation @function\n"
    "__load_and_call_sceMbusLeaveAudioOutAutoAttenuation:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusLeaveAudioOutAutoAttenuation\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusLeaveAudioOutAutoAttenuation]\n");

void __load_and_call_sceMbusLeaveAudioOutAutoAttenuation();
static __attribute__ ((used)) void* __ptr_sceMbusLeaveAudioOutAutoAttenuation = &__load_and_call_sceMbusLeaveAudioOutAutoAttenuation;

static __attribute__ ((used)) void
__load_sceMbusLeaveAudioOutAutoAttenuation(void) {
  sprx_dlsym(__handle, "sceMbusLeaveAudioOutAutoAttenuation", &__ptr_sceMbusLeaveAudioOutAutoAttenuation);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusNotifyBtDisconnection\n"
    ".type sceMbusNotifyBtDisconnection @function\n"
    "sceMbusNotifyBtDisconnection:\n"
    "jmp qword ptr [rip + __ptr_sceMbusNotifyBtDisconnection]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusNotifyBtDisconnection\n"
    ".type __load_and_call_sceMbusNotifyBtDisconnection @function\n"
    "__load_and_call_sceMbusNotifyBtDisconnection:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusNotifyBtDisconnection\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusNotifyBtDisconnection]\n");

void __load_and_call_sceMbusNotifyBtDisconnection();
static __attribute__ ((used)) void* __ptr_sceMbusNotifyBtDisconnection = &__load_and_call_sceMbusNotifyBtDisconnection;

static __attribute__ ((used)) void
__load_sceMbusNotifyBtDisconnection(void) {
  sprx_dlsym(__handle, "sceMbusNotifyBtDisconnection", &__ptr_sceMbusNotifyBtDisconnection);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusNotifyDriverEvent\n"
    ".type sceMbusNotifyDriverEvent @function\n"
    "sceMbusNotifyDriverEvent:\n"
    "jmp qword ptr [rip + __ptr_sceMbusNotifyDriverEvent]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusNotifyDriverEvent\n"
    ".type __load_and_call_sceMbusNotifyDriverEvent @function\n"
    "__load_and_call_sceMbusNotifyDriverEvent:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusNotifyDriverEvent\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusNotifyDriverEvent]\n");

void __load_and_call_sceMbusNotifyDriverEvent();
static __attribute__ ((used)) void* __ptr_sceMbusNotifyDriverEvent = &__load_and_call_sceMbusNotifyDriverEvent;

static __attribute__ ((used)) void
__load_sceMbusNotifyDriverEvent(void) {
  sprx_dlsym(__handle, "sceMbusNotifyDriverEvent", &__ptr_sceMbusNotifyDriverEvent);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusReenableBgmForShellUi\n"
    ".type sceMbusReenableBgmForShellUi @function\n"
    "sceMbusReenableBgmForShellUi:\n"
    "jmp qword ptr [rip + __ptr_sceMbusReenableBgmForShellUi]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusReenableBgmForShellUi\n"
    ".type __load_and_call_sceMbusReenableBgmForShellUi @function\n"
    "__load_and_call_sceMbusReenableBgmForShellUi:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusReenableBgmForShellUi\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusReenableBgmForShellUi]\n");

void __load_and_call_sceMbusReenableBgmForShellUi();
static __attribute__ ((used)) void* __ptr_sceMbusReenableBgmForShellUi = &__load_and_call_sceMbusReenableBgmForShellUi;

static __attribute__ ((used)) void
__load_sceMbusReenableBgmForShellUi(void) {
  sprx_dlsym(__handle, "sceMbusReenableBgmForShellUi", &__ptr_sceMbusReenableBgmForShellUi);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusRegisterDriver\n"
    ".type sceMbusRegisterDriver @function\n"
    "sceMbusRegisterDriver:\n"
    "jmp qword ptr [rip + __ptr_sceMbusRegisterDriver]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusRegisterDriver\n"
    ".type __load_and_call_sceMbusRegisterDriver @function\n"
    "__load_and_call_sceMbusRegisterDriver:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusRegisterDriver\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusRegisterDriver]\n");

void __load_and_call_sceMbusRegisterDriver();
static __attribute__ ((used)) void* __ptr_sceMbusRegisterDriver = &__load_and_call_sceMbusRegisterDriver;

static __attribute__ ((used)) void
__load_sceMbusRegisterDriver(void) {
  sprx_dlsym(__handle, "sceMbusRegisterDriver", &__ptr_sceMbusRegisterDriver);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusReleaseControl\n"
    ".type sceMbusReleaseControl @function\n"
    "sceMbusReleaseControl:\n"
    "jmp qword ptr [rip + __ptr_sceMbusReleaseControl]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusReleaseControl\n"
    ".type __load_and_call_sceMbusReleaseControl @function\n"
    "__load_and_call_sceMbusReleaseControl:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusReleaseControl\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusReleaseControl]\n");

void __load_and_call_sceMbusReleaseControl();
static __attribute__ ((used)) void* __ptr_sceMbusReleaseControl = &__load_and_call_sceMbusReleaseControl;

static __attribute__ ((used)) void
__load_sceMbusReleaseControl(void) {
  sprx_dlsym(__handle, "sceMbusReleaseControl", &__ptr_sceMbusReleaseControl);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusRemoveCameraAppModuleFocus\n"
    ".type sceMbusRemoveCameraAppModuleFocus @function\n"
    "sceMbusRemoveCameraAppModuleFocus:\n"
    "jmp qword ptr [rip + __ptr_sceMbusRemoveCameraAppModuleFocus]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusRemoveCameraAppModuleFocus\n"
    ".type __load_and_call_sceMbusRemoveCameraAppModuleFocus @function\n"
    "__load_and_call_sceMbusRemoveCameraAppModuleFocus:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusRemoveCameraAppModuleFocus\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusRemoveCameraAppModuleFocus]\n");

void __load_and_call_sceMbusRemoveCameraAppModuleFocus();
static __attribute__ ((used)) void* __ptr_sceMbusRemoveCameraAppModuleFocus = &__load_and_call_sceMbusRemoveCameraAppModuleFocus;

static __attribute__ ((used)) void
__load_sceMbusRemoveCameraAppModuleFocus(void) {
  sprx_dlsym(__handle, "sceMbusRemoveCameraAppModuleFocus", &__ptr_sceMbusRemoveCameraAppModuleFocus);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusRemoveHandle\n"
    ".type sceMbusRemoveHandle @function\n"
    "sceMbusRemoveHandle:\n"
    "jmp qword ptr [rip + __ptr_sceMbusRemoveHandle]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusRemoveHandle\n"
    ".type __load_and_call_sceMbusRemoveHandle @function\n"
    "__load_and_call_sceMbusRemoveHandle:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusRemoveHandle\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusRemoveHandle]\n");

void __load_and_call_sceMbusRemoveHandle();
static __attribute__ ((used)) void* __ptr_sceMbusRemoveHandle = &__load_and_call_sceMbusRemoveHandle;

static __attribute__ ((used)) void
__load_sceMbusRemoveHandle(void) {
  sprx_dlsym(__handle, "sceMbusRemoveHandle", &__ptr_sceMbusRemoveHandle);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusRemoveProxy\n"
    ".type sceMbusRemoveProxy @function\n"
    "sceMbusRemoveProxy:\n"
    "jmp qword ptr [rip + __ptr_sceMbusRemoveProxy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusRemoveProxy\n"
    ".type __load_and_call_sceMbusRemoveProxy @function\n"
    "__load_and_call_sceMbusRemoveProxy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusRemoveProxy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusRemoveProxy]\n");

void __load_and_call_sceMbusRemoveProxy();
static __attribute__ ((used)) void* __ptr_sceMbusRemoveProxy = &__load_and_call_sceMbusRemoveProxy;

static __attribute__ ((used)) void
__load_sceMbusRemoveProxy(void) {
  sprx_dlsym(__handle, "sceMbusRemoveProxy", &__ptr_sceMbusRemoveProxy);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusResolveByDeviceId\n"
    ".type sceMbusResolveByDeviceId @function\n"
    "sceMbusResolveByDeviceId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusResolveByDeviceId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusResolveByDeviceId\n"
    ".type __load_and_call_sceMbusResolveByDeviceId @function\n"
    "__load_and_call_sceMbusResolveByDeviceId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusResolveByDeviceId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusResolveByDeviceId]\n");

void __load_and_call_sceMbusResolveByDeviceId();
static __attribute__ ((used)) void* __ptr_sceMbusResolveByDeviceId = &__load_and_call_sceMbusResolveByDeviceId;

static __attribute__ ((used)) void
__load_sceMbusResolveByDeviceId(void) {
  sprx_dlsym(__handle, "sceMbusResolveByDeviceId", &__ptr_sceMbusResolveByDeviceId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusResolveByHandle\n"
    ".type sceMbusResolveByHandle @function\n"
    "sceMbusResolveByHandle:\n"
    "jmp qword ptr [rip + __ptr_sceMbusResolveByHandle]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusResolveByHandle\n"
    ".type __load_and_call_sceMbusResolveByHandle @function\n"
    "__load_and_call_sceMbusResolveByHandle:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusResolveByHandle\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusResolveByHandle]\n");

void __load_and_call_sceMbusResolveByHandle();
static __attribute__ ((used)) void* __ptr_sceMbusResolveByHandle = &__load_and_call_sceMbusResolveByHandle;

static __attribute__ ((used)) void
__load_sceMbusResolveByHandle(void) {
  sprx_dlsym(__handle, "sceMbusResolveByHandle", &__ptr_sceMbusResolveByHandle);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusResolveByPlayerId\n"
    ".type sceMbusResolveByPlayerId @function\n"
    "sceMbusResolveByPlayerId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusResolveByPlayerId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusResolveByPlayerId\n"
    ".type __load_and_call_sceMbusResolveByPlayerId @function\n"
    "__load_and_call_sceMbusResolveByPlayerId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusResolveByPlayerId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusResolveByPlayerId]\n");

void __load_and_call_sceMbusResolveByPlayerId();
static __attribute__ ((used)) void* __ptr_sceMbusResolveByPlayerId = &__load_and_call_sceMbusResolveByPlayerId;

static __attribute__ ((used)) void
__load_sceMbusResolveByPlayerId(void) {
  sprx_dlsym(__handle, "sceMbusResolveByPlayerId", &__ptr_sceMbusResolveByPlayerId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusResolveByUserId\n"
    ".type sceMbusResolveByUserId @function\n"
    "sceMbusResolveByUserId:\n"
    "jmp qword ptr [rip + __ptr_sceMbusResolveByUserId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusResolveByUserId\n"
    ".type __load_and_call_sceMbusResolveByUserId @function\n"
    "__load_and_call_sceMbusResolveByUserId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusResolveByUserId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusResolveByUserId]\n");

void __load_and_call_sceMbusResolveByUserId();
static __attribute__ ((used)) void* __ptr_sceMbusResolveByUserId = &__load_and_call_sceMbusResolveByUserId;

static __attribute__ ((used)) void
__load_sceMbusResolveByUserId(void) {
  sprx_dlsym(__handle, "sceMbusResolveByUserId", &__ptr_sceMbusResolveByUserId);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetAutoLoginMode\n"
    ".type sceMbusSetAutoLoginMode @function\n"
    "sceMbusSetAutoLoginMode:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetAutoLoginMode]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetAutoLoginMode\n"
    ".type __load_and_call_sceMbusSetAutoLoginMode @function\n"
    "__load_and_call_sceMbusSetAutoLoginMode:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetAutoLoginMode\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetAutoLoginMode]\n");

void __load_and_call_sceMbusSetAutoLoginMode();
static __attribute__ ((used)) void* __ptr_sceMbusSetAutoLoginMode = &__load_and_call_sceMbusSetAutoLoginMode;

static __attribute__ ((used)) void
__load_sceMbusSetAutoLoginMode(void) {
  sprx_dlsym(__handle, "sceMbusSetAutoLoginMode", &__ptr_sceMbusSetAutoLoginMode);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetCameraAppModuleFocus\n"
    ".type sceMbusSetCameraAppModuleFocus @function\n"
    "sceMbusSetCameraAppModuleFocus:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetCameraAppModuleFocus]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetCameraAppModuleFocus\n"
    ".type __load_and_call_sceMbusSetCameraAppModuleFocus @function\n"
    "__load_and_call_sceMbusSetCameraAppModuleFocus:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetCameraAppModuleFocus\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetCameraAppModuleFocus]\n");

void __load_and_call_sceMbusSetCameraAppModuleFocus();
static __attribute__ ((used)) void* __ptr_sceMbusSetCameraAppModuleFocus = &__load_and_call_sceMbusSetCameraAppModuleFocus;

static __attribute__ ((used)) void
__load_sceMbusSetCameraAppModuleFocus(void) {
  sprx_dlsym(__handle, "sceMbusSetCameraAppModuleFocus", &__ptr_sceMbusSetCameraAppModuleFocus);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetDeviceFunctionState\n"
    ".type sceMbusSetDeviceFunctionState @function\n"
    "sceMbusSetDeviceFunctionState:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetDeviceFunctionState]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetDeviceFunctionState\n"
    ".type __load_and_call_sceMbusSetDeviceFunctionState @function\n"
    "__load_and_call_sceMbusSetDeviceFunctionState:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetDeviceFunctionState\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetDeviceFunctionState]\n");

void __load_and_call_sceMbusSetDeviceFunctionState();
static __attribute__ ((used)) void* __ptr_sceMbusSetDeviceFunctionState = &__load_and_call_sceMbusSetDeviceFunctionState;

static __attribute__ ((used)) void
__load_sceMbusSetDeviceFunctionState(void) {
  sprx_dlsym(__handle, "sceMbusSetDeviceFunctionState", &__ptr_sceMbusSetDeviceFunctionState);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetDuckingSetting\n"
    ".type sceMbusSetDuckingSetting @function\n"
    "sceMbusSetDuckingSetting:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetDuckingSetting]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetDuckingSetting\n"
    ".type __load_and_call_sceMbusSetDuckingSetting @function\n"
    "__load_and_call_sceMbusSetDuckingSetting:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetDuckingSetting\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetDuckingSetting]\n");

void __load_and_call_sceMbusSetDuckingSetting();
static __attribute__ ((used)) void* __ptr_sceMbusSetDuckingSetting = &__load_and_call_sceMbusSetDuckingSetting;

static __attribute__ ((used)) void
__load_sceMbusSetDuckingSetting(void) {
  sprx_dlsym(__handle, "sceMbusSetDuckingSetting", &__ptr_sceMbusSetDuckingSetting);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetProxy\n"
    ".type sceMbusSetProxy @function\n"
    "sceMbusSetProxy:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetProxy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetProxy\n"
    ".type __load_and_call_sceMbusSetProxy @function\n"
    "__load_and_call_sceMbusSetProxy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetProxy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetProxy]\n");

void __load_and_call_sceMbusSetProxy();
static __attribute__ ((used)) void* __ptr_sceMbusSetProxy = &__load_and_call_sceMbusSetProxy;

static __attribute__ ((used)) void
__load_sceMbusSetProxy(void) {
  sprx_dlsym(__handle, "sceMbusSetProxy", &__ptr_sceMbusSetProxy);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetRoutingMode\n"
    ".type sceMbusSetRoutingMode @function\n"
    "sceMbusSetRoutingMode:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetRoutingMode]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetRoutingMode\n"
    ".type __load_and_call_sceMbusSetRoutingMode @function\n"
    "__load_and_call_sceMbusSetRoutingMode:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetRoutingMode\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetRoutingMode]\n");

void __load_and_call_sceMbusSetRoutingMode();
static __attribute__ ((used)) void* __ptr_sceMbusSetRoutingMode = &__load_and_call_sceMbusSetRoutingMode;

static __attribute__ ((used)) void
__load_sceMbusSetRoutingMode(void) {
  sprx_dlsym(__handle, "sceMbusSetRoutingMode", &__ptr_sceMbusSetRoutingMode);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetScratchData\n"
    ".type sceMbusSetScratchData @function\n"
    "sceMbusSetScratchData:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetScratchData]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetScratchData\n"
    ".type __load_and_call_sceMbusSetScratchData @function\n"
    "__load_and_call_sceMbusSetScratchData:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetScratchData\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetScratchData]\n");

void __load_and_call_sceMbusSetScratchData();
static __attribute__ ((used)) void* __ptr_sceMbusSetScratchData = &__load_and_call_sceMbusSetScratchData;

static __attribute__ ((used)) void
__load_sceMbusSetScratchData(void) {
  sprx_dlsym(__handle, "sceMbusSetScratchData", &__ptr_sceMbusSetScratchData);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetScratchDataUpdatedEventMask\n"
    ".type sceMbusSetScratchDataUpdatedEventMask @function\n"
    "sceMbusSetScratchDataUpdatedEventMask:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetScratchDataUpdatedEventMask]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetScratchDataUpdatedEventMask\n"
    ".type __load_and_call_sceMbusSetScratchDataUpdatedEventMask @function\n"
    "__load_and_call_sceMbusSetScratchDataUpdatedEventMask:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetScratchDataUpdatedEventMask\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetScratchDataUpdatedEventMask]\n");

void __load_and_call_sceMbusSetScratchDataUpdatedEventMask();
static __attribute__ ((used)) void* __ptr_sceMbusSetScratchDataUpdatedEventMask = &__load_and_call_sceMbusSetScratchDataUpdatedEventMask;

static __attribute__ ((used)) void
__load_sceMbusSetScratchDataUpdatedEventMask(void) {
  sprx_dlsym(__handle, "sceMbusSetScratchDataUpdatedEventMask", &__ptr_sceMbusSetScratchDataUpdatedEventMask);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetSocialScreenAudioMode\n"
    ".type sceMbusSetSocialScreenAudioMode @function\n"
    "sceMbusSetSocialScreenAudioMode:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetSocialScreenAudioMode]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetSocialScreenAudioMode\n"
    ".type __load_and_call_sceMbusSetSocialScreenAudioMode @function\n"
    "__load_and_call_sceMbusSetSocialScreenAudioMode:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetSocialScreenAudioMode\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetSocialScreenAudioMode]\n");

void __load_and_call_sceMbusSetSocialScreenAudioMode();
static __attribute__ ((used)) void* __ptr_sceMbusSetSocialScreenAudioMode = &__load_and_call_sceMbusSetSocialScreenAudioMode;

static __attribute__ ((used)) void
__load_sceMbusSetSocialScreenAudioMode(void) {
  sprx_dlsym(__handle, "sceMbusSetSocialScreenAudioMode", &__ptr_sceMbusSetSocialScreenAudioMode);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetTestFlag\n"
    ".type sceMbusSetTestFlag @function\n"
    "sceMbusSetTestFlag:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetTestFlag]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetTestFlag\n"
    ".type __load_and_call_sceMbusSetTestFlag @function\n"
    "__load_and_call_sceMbusSetTestFlag:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetTestFlag\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetTestFlag]\n");

void __load_and_call_sceMbusSetTestFlag();
static __attribute__ ((used)) void* __ptr_sceMbusSetTestFlag = &__load_and_call_sceMbusSetTestFlag;

static __attribute__ ((used)) void
__load_sceMbusSetTestFlag(void) {
  sprx_dlsym(__handle, "sceMbusSetTestFlag", &__ptr_sceMbusSetTestFlag);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetThreadParam\n"
    ".type sceMbusSetThreadParam @function\n"
    "sceMbusSetThreadParam:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetThreadParam]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetThreadParam\n"
    ".type __load_and_call_sceMbusSetThreadParam @function\n"
    "__load_and_call_sceMbusSetThreadParam:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetThreadParam\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetThreadParam]\n");

void __load_and_call_sceMbusSetThreadParam();
static __attribute__ ((used)) void* __ptr_sceMbusSetThreadParam = &__load_and_call_sceMbusSetThreadParam;

static __attribute__ ((used)) void
__load_sceMbusSetThreadParam(void) {
  sprx_dlsym(__handle, "sceMbusSetThreadParam", &__ptr_sceMbusSetThreadParam);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetUsbPowerBlackList\n"
    ".type sceMbusSetUsbPowerBlackList @function\n"
    "sceMbusSetUsbPowerBlackList:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetUsbPowerBlackList]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetUsbPowerBlackList\n"
    ".type __load_and_call_sceMbusSetUsbPowerBlackList @function\n"
    "__load_and_call_sceMbusSetUsbPowerBlackList:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetUsbPowerBlackList\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetUsbPowerBlackList]\n");

void __load_and_call_sceMbusSetUsbPowerBlackList();
static __attribute__ ((used)) void* __ptr_sceMbusSetUsbPowerBlackList = &__load_and_call_sceMbusSetUsbPowerBlackList;

static __attribute__ ((used)) void
__load_sceMbusSetUsbPowerBlackList(void) {
  sprx_dlsym(__handle, "sceMbusSetUsbPowerBlackList", &__ptr_sceMbusSetUsbPowerBlackList);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetUserMuteStatus\n"
    ".type sceMbusSetUserMuteStatus @function\n"
    "sceMbusSetUserMuteStatus:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetUserMuteStatus]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetUserMuteStatus\n"
    ".type __load_and_call_sceMbusSetUserMuteStatus @function\n"
    "__load_and_call_sceMbusSetUserMuteStatus:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetUserMuteStatus\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetUserMuteStatus]\n");

void __load_and_call_sceMbusSetUserMuteStatus();
static __attribute__ ((used)) void* __ptr_sceMbusSetUserMuteStatus = &__load_and_call_sceMbusSetUserMuteStatus;

static __attribute__ ((used)) void
__load_sceMbusSetUserMuteStatus(void) {
  sprx_dlsym(__handle, "sceMbusSetUserMuteStatus", &__ptr_sceMbusSetUserMuteStatus);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusSetVolumeDown\n"
    ".type sceMbusSetVolumeDown @function\n"
    "sceMbusSetVolumeDown:\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetVolumeDown]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusSetVolumeDown\n"
    ".type __load_and_call_sceMbusSetVolumeDown @function\n"
    "__load_and_call_sceMbusSetVolumeDown:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusSetVolumeDown\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusSetVolumeDown]\n");

void __load_and_call_sceMbusSetVolumeDown();
static __attribute__ ((used)) void* __ptr_sceMbusSetVolumeDown = &__load_and_call_sceMbusSetVolumeDown;

static __attribute__ ((used)) void
__load_sceMbusSetVolumeDown(void) {
  sprx_dlsym(__handle, "sceMbusSetVolumeDown", &__ptr_sceMbusSetVolumeDown);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusStartAudioOutAuxBroadcast\n"
    ".type sceMbusStartAudioOutAuxBroadcast @function\n"
    "sceMbusStartAudioOutAuxBroadcast:\n"
    "jmp qword ptr [rip + __ptr_sceMbusStartAudioOutAuxBroadcast]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusStartAudioOutAuxBroadcast\n"
    ".type __load_and_call_sceMbusStartAudioOutAuxBroadcast @function\n"
    "__load_and_call_sceMbusStartAudioOutAuxBroadcast:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusStartAudioOutAuxBroadcast\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusStartAudioOutAuxBroadcast]\n");

void __load_and_call_sceMbusStartAudioOutAuxBroadcast();
static __attribute__ ((used)) void* __ptr_sceMbusStartAudioOutAuxBroadcast = &__load_and_call_sceMbusStartAudioOutAuxBroadcast;

static __attribute__ ((used)) void
__load_sceMbusStartAudioOutAuxBroadcast(void) {
  sprx_dlsym(__handle, "sceMbusStartAudioOutAuxBroadcast", &__ptr_sceMbusStartAudioOutAuxBroadcast);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusStartAudioOutSharePlay\n"
    ".type sceMbusStartAudioOutSharePlay @function\n"
    "sceMbusStartAudioOutSharePlay:\n"
    "jmp qword ptr [rip + __ptr_sceMbusStartAudioOutSharePlay]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusStartAudioOutSharePlay\n"
    ".type __load_and_call_sceMbusStartAudioOutSharePlay @function\n"
    "__load_and_call_sceMbusStartAudioOutSharePlay:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusStartAudioOutSharePlay\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusStartAudioOutSharePlay]\n");

void __load_and_call_sceMbusStartAudioOutSharePlay();
static __attribute__ ((used)) void* __ptr_sceMbusStartAudioOutSharePlay = &__load_and_call_sceMbusStartAudioOutSharePlay;

static __attribute__ ((used)) void
__load_sceMbusStartAudioOutSharePlay(void) {
  sprx_dlsym(__handle, "sceMbusStartAudioOutSharePlay", &__ptr_sceMbusStartAudioOutSharePlay);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusStopAudioOutAuxBroadcast\n"
    ".type sceMbusStopAudioOutAuxBroadcast @function\n"
    "sceMbusStopAudioOutAuxBroadcast:\n"
    "jmp qword ptr [rip + __ptr_sceMbusStopAudioOutAuxBroadcast]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusStopAudioOutAuxBroadcast\n"
    ".type __load_and_call_sceMbusStopAudioOutAuxBroadcast @function\n"
    "__load_and_call_sceMbusStopAudioOutAuxBroadcast:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusStopAudioOutAuxBroadcast\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusStopAudioOutAuxBroadcast]\n");

void __load_and_call_sceMbusStopAudioOutAuxBroadcast();
static __attribute__ ((used)) void* __ptr_sceMbusStopAudioOutAuxBroadcast = &__load_and_call_sceMbusStopAudioOutAuxBroadcast;

static __attribute__ ((used)) void
__load_sceMbusStopAudioOutAuxBroadcast(void) {
  sprx_dlsym(__handle, "sceMbusStopAudioOutAuxBroadcast", &__ptr_sceMbusStopAudioOutAuxBroadcast);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusStopAudioOutSharePlay\n"
    ".type sceMbusStopAudioOutSharePlay @function\n"
    "sceMbusStopAudioOutSharePlay:\n"
    "jmp qword ptr [rip + __ptr_sceMbusStopAudioOutSharePlay]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusStopAudioOutSharePlay\n"
    ".type __load_and_call_sceMbusStopAudioOutSharePlay @function\n"
    "__load_and_call_sceMbusStopAudioOutSharePlay:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusStopAudioOutSharePlay\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusStopAudioOutSharePlay]\n");

void __load_and_call_sceMbusStopAudioOutSharePlay();
static __attribute__ ((used)) void* __ptr_sceMbusStopAudioOutSharePlay = &__load_and_call_sceMbusStopAudioOutSharePlay;

static __attribute__ ((used)) void
__load_sceMbusStopAudioOutSharePlay(void) {
  sprx_dlsym(__handle, "sceMbusStopAudioOutSharePlay", &__ptr_sceMbusStopAudioOutSharePlay);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusTerm\n"
    ".type sceMbusTerm @function\n"
    "sceMbusTerm:\n"
    "jmp qword ptr [rip + __ptr_sceMbusTerm]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusTerm\n"
    ".type __load_and_call_sceMbusTerm @function\n"
    "__load_and_call_sceMbusTerm:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusTerm\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusTerm]\n");

void __load_and_call_sceMbusTerm();
static __attribute__ ((used)) void* __ptr_sceMbusTerm = &__load_and_call_sceMbusTerm;

static __attribute__ ((used)) void
__load_sceMbusTerm(void) {
  sprx_dlsym(__handle, "sceMbusTerm", &__ptr_sceMbusTerm);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusUnregisterDriver\n"
    ".type sceMbusUnregisterDriver @function\n"
    "sceMbusUnregisterDriver:\n"
    "jmp qword ptr [rip + __ptr_sceMbusUnregisterDriver]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusUnregisterDriver\n"
    ".type __load_and_call_sceMbusUnregisterDriver @function\n"
    "__load_and_call_sceMbusUnregisterDriver:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusUnregisterDriver\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusUnregisterDriver]\n");

void __load_and_call_sceMbusUnregisterDriver();
static __attribute__ ((used)) void* __ptr_sceMbusUnregisterDriver = &__load_and_call_sceMbusUnregisterDriver;

static __attribute__ ((used)) void
__load_sceMbusUnregisterDriver(void) {
  sprx_dlsym(__handle, "sceMbusUnregisterDriver", &__ptr_sceMbusUnregisterDriver);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusUserLogin\n"
    ".type sceMbusUserLogin @function\n"
    "sceMbusUserLogin:\n"
    "jmp qword ptr [rip + __ptr_sceMbusUserLogin]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusUserLogin\n"
    ".type __load_and_call_sceMbusUserLogin @function\n"
    "__load_and_call_sceMbusUserLogin:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusUserLogin\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusUserLogin]\n");

void __load_and_call_sceMbusUserLogin();
static __attribute__ ((used)) void* __ptr_sceMbusUserLogin = &__load_and_call_sceMbusUserLogin;

static __attribute__ ((used)) void
__load_sceMbusUserLogin(void) {
  sprx_dlsym(__handle, "sceMbusUserLogin", &__ptr_sceMbusUserLogin);
}

asm(".intel_syntax noprefix\n"
    ".global sceMbusUserLogout\n"
    ".type sceMbusUserLogout @function\n"
    "sceMbusUserLogout:\n"
    "jmp qword ptr [rip + __ptr_sceMbusUserLogout]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceMbusUserLogout\n"
    ".type __load_and_call_sceMbusUserLogout @function\n"
    "__load_and_call_sceMbusUserLogout:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceMbusUserLogout\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceMbusUserLogout]\n");

void __load_and_call_sceMbusUserLogout();
static __attribute__ ((used)) void* __ptr_sceMbusUserLogout = &__load_and_call_sceMbusUserLogout;

static __attribute__ ((used)) void
__load_sceMbusUserLogout(void) {
  sprx_dlsym(__handle, "sceMbusUserLogout", &__ptr_sceMbusUserLogout);
}
