/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libScePosixForWebKit", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global __wrap_access\n"
    ".type __wrap_access @function\n"
    "__wrap_access:\n"
    "jmp qword ptr [rip + __ptr___wrap_access]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_access\n"
    ".type __load_and_call___wrap_access @function\n"
    "__load_and_call___wrap_access:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_access\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_access]\n");

void __load_and_call___wrap_access();
static __attribute__ ((used)) void* __ptr___wrap_access = &__load_and_call___wrap_access;

static __attribute__ ((used)) void
__load___wrap_access(void) {
  sprx_dlsym(__handle, "__wrap_access", &__ptr___wrap_access);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_clock_gettime\n"
    ".type __wrap_clock_gettime @function\n"
    "__wrap_clock_gettime:\n"
    "jmp qword ptr [rip + __ptr___wrap_clock_gettime]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_clock_gettime\n"
    ".type __load_and_call___wrap_clock_gettime @function\n"
    "__load_and_call___wrap_clock_gettime:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_clock_gettime\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_clock_gettime]\n");

void __load_and_call___wrap_clock_gettime();
static __attribute__ ((used)) void* __ptr___wrap_clock_gettime = &__load_and_call___wrap_clock_gettime;

static __attribute__ ((used)) void
__load___wrap_clock_gettime(void) {
  sprx_dlsym(__handle, "__wrap_clock_gettime", &__ptr___wrap_clock_gettime);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_fchown\n"
    ".type __wrap_fchown @function\n"
    "__wrap_fchown:\n"
    "jmp qword ptr [rip + __ptr___wrap_fchown]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_fchown\n"
    ".type __load_and_call___wrap_fchown @function\n"
    "__load_and_call___wrap_fchown:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_fchown\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_fchown]\n");

void __load_and_call___wrap_fchown();
static __attribute__ ((used)) void* __ptr___wrap_fchown = &__load_and_call___wrap_fchown;

static __attribute__ ((used)) void
__load___wrap_fchown(void) {
  sprx_dlsym(__handle, "__wrap_fchown", &__ptr___wrap_fchown);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_getcwd\n"
    ".type __wrap_getcwd @function\n"
    "__wrap_getcwd:\n"
    "jmp qword ptr [rip + __ptr___wrap_getcwd]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_getcwd\n"
    ".type __load_and_call___wrap_getcwd @function\n"
    "__load_and_call___wrap_getcwd:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_getcwd\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_getcwd]\n");

void __load_and_call___wrap_getcwd();
static __attribute__ ((used)) void* __ptr___wrap_getcwd = &__load_and_call___wrap_getcwd;

static __attribute__ ((used)) void
__load___wrap_getcwd(void) {
  sprx_dlsym(__handle, "__wrap_getcwd", &__ptr___wrap_getcwd);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_getenv\n"
    ".type __wrap_getenv @function\n"
    "__wrap_getenv:\n"
    "jmp qword ptr [rip + __ptr___wrap_getenv]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_getenv\n"
    ".type __load_and_call___wrap_getenv @function\n"
    "__load_and_call___wrap_getenv:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_getenv\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_getenv]\n");

void __load_and_call___wrap_getenv();
static __attribute__ ((used)) void* __ptr___wrap_getenv = &__load_and_call___wrap_getenv;

static __attribute__ ((used)) void
__load___wrap_getenv(void) {
  sprx_dlsym(__handle, "__wrap_getenv", &__ptr___wrap_getenv);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_link\n"
    ".type __wrap_link @function\n"
    "__wrap_link:\n"
    "jmp qword ptr [rip + __ptr___wrap_link]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_link\n"
    ".type __load_and_call___wrap_link @function\n"
    "__load_and_call___wrap_link:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_link\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_link]\n");

void __load_and_call___wrap_link();
static __attribute__ ((used)) void* __ptr___wrap_link = &__load_and_call___wrap_link;

static __attribute__ ((used)) void
__load___wrap_link(void) {
  sprx_dlsym(__handle, "__wrap_link", &__ptr___wrap_link);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_lstat\n"
    ".type __wrap_lstat @function\n"
    "__wrap_lstat:\n"
    "jmp qword ptr [rip + __ptr___wrap_lstat]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_lstat\n"
    ".type __load_and_call___wrap_lstat @function\n"
    "__load_and_call___wrap_lstat:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_lstat\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_lstat]\n");

void __load_and_call___wrap_lstat();
static __attribute__ ((used)) void* __ptr___wrap_lstat = &__load_and_call___wrap_lstat;

static __attribute__ ((used)) void
__load___wrap_lstat(void) {
  sprx_dlsym(__handle, "__wrap_lstat", &__ptr___wrap_lstat);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_mmap\n"
    ".type __wrap_mmap @function\n"
    "__wrap_mmap:\n"
    "jmp qword ptr [rip + __ptr___wrap_mmap]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_mmap\n"
    ".type __load_and_call___wrap_mmap @function\n"
    "__load_and_call___wrap_mmap:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_mmap\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_mmap]\n");

void __load_and_call___wrap_mmap();
static __attribute__ ((used)) void* __ptr___wrap_mmap = &__load_and_call___wrap_mmap;

static __attribute__ ((used)) void
__load___wrap_mmap(void) {
  sprx_dlsym(__handle, "__wrap_mmap", &__ptr___wrap_mmap);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_readlink\n"
    ".type __wrap_readlink @function\n"
    "__wrap_readlink:\n"
    "jmp qword ptr [rip + __ptr___wrap_readlink]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_readlink\n"
    ".type __load_and_call___wrap_readlink @function\n"
    "__load_and_call___wrap_readlink:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_readlink\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_readlink]\n");

void __load_and_call___wrap_readlink();
static __attribute__ ((used)) void* __ptr___wrap_readlink = &__load_and_call___wrap_readlink;

static __attribute__ ((used)) void
__load___wrap_readlink(void) {
  sprx_dlsym(__handle, "__wrap_readlink", &__ptr___wrap_readlink);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_statvfs\n"
    ".type __wrap_statvfs @function\n"
    "__wrap_statvfs:\n"
    "jmp qword ptr [rip + __ptr___wrap_statvfs]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_statvfs\n"
    ".type __load_and_call___wrap_statvfs @function\n"
    "__load_and_call___wrap_statvfs:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_statvfs\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_statvfs]\n");

void __load_and_call___wrap_statvfs();
static __attribute__ ((used)) void* __ptr___wrap_statvfs = &__load_and_call___wrap_statvfs;

static __attribute__ ((used)) void
__load___wrap_statvfs(void) {
  sprx_dlsym(__handle, "__wrap_statvfs", &__ptr___wrap_statvfs);
}

asm(".intel_syntax noprefix\n"
    ".global __wrap_symlink\n"
    ".type __wrap_symlink @function\n"
    "__wrap_symlink:\n"
    "jmp qword ptr [rip + __ptr___wrap_symlink]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call___wrap_symlink\n"
    ".type __load_and_call___wrap_symlink @function\n"
    "__load_and_call___wrap_symlink:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load___wrap_symlink\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr___wrap_symlink]\n");

void __load_and_call___wrap_symlink();
static __attribute__ ((used)) void* __ptr___wrap_symlink = &__load_and_call___wrap_symlink;

static __attribute__ ((used)) void
__load___wrap_symlink(void) {
  sprx_dlsym(__handle, "__wrap_symlink", &__ptr___wrap_symlink);
}

asm(".intel_syntax noprefix\n"
    ".global arc4random\n"
    ".type arc4random @function\n"
    "arc4random:\n"
    "jmp qword ptr [rip + __ptr_arc4random]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_arc4random\n"
    ".type __load_and_call_arc4random @function\n"
    "__load_and_call_arc4random:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_arc4random\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_arc4random]\n");

void __load_and_call_arc4random();
static __attribute__ ((used)) void* __ptr_arc4random = &__load_and_call_arc4random;

static __attribute__ ((used)) void
__load_arc4random(void) {
  sprx_dlsym(__handle, "arc4random", &__ptr_arc4random);
}

asm(".intel_syntax noprefix\n"
    ".global arc4random_buf\n"
    ".type arc4random_buf @function\n"
    "arc4random_buf:\n"
    "jmp qword ptr [rip + __ptr_arc4random_buf]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_arc4random_buf\n"
    ".type __load_and_call_arc4random_buf @function\n"
    "__load_and_call_arc4random_buf:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_arc4random_buf\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_arc4random_buf]\n");

void __load_and_call_arc4random_buf();
static __attribute__ ((used)) void* __ptr_arc4random_buf = &__load_and_call_arc4random_buf;

static __attribute__ ((used)) void
__load_arc4random_buf(void) {
  sprx_dlsym(__handle, "arc4random_buf", &__ptr_arc4random_buf);
}

asm(".intel_syntax noprefix\n"
    ".global clock_gettime_np\n"
    ".type clock_gettime_np @function\n"
    "clock_gettime_np:\n"
    "jmp qword ptr [rip + __ptr_clock_gettime_np]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_clock_gettime_np\n"
    ".type __load_and_call_clock_gettime_np @function\n"
    "__load_and_call_clock_gettime_np:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_clock_gettime_np\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_clock_gettime_np]\n");

void __load_and_call_clock_gettime_np();
static __attribute__ ((used)) void* __ptr_clock_gettime_np = &__load_and_call_clock_gettime_np;

static __attribute__ ((used)) void
__load_clock_gettime_np(void) {
  sprx_dlsym(__handle, "clock_gettime_np", &__ptr_clock_gettime_np);
}

asm(".intel_syntax noprefix\n"
    ".global closedir\n"
    ".type closedir @function\n"
    "closedir:\n"
    "jmp qword ptr [rip + __ptr_closedir]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_closedir\n"
    ".type __load_and_call_closedir @function\n"
    "__load_and_call_closedir:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_closedir\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_closedir]\n");

void __load_and_call_closedir();
static __attribute__ ((used)) void* __ptr_closedir = &__load_and_call_closedir;

static __attribute__ ((used)) void
__load_closedir(void) {
  sprx_dlsym(__handle, "closedir", &__ptr_closedir);
}

asm(".intel_syntax noprefix\n"
    ".global fnmatch\n"
    ".type fnmatch @function\n"
    "fnmatch:\n"
    "jmp qword ptr [rip + __ptr_fnmatch]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_fnmatch\n"
    ".type __load_and_call_fnmatch @function\n"
    "__load_and_call_fnmatch:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_fnmatch\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_fnmatch]\n");

void __load_and_call_fnmatch();
static __attribute__ ((used)) void* __ptr_fnmatch = &__load_and_call_fnmatch;

static __attribute__ ((used)) void
__load_fnmatch(void) {
  sprx_dlsym(__handle, "fnmatch", &__ptr_fnmatch);
}

asm(".intel_syntax noprefix\n"
    ".global freeaddrinfo\n"
    ".type freeaddrinfo @function\n"
    "freeaddrinfo:\n"
    "jmp qword ptr [rip + __ptr_freeaddrinfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_freeaddrinfo\n"
    ".type __load_and_call_freeaddrinfo @function\n"
    "__load_and_call_freeaddrinfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_freeaddrinfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_freeaddrinfo]\n");

void __load_and_call_freeaddrinfo();
static __attribute__ ((used)) void* __ptr_freeaddrinfo = &__load_and_call_freeaddrinfo;

static __attribute__ ((used)) void
__load_freeaddrinfo(void) {
  sprx_dlsym(__handle, "freeaddrinfo", &__ptr_freeaddrinfo);
}

asm(".intel_syntax noprefix\n"
    ".global gai_strerror\n"
    ".type gai_strerror @function\n"
    "gai_strerror:\n"
    "jmp qword ptr [rip + __ptr_gai_strerror]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_gai_strerror\n"
    ".type __load_and_call_gai_strerror @function\n"
    "__load_and_call_gai_strerror:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_gai_strerror\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_gai_strerror]\n");

void __load_and_call_gai_strerror();
static __attribute__ ((used)) void* __ptr_gai_strerror = &__load_and_call_gai_strerror;

static __attribute__ ((used)) void
__load_gai_strerror(void) {
  sprx_dlsym(__handle, "gai_strerror", &__ptr_gai_strerror);
}

asm(".intel_syntax noprefix\n"
    ".global getaddrinfo\n"
    ".type getaddrinfo @function\n"
    "getaddrinfo:\n"
    "jmp qword ptr [rip + __ptr_getaddrinfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_getaddrinfo\n"
    ".type __load_and_call_getaddrinfo @function\n"
    "__load_and_call_getaddrinfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_getaddrinfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_getaddrinfo]\n");

void __load_and_call_getaddrinfo();
static __attribute__ ((used)) void* __ptr_getaddrinfo = &__load_and_call_getaddrinfo;

static __attribute__ ((used)) void
__load_getaddrinfo(void) {
  sprx_dlsym(__handle, "getaddrinfo", &__ptr_getaddrinfo);
}

asm(".intel_syntax noprefix\n"
    ".global getenv_np\n"
    ".type getenv_np @function\n"
    "getenv_np:\n"
    "jmp qword ptr [rip + __ptr_getenv_np]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_getenv_np\n"
    ".type __load_and_call_getenv_np @function\n"
    "__load_and_call_getenv_np:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_getenv_np\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_getenv_np]\n");

void __load_and_call_getenv_np();
static __attribute__ ((used)) void* __ptr_getenv_np = &__load_and_call_getenv_np;

static __attribute__ ((used)) void
__load_getenv_np(void) {
  sprx_dlsym(__handle, "getenv_np", &__ptr_getenv_np);
}

asm(".intel_syntax noprefix\n"
    ".global gethostbyname\n"
    ".type gethostbyname @function\n"
    "gethostbyname:\n"
    "jmp qword ptr [rip + __ptr_gethostbyname]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_gethostbyname\n"
    ".type __load_and_call_gethostbyname @function\n"
    "__load_and_call_gethostbyname:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_gethostbyname\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_gethostbyname]\n");

void __load_and_call_gethostbyname();
static __attribute__ ((used)) void* __ptr_gethostbyname = &__load_and_call_gethostbyname;

static __attribute__ ((used)) void
__load_gethostbyname(void) {
  sprx_dlsym(__handle, "gethostbyname", &__ptr_gethostbyname);
}

asm(".intel_syntax noprefix\n"
    ".global gethostbyname_r\n"
    ".type gethostbyname_r @function\n"
    "gethostbyname_r:\n"
    "jmp qword ptr [rip + __ptr_gethostbyname_r]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_gethostbyname_r\n"
    ".type __load_and_call_gethostbyname_r @function\n"
    "__load_and_call_gethostbyname_r:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_gethostbyname_r\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_gethostbyname_r]\n");

void __load_and_call_gethostbyname_r();
static __attribute__ ((used)) void* __ptr_gethostbyname_r = &__load_and_call_gethostbyname_r;

static __attribute__ ((used)) void
__load_gethostbyname_r(void) {
  sprx_dlsym(__handle, "gethostbyname_r", &__ptr_gethostbyname_r);
}

asm(".intel_syntax noprefix\n"
    ".global getnameinfo\n"
    ".type getnameinfo @function\n"
    "getnameinfo:\n"
    "jmp qword ptr [rip + __ptr_getnameinfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_getnameinfo\n"
    ".type __load_and_call_getnameinfo @function\n"
    "__load_and_call_getnameinfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_getnameinfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_getnameinfo]\n");

void __load_and_call_getnameinfo();
static __attribute__ ((used)) void* __ptr_getnameinfo = &__load_and_call_getnameinfo;

static __attribute__ ((used)) void
__load_getnameinfo(void) {
  sprx_dlsym(__handle, "getnameinfo", &__ptr_getnameinfo);
}

asm(".intel_syntax noprefix\n"
    ".global getservbyname\n"
    ".type getservbyname @function\n"
    "getservbyname:\n"
    "jmp qword ptr [rip + __ptr_getservbyname]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_getservbyname\n"
    ".type __load_and_call_getservbyname @function\n"
    "__load_and_call_getservbyname:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_getservbyname\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_getservbyname]\n");

void __load_and_call_getservbyname();
static __attribute__ ((used)) void* __ptr_getservbyname = &__load_and_call_getservbyname;

static __attribute__ ((used)) void
__load_getservbyname(void) {
  sprx_dlsym(__handle, "getservbyname", &__ptr_getservbyname);
}

asm(".intel_syntax noprefix\n"
    ".global isatty\n"
    ".type isatty @function\n"
    "isatty:\n"
    "jmp qword ptr [rip + __ptr_isatty]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_isatty\n"
    ".type __load_and_call_isatty @function\n"
    "__load_and_call_isatty:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_isatty\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_isatty]\n");

void __load_and_call_isatty();
static __attribute__ ((used)) void* __ptr_isatty = &__load_and_call_isatty;

static __attribute__ ((used)) void
__load_isatty(void) {
  sprx_dlsym(__handle, "isatty", &__ptr_isatty);
}

asm(".intel_syntax noprefix\n"
    ".global mkstemp\n"
    ".type mkstemp @function\n"
    "mkstemp:\n"
    "jmp qword ptr [rip + __ptr_mkstemp]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_mkstemp\n"
    ".type __load_and_call_mkstemp @function\n"
    "__load_and_call_mkstemp:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_mkstemp\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_mkstemp]\n");

void __load_and_call_mkstemp();
static __attribute__ ((used)) void* __ptr_mkstemp = &__load_and_call_mkstemp;

static __attribute__ ((used)) void
__load_mkstemp(void) {
  sprx_dlsym(__handle, "mkstemp", &__ptr_mkstemp);
}

asm(".intel_syntax noprefix\n"
    ".global mmap_np\n"
    ".type mmap_np @function\n"
    "mmap_np:\n"
    "jmp qword ptr [rip + __ptr_mmap_np]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_mmap_np\n"
    ".type __load_and_call_mmap_np @function\n"
    "__load_and_call_mmap_np:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_mmap_np\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_mmap_np]\n");

void __load_and_call_mmap_np();
static __attribute__ ((used)) void* __ptr_mmap_np = &__load_and_call_mmap_np;

static __attribute__ ((used)) void
__load_mmap_np(void) {
  sprx_dlsym(__handle, "mmap_np", &__ptr_mmap_np);
}

asm(".intel_syntax noprefix\n"
    ".global msetname\n"
    ".type msetname @function\n"
    "msetname:\n"
    "jmp qword ptr [rip + __ptr_msetname]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_msetname\n"
    ".type __load_and_call_msetname @function\n"
    "__load_and_call_msetname:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_msetname\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_msetname]\n");

void __load_and_call_msetname();
static __attribute__ ((used)) void* __ptr_msetname = &__load_and_call_msetname;

static __attribute__ ((used)) void
__load_msetname(void) {
  sprx_dlsym(__handle, "msetname", &__ptr_msetname);
}

asm(".intel_syntax noprefix\n"
    ".global opendir\n"
    ".type opendir @function\n"
    "opendir:\n"
    "jmp qword ptr [rip + __ptr_opendir]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_opendir\n"
    ".type __load_and_call_opendir @function\n"
    "__load_and_call_opendir:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_opendir\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_opendir]\n");

void __load_and_call_opendir();
static __attribute__ ((used)) void* __ptr_opendir = &__load_and_call_opendir;

static __attribute__ ((used)) void
__load_opendir(void) {
  sprx_dlsym(__handle, "opendir", &__ptr_opendir);
}

asm(".intel_syntax noprefix\n"
    ".global pthread_setname_np\n"
    ".type pthread_setname_np @function\n"
    "pthread_setname_np:\n"
    "jmp qword ptr [rip + __ptr_pthread_setname_np]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_pthread_setname_np\n"
    ".type __load_and_call_pthread_setname_np @function\n"
    "__load_and_call_pthread_setname_np:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_pthread_setname_np\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_pthread_setname_np]\n");

void __load_and_call_pthread_setname_np();
static __attribute__ ((used)) void* __ptr_pthread_setname_np = &__load_and_call_pthread_setname_np;

static __attribute__ ((used)) void
__load_pthread_setname_np(void) {
  sprx_dlsym(__handle, "pthread_setname_np", &__ptr_pthread_setname_np);
}

asm(".intel_syntax noprefix\n"
    ".global pthread_setschedparam_np\n"
    ".type pthread_setschedparam_np @function\n"
    "pthread_setschedparam_np:\n"
    "jmp qword ptr [rip + __ptr_pthread_setschedparam_np]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_pthread_setschedparam_np\n"
    ".type __load_and_call_pthread_setschedparam_np @function\n"
    "__load_and_call_pthread_setschedparam_np:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_pthread_setschedparam_np\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_pthread_setschedparam_np]\n");

void __load_and_call_pthread_setschedparam_np();
static __attribute__ ((used)) void* __ptr_pthread_setschedparam_np = &__load_and_call_pthread_setschedparam_np;

static __attribute__ ((used)) void
__load_pthread_setschedparam_np(void) {
  sprx_dlsym(__handle, "pthread_setschedparam_np", &__ptr_pthread_setschedparam_np);
}

asm(".intel_syntax noprefix\n"
    ".global readdir\n"
    ".type readdir @function\n"
    "readdir:\n"
    "jmp qword ptr [rip + __ptr_readdir]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_readdir\n"
    ".type __load_and_call_readdir @function\n"
    "__load_and_call_readdir:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_readdir\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_readdir]\n");

void __load_and_call_readdir();
static __attribute__ ((used)) void* __ptr_readdir = &__load_and_call_readdir;

static __attribute__ ((used)) void
__load_readdir(void) {
  sprx_dlsym(__handle, "readdir", &__ptr_readdir);
}

asm(".intel_syntax noprefix\n"
    ".global readdir_r\n"
    ".type readdir_r @function\n"
    "readdir_r:\n"
    "jmp qword ptr [rip + __ptr_readdir_r]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_readdir_r\n"
    ".type __load_and_call_readdir_r @function\n"
    "__load_and_call_readdir_r:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_readdir_r\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_readdir_r]\n");

void __load_and_call_readdir_r();
static __attribute__ ((used)) void* __ptr_readdir_r = &__load_and_call_readdir_r;

static __attribute__ ((used)) void
__load_readdir_r(void) {
  sprx_dlsym(__handle, "readdir_r", &__ptr_readdir_r);
}

asm(".intel_syntax noprefix\n"
    ".global setenv_np\n"
    ".type setenv_np @function\n"
    "setenv_np:\n"
    "jmp qword ptr [rip + __ptr_setenv_np]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_setenv_np\n"
    ".type __load_and_call_setenv_np @function\n"
    "__load_and_call_setenv_np:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_setenv_np\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_setenv_np]\n");

void __load_and_call_setenv_np();
static __attribute__ ((used)) void* __ptr_setenv_np = &__load_and_call_setenv_np;

static __attribute__ ((used)) void
__load_setenv_np(void) {
  sprx_dlsym(__handle, "setenv_np", &__ptr_setenv_np);
}

asm(".intel_syntax noprefix\n"
    ".global strcasestr\n"
    ".type strcasestr @function\n"
    "strcasestr:\n"
    "jmp qword ptr [rip + __ptr_strcasestr]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_strcasestr\n"
    ".type __load_and_call_strcasestr @function\n"
    "__load_and_call_strcasestr:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_strcasestr\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_strcasestr]\n");

void __load_and_call_strcasestr();
static __attribute__ ((used)) void* __ptr_strcasestr = &__load_and_call_strcasestr;

static __attribute__ ((used)) void
__load_strcasestr(void) {
  sprx_dlsym(__handle, "strcasestr", &__ptr_strcasestr);
}

asm(".intel_syntax noprefix\n"
    ".global sysinfo\n"
    ".type sysinfo @function\n"
    "sysinfo:\n"
    "jmp qword ptr [rip + __ptr_sysinfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sysinfo\n"
    ".type __load_and_call_sysinfo @function\n"
    "__load_and_call_sysinfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sysinfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sysinfo]\n");

void __load_and_call_sysinfo();
static __attribute__ ((used)) void* __ptr_sysinfo = &__load_and_call_sysinfo;

static __attribute__ ((used)) void
__load_sysinfo(void) {
  sprx_dlsym(__handle, "sysinfo", &__ptr_sysinfo);
}
