/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceScreenShot", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global _Z5dummyv\n"
    ".type _Z5dummyv @function\n"
    "_Z5dummyv:\n"
    "jmp qword ptr [rip + __ptr__Z5dummyv]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__Z5dummyv\n"
    ".type __load_and_call__Z5dummyv @function\n"
    "__load_and_call__Z5dummyv:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__Z5dummyv\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__Z5dummyv]\n");

void __load_and_call__Z5dummyv();
static __attribute__ ((used)) void* __ptr__Z5dummyv = &__load_and_call__Z5dummyv;

static __attribute__ ((used)) void
__load__Z5dummyv(void) {
  sprx_dlsym(__handle, "_Z5dummyv", &__ptr__Z5dummyv);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotCapture\n"
    ".type sceScreenShotCapture @function\n"
    "sceScreenShotCapture:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotCapture]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotCapture\n"
    ".type __load_and_call_sceScreenShotCapture @function\n"
    "__load_and_call_sceScreenShotCapture:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotCapture\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotCapture]\n");

void __load_and_call_sceScreenShotCapture();
static __attribute__ ((used)) void* __ptr_sceScreenShotCapture = &__load_and_call_sceScreenShotCapture;

static __attribute__ ((used)) void
__load_sceScreenShotCapture(void) {
  sprx_dlsym(__handle, "sceScreenShotCapture", &__ptr_sceScreenShotCapture);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotDisable\n"
    ".type sceScreenShotDisable @function\n"
    "sceScreenShotDisable:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotDisable]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotDisable\n"
    ".type __load_and_call_sceScreenShotDisable @function\n"
    "__load_and_call_sceScreenShotDisable:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotDisable\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotDisable]\n");

void __load_and_call_sceScreenShotDisable();
static __attribute__ ((used)) void* __ptr_sceScreenShotDisable = &__load_and_call_sceScreenShotDisable;

static __attribute__ ((used)) void
__load_sceScreenShotDisable(void) {
  sprx_dlsym(__handle, "sceScreenShotDisable", &__ptr_sceScreenShotDisable);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotDisableNotification\n"
    ".type sceScreenShotDisableNotification @function\n"
    "sceScreenShotDisableNotification:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotDisableNotification]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotDisableNotification\n"
    ".type __load_and_call_sceScreenShotDisableNotification @function\n"
    "__load_and_call_sceScreenShotDisableNotification:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotDisableNotification\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotDisableNotification]\n");

void __load_and_call_sceScreenShotDisableNotification();
static __attribute__ ((used)) void* __ptr_sceScreenShotDisableNotification = &__load_and_call_sceScreenShotDisableNotification;

static __attribute__ ((used)) void
__load_sceScreenShotDisableNotification(void) {
  sprx_dlsym(__handle, "sceScreenShotDisableNotification", &__ptr_sceScreenShotDisableNotification);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotEnable\n"
    ".type sceScreenShotEnable @function\n"
    "sceScreenShotEnable:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotEnable]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotEnable\n"
    ".type __load_and_call_sceScreenShotEnable @function\n"
    "__load_and_call_sceScreenShotEnable:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotEnable\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotEnable]\n");

void __load_and_call_sceScreenShotEnable();
static __attribute__ ((used)) void* __ptr_sceScreenShotEnable = &__load_and_call_sceScreenShotEnable;

static __attribute__ ((used)) void
__load_sceScreenShotEnable(void) {
  sprx_dlsym(__handle, "sceScreenShotEnable", &__ptr_sceScreenShotEnable);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotEnableNotification\n"
    ".type sceScreenShotEnableNotification @function\n"
    "sceScreenShotEnableNotification:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotEnableNotification]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotEnableNotification\n"
    ".type __load_and_call_sceScreenShotEnableNotification @function\n"
    "__load_and_call_sceScreenShotEnableNotification:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotEnableNotification\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotEnableNotification]\n");

void __load_and_call_sceScreenShotEnableNotification();
static __attribute__ ((used)) void* __ptr_sceScreenShotEnableNotification = &__load_and_call_sceScreenShotEnableNotification;

static __attribute__ ((used)) void
__load_sceScreenShotEnableNotification(void) {
  sprx_dlsym(__handle, "sceScreenShotEnableNotification", &__ptr_sceScreenShotEnableNotification);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotGetAppInfo\n"
    ".type sceScreenShotGetAppInfo @function\n"
    "sceScreenShotGetAppInfo:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotGetAppInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotGetAppInfo\n"
    ".type __load_and_call_sceScreenShotGetAppInfo @function\n"
    "__load_and_call_sceScreenShotGetAppInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotGetAppInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotGetAppInfo]\n");

void __load_and_call_sceScreenShotGetAppInfo();
static __attribute__ ((used)) void* __ptr_sceScreenShotGetAppInfo = &__load_and_call_sceScreenShotGetAppInfo;

static __attribute__ ((used)) void
__load_sceScreenShotGetAppInfo(void) {
  sprx_dlsym(__handle, "sceScreenShotGetAppInfo", &__ptr_sceScreenShotGetAppInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotGetDrcParam\n"
    ".type sceScreenShotGetDrcParam @function\n"
    "sceScreenShotGetDrcParam:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotGetDrcParam]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotGetDrcParam\n"
    ".type __load_and_call_sceScreenShotGetDrcParam @function\n"
    "__load_and_call_sceScreenShotGetDrcParam:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotGetDrcParam\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotGetDrcParam]\n");

void __load_and_call_sceScreenShotGetDrcParam();
static __attribute__ ((used)) void* __ptr_sceScreenShotGetDrcParam = &__load_and_call_sceScreenShotGetDrcParam;

static __attribute__ ((used)) void
__load_sceScreenShotGetDrcParam(void) {
  sprx_dlsym(__handle, "sceScreenShotGetDrcParam", &__ptr_sceScreenShotGetDrcParam);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotIsDisabled\n"
    ".type sceScreenShotIsDisabled @function\n"
    "sceScreenShotIsDisabled:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotIsDisabled]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotIsDisabled\n"
    ".type __load_and_call_sceScreenShotIsDisabled @function\n"
    "__load_and_call_sceScreenShotIsDisabled:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotIsDisabled\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotIsDisabled]\n");

void __load_and_call_sceScreenShotIsDisabled();
static __attribute__ ((used)) void* __ptr_sceScreenShotIsDisabled = &__load_and_call_sceScreenShotIsDisabled;

static __attribute__ ((used)) void
__load_sceScreenShotIsDisabled(void) {
  sprx_dlsym(__handle, "sceScreenShotIsDisabled", &__ptr_sceScreenShotIsDisabled);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotIsVshScreenCaptureDisabled\n"
    ".type sceScreenShotIsVshScreenCaptureDisabled @function\n"
    "sceScreenShotIsVshScreenCaptureDisabled:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotIsVshScreenCaptureDisabled]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotIsVshScreenCaptureDisabled\n"
    ".type __load_and_call_sceScreenShotIsVshScreenCaptureDisabled @function\n"
    "__load_and_call_sceScreenShotIsVshScreenCaptureDisabled:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotIsVshScreenCaptureDisabled\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotIsVshScreenCaptureDisabled]\n");

void __load_and_call_sceScreenShotIsVshScreenCaptureDisabled();
static __attribute__ ((used)) void* __ptr_sceScreenShotIsVshScreenCaptureDisabled = &__load_and_call_sceScreenShotIsVshScreenCaptureDisabled;

static __attribute__ ((used)) void
__load_sceScreenShotIsVshScreenCaptureDisabled(void) {
  sprx_dlsym(__handle, "sceScreenShotIsVshScreenCaptureDisabled", &__ptr_sceScreenShotIsVshScreenCaptureDisabled);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotSetOverlayImage\n"
    ".type sceScreenShotSetOverlayImage @function\n"
    "sceScreenShotSetOverlayImage:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotSetOverlayImage]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotSetOverlayImage\n"
    ".type __load_and_call_sceScreenShotSetOverlayImage @function\n"
    "__load_and_call_sceScreenShotSetOverlayImage:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotSetOverlayImage\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotSetOverlayImage]\n");

void __load_and_call_sceScreenShotSetOverlayImage();
static __attribute__ ((used)) void* __ptr_sceScreenShotSetOverlayImage = &__load_and_call_sceScreenShotSetOverlayImage;

static __attribute__ ((used)) void
__load_sceScreenShotSetOverlayImage(void) {
  sprx_dlsym(__handle, "sceScreenShotSetOverlayImage", &__ptr_sceScreenShotSetOverlayImage);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotSetOverlayImageWithOrigin\n"
    ".type sceScreenShotSetOverlayImageWithOrigin @function\n"
    "sceScreenShotSetOverlayImageWithOrigin:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotSetOverlayImageWithOrigin]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotSetOverlayImageWithOrigin\n"
    ".type __load_and_call_sceScreenShotSetOverlayImageWithOrigin @function\n"
    "__load_and_call_sceScreenShotSetOverlayImageWithOrigin:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotSetOverlayImageWithOrigin\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotSetOverlayImageWithOrigin]\n");

void __load_and_call_sceScreenShotSetOverlayImageWithOrigin();
static __attribute__ ((used)) void* __ptr_sceScreenShotSetOverlayImageWithOrigin = &__load_and_call_sceScreenShotSetOverlayImageWithOrigin;

static __attribute__ ((used)) void
__load_sceScreenShotSetOverlayImageWithOrigin(void) {
  sprx_dlsym(__handle, "sceScreenShotSetOverlayImageWithOrigin", &__ptr_sceScreenShotSetOverlayImageWithOrigin);
}

asm(".intel_syntax noprefix\n"
    ".global sceScreenShotSetParam\n"
    ".type sceScreenShotSetParam @function\n"
    "sceScreenShotSetParam:\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotSetParam]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceScreenShotSetParam\n"
    ".type __load_and_call_sceScreenShotSetParam @function\n"
    "__load_and_call_sceScreenShotSetParam:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceScreenShotSetParam\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceScreenShotSetParam]\n");

void __load_and_call_sceScreenShotSetParam();
static __attribute__ ((used)) void* __ptr_sceScreenShotSetParam = &__load_and_call_sceScreenShotSetParam;

static __attribute__ ((used)) void
__load_sceScreenShotSetParam(void) {
  sprx_dlsym(__handle, "sceScreenShotSetParam", &__ptr_sceScreenShotSetParam);
}
