/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceMetadataReaderWriter", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter10initializeEv\n"
    ".type _ZN23sceMetadataReaderWriter10initializeEv @function\n"
    "_ZN23sceMetadataReaderWriter10initializeEv:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter10initializeEv]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter10initializeEv\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter10initializeEv @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter10initializeEv:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter10initializeEv\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter10initializeEv]\n");

void __load_and_call__ZN23sceMetadataReaderWriter10initializeEv();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter10initializeEv = &__load_and_call__ZN23sceMetadataReaderWriter10initializeEv;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter10initializeEv(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter10initializeEv", &__ptr__ZN23sceMetadataReaderWriter10initializeEv);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE\n"
    ".type _ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE @function\n"
    "_ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE]\n");

void __load_and_call__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE = &__load_and_call__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE", &__ptr__ZN23sceMetadataReaderWriter11getMimeTypeERKSsRSt6vectorIjSaIjEE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi\n"
    ".type _ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi @function\n"
    "_ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi]\n");

void __load_and_call__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi = &__load_and_call__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi", &__ptr__ZN23sceMetadataReaderWriter12getMimeTypesERKSsiPi);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_\n"
    ".type _ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_ @function\n"
    "_ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_ = &__load_and_call__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_", &__ptr__ZN23sceMetadataReaderWriter12readMetadataERKSsRKNS_8MetadataEjRS2_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj\n"
    ".type _ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj @function\n"
    "_ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj]\n");

void __load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj = &__load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj", &__ptr__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEj);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_\n"
    ".type _ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_ @function\n"
    "_ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_ = &__load_and_call__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_", &__ptr__ZN23sceMetadataReaderWriter13writeMetadataERKSsRKNS_8MetadataEjPS2_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_\n"
    ".type _ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_ @function\n"
    "_ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_ = &__load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_", &__ptr__ZN23sceMetadataReaderWriter15ParserInterfaceC1ERKS0_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_\n"
    ".type _ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_ @function\n"
    "_ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_ = &__load_and_call__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_", &__ptr__ZN23sceMetadataReaderWriter15ParserInterfaceC2ERKS0_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE\n"
    ".type _ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE @function\n"
    "_ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE]\n");

void __load_and_call__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE = &__load_and_call__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE", &__ptr__ZN23sceMetadataReaderWriter16extractThumbnailERKSsjRNS_9ThumbnailE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi\n"
    ".type _ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi @function\n"
    "_ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi]\n");

void __load_and_call__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi = &__load_and_call__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi", &__ptr__ZN23sceMetadataReaderWriter16getNumOfMimeTypeERKSsPi);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE\n"
    ".type _ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE @function\n"
    "_ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE]\n");

void __load_and_call__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE = &__load_and_call__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE", &__ptr__ZN23sceMetadataReaderWriter17getParserInfoListERSt6vectorINS_10ParserInfoESaIS1_EE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE\n"
    ".type _ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE @function\n"
    "_ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE]\n");

void __load_and_call__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE = &__load_and_call__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE", &__ptr__ZN23sceMetadataReaderWriter18registerParserInfoERKSt6vectorINS_10ParserInfoESaIS1_EE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter20unregisterParserInfoEv\n"
    ".type _ZN23sceMetadataReaderWriter20unregisterParserInfoEv @function\n"
    "_ZN23sceMetadataReaderWriter20unregisterParserInfoEv:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter20unregisterParserInfoEv]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter20unregisterParserInfoEv\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter20unregisterParserInfoEv @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter20unregisterParserInfoEv:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter20unregisterParserInfoEv\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter20unregisterParserInfoEv]\n");

void __load_and_call__ZN23sceMetadataReaderWriter20unregisterParserInfoEv();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter20unregisterParserInfoEv = &__load_and_call__ZN23sceMetadataReaderWriter20unregisterParserInfoEv;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter20unregisterParserInfoEv(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter20unregisterParserInfoEv", &__ptr__ZN23sceMetadataReaderWriter20unregisterParserInfoEv);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE\n"
    ".type _ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE @function\n"
    "_ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE]\n");

void __load_and_call__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE = &__load_and_call__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE", &__ptr__ZN23sceMetadataReaderWriter23registerParserInterfaceEjRKNS_15ParserInterfaceE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter5ValueaSERS0_\n"
    ".type _ZN23sceMetadataReaderWriter5ValueaSERS0_ @function\n"
    "_ZN23sceMetadataReaderWriter5ValueaSERS0_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter5ValueaSERS0_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter5ValueaSERS0_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter5ValueaSERS0_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter5ValueaSERS0_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter5ValueaSERS0_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter5ValueaSERS0_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter5ValueaSERS0_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter5ValueaSERS0_ = &__load_and_call__ZN23sceMetadataReaderWriter5ValueaSERS0_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter5ValueaSERS0_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter5ValueaSERS0_", &__ptr__ZN23sceMetadataReaderWriter5ValueaSERS0_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_\n"
    ".type _ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_ @function\n"
    "_ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_ = &__load_and_call__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_", &__ptr__ZN23sceMetadataReaderWriter8Metadata11DeserializeERN3sce4Json5ValueERS0_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs\n"
    ".type _ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs @function\n"
    "_ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs = &__load_and_call__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs", &__ptr__ZN23sceMetadataReaderWriter8Metadata11deleteFieldERKSs);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE\n"
    ".type _ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE @function\n"
    "_ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE = &__load_and_call__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE", &__ptr__ZN23sceMetadataReaderWriter8Metadata15iterateAllFieldEPFiRKSsRKNS_5ValueEbE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb\n"
    ".type _ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb @function\n"
    "_ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb = &__load_and_call__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb", &__ptr__ZN23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueERb);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs\n"
    ".type _ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs @function\n"
    "_ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs = &__load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs", &__ptr__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSs);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE\n"
    ".type _ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE @function\n"
    "_ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE = &__load_and_call__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE", &__ptr__ZN23sceMetadataReaderWriter8Metadata8setFieldERKSsRKNS_5ValueE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE\n"
    ".type _ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE @function\n"
    "_ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE = &__load_and_call__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE", &__ptr__ZN23sceMetadataReaderWriter8Metadata9SerializeERS0_RN3sce4Json5ValueE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E", &__ptr__ZN23sceMetadataReaderWriter8MetadataC1EPFPvmEPFvS1_E);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataC1ERKS0_\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataC1ERKS0_ @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataC1ERKS0_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_ = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataC1ERKS0_", &__ptr__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E", &__ptr__ZN23sceMetadataReaderWriter8MetadataC1ERKS0_PFPvmEPFvS3_E);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataC1Ev\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataC1Ev @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataC1Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC1Ev]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1Ev\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1Ev @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataC1Ev:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataC1Ev\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC1Ev]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataC1Ev();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataC1Ev = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataC1Ev;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataC1Ev(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataC1Ev", &__ptr__ZN23sceMetadataReaderWriter8MetadataC1Ev);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E", &__ptr__ZN23sceMetadataReaderWriter8MetadataC2EPFPvmEPFvS1_E);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataC2ERKS0_\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataC2ERKS0_ @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataC2ERKS0_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_ = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataC2ERKS0_", &__ptr__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E", &__ptr__ZN23sceMetadataReaderWriter8MetadataC2ERKS0_PFPvmEPFvS3_E);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataC2Ev\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataC2Ev @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataC2Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC2Ev]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2Ev\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2Ev @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataC2Ev:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataC2Ev\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataC2Ev]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataC2Ev();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataC2Ev = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataC2Ev;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataC2Ev(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataC2Ev", &__ptr__ZN23sceMetadataReaderWriter8MetadataC2Ev);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataD0Ev\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataD0Ev @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataD0Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataD0Ev]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataD0Ev\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataD0Ev @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataD0Ev:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataD0Ev\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataD0Ev]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataD0Ev();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataD0Ev = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataD0Ev;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataD0Ev(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataD0Ev", &__ptr__ZN23sceMetadataReaderWriter8MetadataD0Ev);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataD1Ev\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataD1Ev @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataD1Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataD1Ev]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataD1Ev\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataD1Ev @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataD1Ev:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataD1Ev\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataD1Ev]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataD1Ev();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataD1Ev = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataD1Ev;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataD1Ev(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataD1Ev", &__ptr__ZN23sceMetadataReaderWriter8MetadataD1Ev);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataD2Ev\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataD2Ev @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataD2Ev:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataD2Ev]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataD2Ev\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataD2Ev @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataD2Ev:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataD2Ev\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataD2Ev]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataD2Ev();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataD2Ev = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataD2Ev;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataD2Ev(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataD2Ev", &__ptr__ZN23sceMetadataReaderWriter8MetadataD2Ev);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8MetadataaSERKS0_\n"
    ".type _ZN23sceMetadataReaderWriter8MetadataaSERKS0_ @function\n"
    "_ZN23sceMetadataReaderWriter8MetadataaSERKS0_:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataaSERKS0_]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8MetadataaSERKS0_\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8MetadataaSERKS0_ @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8MetadataaSERKS0_:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8MetadataaSERKS0_\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8MetadataaSERKS0_]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8MetadataaSERKS0_();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8MetadataaSERKS0_ = &__load_and_call__ZN23sceMetadataReaderWriter8MetadataaSERKS0_;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8MetadataaSERKS0_(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8MetadataaSERKS0_", &__ptr__ZN23sceMetadataReaderWriter8MetadataaSERKS0_);
}

asm(".intel_syntax noprefix\n"
    ".global _ZN23sceMetadataReaderWriter8finalizeEv\n"
    ".type _ZN23sceMetadataReaderWriter8finalizeEv @function\n"
    "_ZN23sceMetadataReaderWriter8finalizeEv:\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8finalizeEv]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZN23sceMetadataReaderWriter8finalizeEv\n"
    ".type __load_and_call__ZN23sceMetadataReaderWriter8finalizeEv @function\n"
    "__load_and_call__ZN23sceMetadataReaderWriter8finalizeEv:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZN23sceMetadataReaderWriter8finalizeEv\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZN23sceMetadataReaderWriter8finalizeEv]\n");

void __load_and_call__ZN23sceMetadataReaderWriter8finalizeEv();
static __attribute__ ((used)) void* __ptr__ZN23sceMetadataReaderWriter8finalizeEv = &__load_and_call__ZN23sceMetadataReaderWriter8finalizeEv;

static __attribute__ ((used)) void
__load__ZN23sceMetadataReaderWriter8finalizeEv(void) {
  sprx_dlsym(__handle, "_ZN23sceMetadataReaderWriter8finalizeEv", &__ptr__ZN23sceMetadataReaderWriter8finalizeEv);
}

asm(".intel_syntax noprefix\n"
    ".global _ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv\n"
    ".type _ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv @function\n"
    "_ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv:\n"
    "jmp qword ptr [rip + __ptr__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv\n"
    ".type __load_and_call__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv @function\n"
    "__load_and_call__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv]\n");

void __load_and_call__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv();
static __attribute__ ((used)) void* __ptr__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv = &__load_and_call__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv;

static __attribute__ ((used)) void
__load__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv(void) {
  sprx_dlsym(__handle, "_ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv", &__ptr__ZNK23sceMetadataReaderWriter8Metadata13getFieldCountEv);
}

asm(".intel_syntax noprefix\n"
    ".global _ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE\n"
    ".type _ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE @function\n"
    "_ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE:\n"
    "jmp qword ptr [rip + __ptr__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE\n"
    ".type __load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE @function\n"
    "__load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE]\n");

void __load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE();
static __attribute__ ((used)) void* __ptr__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE = &__load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE;

static __attribute__ ((used)) void
__load__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE(void) {
  sprx_dlsym(__handle, "_ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE", &__ptr__ZNK23sceMetadataReaderWriter8Metadata8getFieldEiRSsRNS_5ValueE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE\n"
    ".type _ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE @function\n"
    "_ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE:\n"
    "jmp qword ptr [rip + __ptr__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE\n"
    ".type __load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE @function\n"
    "__load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE]\n");

void __load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE();
static __attribute__ ((used)) void* __ptr__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE = &__load_and_call__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE;

static __attribute__ ((used)) void
__load__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE(void) {
  sprx_dlsym(__handle, "_ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE", &__ptr__ZNK23sceMetadataReaderWriter8Metadata8getValueERKSsRNS_5ValueE);
}

asm(".intel_syntax noprefix\n"
    ".global _ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv\n"
    ".type _ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv @function\n"
    "_ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv:\n"
    "jmp qword ptr [rip + __ptr__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv\n"
    ".type __load_and_call__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv @function\n"
    "__load_and_call__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv]\n");

void __load_and_call__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv();
static __attribute__ ((used)) void* __ptr__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv = &__load_and_call__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv;

static __attribute__ ((used)) void
__load__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv(void) {
  sprx_dlsym(__handle, "_ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv", &__ptr__ZNK23sceMetadataReaderWriter8Metadata9dumpValueEv);
}
