/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceBemp2sys", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global bemp2sys_logprintf_getlevel\n"
    ".type bemp2sys_logprintf_getlevel @function\n"
    "bemp2sys_logprintf_getlevel:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_logprintf_getlevel]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_logprintf_getlevel\n"
    ".type __load_and_call_bemp2sys_logprintf_getlevel @function\n"
    "__load_and_call_bemp2sys_logprintf_getlevel:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_logprintf_getlevel\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_logprintf_getlevel]\n");

void __load_and_call_bemp2sys_logprintf_getlevel();
static __attribute__ ((used)) void* __ptr_bemp2sys_logprintf_getlevel = &__load_and_call_bemp2sys_logprintf_getlevel;

static __attribute__ ((used)) void
__load_bemp2sys_logprintf_getlevel(void) {
  sprx_dlsym(__handle, "bemp2sys_logprintf_getlevel", &__ptr_bemp2sys_logprintf_getlevel);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_logprintf_setfunc\n"
    ".type bemp2sys_logprintf_setfunc @function\n"
    "bemp2sys_logprintf_setfunc:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_logprintf_setfunc]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_logprintf_setfunc\n"
    ".type __load_and_call_bemp2sys_logprintf_setfunc @function\n"
    "__load_and_call_bemp2sys_logprintf_setfunc:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_logprintf_setfunc\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_logprintf_setfunc]\n");

void __load_and_call_bemp2sys_logprintf_setfunc();
static __attribute__ ((used)) void* __ptr_bemp2sys_logprintf_setfunc = &__load_and_call_bemp2sys_logprintf_setfunc;

static __attribute__ ((used)) void
__load_bemp2sys_logprintf_setfunc(void) {
  sprx_dlsym(__handle, "bemp2sys_logprintf_setfunc", &__ptr_bemp2sys_logprintf_setfunc);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_logprintf_setlevel\n"
    ".type bemp2sys_logprintf_setlevel @function\n"
    "bemp2sys_logprintf_setlevel:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_logprintf_setlevel]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_logprintf_setlevel\n"
    ".type __load_and_call_bemp2sys_logprintf_setlevel @function\n"
    "__load_and_call_bemp2sys_logprintf_setlevel:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_logprintf_setlevel\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_logprintf_setlevel]\n");

void __load_and_call_bemp2sys_logprintf_setlevel();
static __attribute__ ((used)) void* __ptr_bemp2sys_logprintf_setlevel = &__load_and_call_bemp2sys_logprintf_setlevel;

static __attribute__ ((used)) void
__load_bemp2sys_logprintf_setlevel(void) {
  sprx_dlsym(__handle, "bemp2sys_logprintf_setlevel", &__ptr_bemp2sys_logprintf_setlevel);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_memmanager_set\n"
    ".type bemp2sys_memmanager_set @function\n"
    "bemp2sys_memmanager_set:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_memmanager_set]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_memmanager_set\n"
    ".type __load_and_call_bemp2sys_memmanager_set @function\n"
    "__load_and_call_bemp2sys_memmanager_set:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_memmanager_set\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_memmanager_set]\n");

void __load_and_call_bemp2sys_memmanager_set();
static __attribute__ ((used)) void* __ptr_bemp2sys_memmanager_set = &__load_and_call_bemp2sys_memmanager_set;

static __attribute__ ((used)) void
__load_bemp2sys_memmanager_set(void) {
  sprx_dlsym(__handle, "bemp2sys_memmanager_set", &__ptr_bemp2sys_memmanager_set);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_packetizer_create\n"
    ".type bemp2sys_packetizer_create @function\n"
    "bemp2sys_packetizer_create:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_packetizer_create]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_packetizer_create\n"
    ".type __load_and_call_bemp2sys_packetizer_create @function\n"
    "__load_and_call_bemp2sys_packetizer_create:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_packetizer_create\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_packetizer_create]\n");

void __load_and_call_bemp2sys_packetizer_create();
static __attribute__ ((used)) void* __ptr_bemp2sys_packetizer_create = &__load_and_call_bemp2sys_packetizer_create;

static __attribute__ ((used)) void
__load_bemp2sys_packetizer_create(void) {
  sprx_dlsym(__handle, "bemp2sys_packetizer_create", &__ptr_bemp2sys_packetizer_create);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_packetizer_destroy\n"
    ".type bemp2sys_packetizer_destroy @function\n"
    "bemp2sys_packetizer_destroy:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_packetizer_destroy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_packetizer_destroy\n"
    ".type __load_and_call_bemp2sys_packetizer_destroy @function\n"
    "__load_and_call_bemp2sys_packetizer_destroy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_packetizer_destroy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_packetizer_destroy]\n");

void __load_and_call_bemp2sys_packetizer_destroy();
static __attribute__ ((used)) void* __ptr_bemp2sys_packetizer_destroy = &__load_and_call_bemp2sys_packetizer_destroy;

static __attribute__ ((used)) void
__load_bemp2sys_packetizer_destroy(void) {
  sprx_dlsym(__handle, "bemp2sys_packetizer_destroy", &__ptr_bemp2sys_packetizer_destroy);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_packetizer_init\n"
    ".type bemp2sys_packetizer_init @function\n"
    "bemp2sys_packetizer_init:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_packetizer_init]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_packetizer_init\n"
    ".type __load_and_call_bemp2sys_packetizer_init @function\n"
    "__load_and_call_bemp2sys_packetizer_init:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_packetizer_init\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_packetizer_init]\n");

void __load_and_call_bemp2sys_packetizer_init();
static __attribute__ ((used)) void* __ptr_bemp2sys_packetizer_init = &__load_and_call_bemp2sys_packetizer_init;

static __attribute__ ((used)) void
__load_bemp2sys_packetizer_init(void) {
  sprx_dlsym(__handle, "bemp2sys_packetizer_init", &__ptr_bemp2sys_packetizer_init);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_packetizer_release\n"
    ".type bemp2sys_packetizer_release @function\n"
    "bemp2sys_packetizer_release:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_packetizer_release]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_packetizer_release\n"
    ".type __load_and_call_bemp2sys_packetizer_release @function\n"
    "__load_and_call_bemp2sys_packetizer_release:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_packetizer_release\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_packetizer_release]\n");

void __load_and_call_bemp2sys_packetizer_release();
static __attribute__ ((used)) void* __ptr_bemp2sys_packetizer_release = &__load_and_call_bemp2sys_packetizer_release;

static __attribute__ ((used)) void
__load_bemp2sys_packetizer_release(void) {
  sprx_dlsym(__handle, "bemp2sys_packetizer_release", &__ptr_bemp2sys_packetizer_release);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_pesparser_create\n"
    ".type bemp2sys_pesparser_create @function\n"
    "bemp2sys_pesparser_create:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_create]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_pesparser_create\n"
    ".type __load_and_call_bemp2sys_pesparser_create @function\n"
    "__load_and_call_bemp2sys_pesparser_create:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_pesparser_create\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_create]\n");

void __load_and_call_bemp2sys_pesparser_create();
static __attribute__ ((used)) void* __ptr_bemp2sys_pesparser_create = &__load_and_call_bemp2sys_pesparser_create;

static __attribute__ ((used)) void
__load_bemp2sys_pesparser_create(void) {
  sprx_dlsym(__handle, "bemp2sys_pesparser_create", &__ptr_bemp2sys_pesparser_create);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_pesparser_destroy\n"
    ".type bemp2sys_pesparser_destroy @function\n"
    "bemp2sys_pesparser_destroy:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_destroy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_pesparser_destroy\n"
    ".type __load_and_call_bemp2sys_pesparser_destroy @function\n"
    "__load_and_call_bemp2sys_pesparser_destroy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_pesparser_destroy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_destroy]\n");

void __load_and_call_bemp2sys_pesparser_destroy();
static __attribute__ ((used)) void* __ptr_bemp2sys_pesparser_destroy = &__load_and_call_bemp2sys_pesparser_destroy;

static __attribute__ ((used)) void
__load_bemp2sys_pesparser_destroy(void) {
  sprx_dlsym(__handle, "bemp2sys_pesparser_destroy", &__ptr_bemp2sys_pesparser_destroy);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_pesparser_init\n"
    ".type bemp2sys_pesparser_init @function\n"
    "bemp2sys_pesparser_init:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_init]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_pesparser_init\n"
    ".type __load_and_call_bemp2sys_pesparser_init @function\n"
    "__load_and_call_bemp2sys_pesparser_init:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_pesparser_init\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_init]\n");

void __load_and_call_bemp2sys_pesparser_init();
static __attribute__ ((used)) void* __ptr_bemp2sys_pesparser_init = &__load_and_call_bemp2sys_pesparser_init;

static __attribute__ ((used)) void
__load_bemp2sys_pesparser_init(void) {
  sprx_dlsym(__handle, "bemp2sys_pesparser_init", &__ptr_bemp2sys_pesparser_init);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_pesparser_parse\n"
    ".type bemp2sys_pesparser_parse @function\n"
    "bemp2sys_pesparser_parse:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_parse]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_pesparser_parse\n"
    ".type __load_and_call_bemp2sys_pesparser_parse @function\n"
    "__load_and_call_bemp2sys_pesparser_parse:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_pesparser_parse\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_parse]\n");

void __load_and_call_bemp2sys_pesparser_parse();
static __attribute__ ((used)) void* __ptr_bemp2sys_pesparser_parse = &__load_and_call_bemp2sys_pesparser_parse;

static __attribute__ ((used)) void
__load_bemp2sys_pesparser_parse(void) {
  sprx_dlsym(__handle, "bemp2sys_pesparser_parse", &__ptr_bemp2sys_pesparser_parse);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_pesparser_release\n"
    ".type bemp2sys_pesparser_release @function\n"
    "bemp2sys_pesparser_release:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_release]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_pesparser_release\n"
    ".type __load_and_call_bemp2sys_pesparser_release @function\n"
    "__load_and_call_bemp2sys_pesparser_release:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_pesparser_release\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_release]\n");

void __load_and_call_bemp2sys_pesparser_release();
static __attribute__ ((used)) void* __ptr_bemp2sys_pesparser_release = &__load_and_call_bemp2sys_pesparser_release;

static __attribute__ ((used)) void
__load_bemp2sys_pesparser_release(void) {
  sprx_dlsym(__handle, "bemp2sys_pesparser_release", &__ptr_bemp2sys_pesparser_release);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_pesparser_sendmessage\n"
    ".type bemp2sys_pesparser_sendmessage @function\n"
    "bemp2sys_pesparser_sendmessage:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_sendmessage]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_pesparser_sendmessage\n"
    ".type __load_and_call_bemp2sys_pesparser_sendmessage @function\n"
    "__load_and_call_bemp2sys_pesparser_sendmessage:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_pesparser_sendmessage\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_pesparser_sendmessage]\n");

void __load_and_call_bemp2sys_pesparser_sendmessage();
static __attribute__ ((used)) void* __ptr_bemp2sys_pesparser_sendmessage = &__load_and_call_bemp2sys_pesparser_sendmessage;

static __attribute__ ((used)) void
__load_bemp2sys_pesparser_sendmessage(void) {
  sprx_dlsym(__handle, "bemp2sys_pesparser_sendmessage", &__ptr_bemp2sys_pesparser_sendmessage);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_psdecoder_create\n"
    ".type bemp2sys_psdecoder_create @function\n"
    "bemp2sys_psdecoder_create:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_create]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_psdecoder_create\n"
    ".type __load_and_call_bemp2sys_psdecoder_create @function\n"
    "__load_and_call_bemp2sys_psdecoder_create:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_psdecoder_create\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_create]\n");

void __load_and_call_bemp2sys_psdecoder_create();
static __attribute__ ((used)) void* __ptr_bemp2sys_psdecoder_create = &__load_and_call_bemp2sys_psdecoder_create;

static __attribute__ ((used)) void
__load_bemp2sys_psdecoder_create(void) {
  sprx_dlsym(__handle, "bemp2sys_psdecoder_create", &__ptr_bemp2sys_psdecoder_create);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_psdecoder_destroy\n"
    ".type bemp2sys_psdecoder_destroy @function\n"
    "bemp2sys_psdecoder_destroy:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_destroy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_psdecoder_destroy\n"
    ".type __load_and_call_bemp2sys_psdecoder_destroy @function\n"
    "__load_and_call_bemp2sys_psdecoder_destroy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_psdecoder_destroy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_destroy]\n");

void __load_and_call_bemp2sys_psdecoder_destroy();
static __attribute__ ((used)) void* __ptr_bemp2sys_psdecoder_destroy = &__load_and_call_bemp2sys_psdecoder_destroy;

static __attribute__ ((used)) void
__load_bemp2sys_psdecoder_destroy(void) {
  sprx_dlsym(__handle, "bemp2sys_psdecoder_destroy", &__ptr_bemp2sys_psdecoder_destroy);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_psdecoder_init\n"
    ".type bemp2sys_psdecoder_init @function\n"
    "bemp2sys_psdecoder_init:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_init]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_psdecoder_init\n"
    ".type __load_and_call_bemp2sys_psdecoder_init @function\n"
    "__load_and_call_bemp2sys_psdecoder_init:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_psdecoder_init\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_init]\n");

void __load_and_call_bemp2sys_psdecoder_init();
static __attribute__ ((used)) void* __ptr_bemp2sys_psdecoder_init = &__load_and_call_bemp2sys_psdecoder_init;

static __attribute__ ((used)) void
__load_bemp2sys_psdecoder_init(void) {
  sprx_dlsym(__handle, "bemp2sys_psdecoder_init", &__ptr_bemp2sys_psdecoder_init);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_psdecoder_readpacket\n"
    ".type bemp2sys_psdecoder_readpacket @function\n"
    "bemp2sys_psdecoder_readpacket:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_readpacket]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_psdecoder_readpacket\n"
    ".type __load_and_call_bemp2sys_psdecoder_readpacket @function\n"
    "__load_and_call_bemp2sys_psdecoder_readpacket:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_psdecoder_readpacket\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_readpacket]\n");

void __load_and_call_bemp2sys_psdecoder_readpacket();
static __attribute__ ((used)) void* __ptr_bemp2sys_psdecoder_readpacket = &__load_and_call_bemp2sys_psdecoder_readpacket;

static __attribute__ ((used)) void
__load_bemp2sys_psdecoder_readpacket(void) {
  sprx_dlsym(__handle, "bemp2sys_psdecoder_readpacket", &__ptr_bemp2sys_psdecoder_readpacket);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_psdecoder_release\n"
    ".type bemp2sys_psdecoder_release @function\n"
    "bemp2sys_psdecoder_release:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_release]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_psdecoder_release\n"
    ".type __load_and_call_bemp2sys_psdecoder_release @function\n"
    "__load_and_call_bemp2sys_psdecoder_release:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_psdecoder_release\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_release]\n");

void __load_and_call_bemp2sys_psdecoder_release();
static __attribute__ ((used)) void* __ptr_bemp2sys_psdecoder_release = &__load_and_call_bemp2sys_psdecoder_release;

static __attribute__ ((used)) void
__load_bemp2sys_psdecoder_release(void) {
  sprx_dlsym(__handle, "bemp2sys_psdecoder_release", &__ptr_bemp2sys_psdecoder_release);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_psdecoder_sendmessage\n"
    ".type bemp2sys_psdecoder_sendmessage @function\n"
    "bemp2sys_psdecoder_sendmessage:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_sendmessage]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_psdecoder_sendmessage\n"
    ".type __load_and_call_bemp2sys_psdecoder_sendmessage @function\n"
    "__load_and_call_bemp2sys_psdecoder_sendmessage:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_psdecoder_sendmessage\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_psdecoder_sendmessage]\n");

void __load_and_call_bemp2sys_psdecoder_sendmessage();
static __attribute__ ((used)) void* __ptr_bemp2sys_psdecoder_sendmessage = &__load_and_call_bemp2sys_psdecoder_sendmessage;

static __attribute__ ((used)) void
__load_bemp2sys_psdecoder_sendmessage(void) {
  sprx_dlsym(__handle, "bemp2sys_psdecoder_sendmessage", &__ptr_bemp2sys_psdecoder_sendmessage);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsdecoder_create\n"
    ".type bemp2sys_tsdecoder_create @function\n"
    "bemp2sys_tsdecoder_create:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_create]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsdecoder_create\n"
    ".type __load_and_call_bemp2sys_tsdecoder_create @function\n"
    "__load_and_call_bemp2sys_tsdecoder_create:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsdecoder_create\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_create]\n");

void __load_and_call_bemp2sys_tsdecoder_create();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsdecoder_create = &__load_and_call_bemp2sys_tsdecoder_create;

static __attribute__ ((used)) void
__load_bemp2sys_tsdecoder_create(void) {
  sprx_dlsym(__handle, "bemp2sys_tsdecoder_create", &__ptr_bemp2sys_tsdecoder_create);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsdecoder_destroy\n"
    ".type bemp2sys_tsdecoder_destroy @function\n"
    "bemp2sys_tsdecoder_destroy:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_destroy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsdecoder_destroy\n"
    ".type __load_and_call_bemp2sys_tsdecoder_destroy @function\n"
    "__load_and_call_bemp2sys_tsdecoder_destroy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsdecoder_destroy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_destroy]\n");

void __load_and_call_bemp2sys_tsdecoder_destroy();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsdecoder_destroy = &__load_and_call_bemp2sys_tsdecoder_destroy;

static __attribute__ ((used)) void
__load_bemp2sys_tsdecoder_destroy(void) {
  sprx_dlsym(__handle, "bemp2sys_tsdecoder_destroy", &__ptr_bemp2sys_tsdecoder_destroy);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsdecoder_init\n"
    ".type bemp2sys_tsdecoder_init @function\n"
    "bemp2sys_tsdecoder_init:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_init]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsdecoder_init\n"
    ".type __load_and_call_bemp2sys_tsdecoder_init @function\n"
    "__load_and_call_bemp2sys_tsdecoder_init:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsdecoder_init\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_init]\n");

void __load_and_call_bemp2sys_tsdecoder_init();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsdecoder_init = &__load_and_call_bemp2sys_tsdecoder_init;

static __attribute__ ((used)) void
__load_bemp2sys_tsdecoder_init(void) {
  sprx_dlsym(__handle, "bemp2sys_tsdecoder_init", &__ptr_bemp2sys_tsdecoder_init);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsdecoder_readpacket\n"
    ".type bemp2sys_tsdecoder_readpacket @function\n"
    "bemp2sys_tsdecoder_readpacket:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_readpacket]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsdecoder_readpacket\n"
    ".type __load_and_call_bemp2sys_tsdecoder_readpacket @function\n"
    "__load_and_call_bemp2sys_tsdecoder_readpacket:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsdecoder_readpacket\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_readpacket]\n");

void __load_and_call_bemp2sys_tsdecoder_readpacket();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsdecoder_readpacket = &__load_and_call_bemp2sys_tsdecoder_readpacket;

static __attribute__ ((used)) void
__load_bemp2sys_tsdecoder_readpacket(void) {
  sprx_dlsym(__handle, "bemp2sys_tsdecoder_readpacket", &__ptr_bemp2sys_tsdecoder_readpacket);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsdecoder_release\n"
    ".type bemp2sys_tsdecoder_release @function\n"
    "bemp2sys_tsdecoder_release:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_release]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsdecoder_release\n"
    ".type __load_and_call_bemp2sys_tsdecoder_release @function\n"
    "__load_and_call_bemp2sys_tsdecoder_release:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsdecoder_release\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_release]\n");

void __load_and_call_bemp2sys_tsdecoder_release();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsdecoder_release = &__load_and_call_bemp2sys_tsdecoder_release;

static __attribute__ ((used)) void
__load_bemp2sys_tsdecoder_release(void) {
  sprx_dlsym(__handle, "bemp2sys_tsdecoder_release", &__ptr_bemp2sys_tsdecoder_release);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsdecoder_sendmessage\n"
    ".type bemp2sys_tsdecoder_sendmessage @function\n"
    "bemp2sys_tsdecoder_sendmessage:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_sendmessage]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsdecoder_sendmessage\n"
    ".type __load_and_call_bemp2sys_tsdecoder_sendmessage @function\n"
    "__load_and_call_bemp2sys_tsdecoder_sendmessage:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsdecoder_sendmessage\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsdecoder_sendmessage]\n");

void __load_and_call_bemp2sys_tsdecoder_sendmessage();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsdecoder_sendmessage = &__load_and_call_bemp2sys_tsdecoder_sendmessage;

static __attribute__ ((used)) void
__load_bemp2sys_tsdecoder_sendmessage(void) {
  sprx_dlsym(__handle, "bemp2sys_tsdecoder_sendmessage", &__ptr_bemp2sys_tsdecoder_sendmessage);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsfilter_create\n"
    ".type bemp2sys_tsfilter_create @function\n"
    "bemp2sys_tsfilter_create:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_create]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsfilter_create\n"
    ".type __load_and_call_bemp2sys_tsfilter_create @function\n"
    "__load_and_call_bemp2sys_tsfilter_create:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsfilter_create\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_create]\n");

void __load_and_call_bemp2sys_tsfilter_create();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsfilter_create = &__load_and_call_bemp2sys_tsfilter_create;

static __attribute__ ((used)) void
__load_bemp2sys_tsfilter_create(void) {
  sprx_dlsym(__handle, "bemp2sys_tsfilter_create", &__ptr_bemp2sys_tsfilter_create);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsfilter_destroy\n"
    ".type bemp2sys_tsfilter_destroy @function\n"
    "bemp2sys_tsfilter_destroy:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_destroy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsfilter_destroy\n"
    ".type __load_and_call_bemp2sys_tsfilter_destroy @function\n"
    "__load_and_call_bemp2sys_tsfilter_destroy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsfilter_destroy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_destroy]\n");

void __load_and_call_bemp2sys_tsfilter_destroy();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsfilter_destroy = &__load_and_call_bemp2sys_tsfilter_destroy;

static __attribute__ ((used)) void
__load_bemp2sys_tsfilter_destroy(void) {
  sprx_dlsym(__handle, "bemp2sys_tsfilter_destroy", &__ptr_bemp2sys_tsfilter_destroy);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsfilter_init\n"
    ".type bemp2sys_tsfilter_init @function\n"
    "bemp2sys_tsfilter_init:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_init]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsfilter_init\n"
    ".type __load_and_call_bemp2sys_tsfilter_init @function\n"
    "__load_and_call_bemp2sys_tsfilter_init:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsfilter_init\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_init]\n");

void __load_and_call_bemp2sys_tsfilter_init();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsfilter_init = &__load_and_call_bemp2sys_tsfilter_init;

static __attribute__ ((used)) void
__load_bemp2sys_tsfilter_init(void) {
  sprx_dlsym(__handle, "bemp2sys_tsfilter_init", &__ptr_bemp2sys_tsfilter_init);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsfilter_release\n"
    ".type bemp2sys_tsfilter_release @function\n"
    "bemp2sys_tsfilter_release:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_release]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsfilter_release\n"
    ".type __load_and_call_bemp2sys_tsfilter_release @function\n"
    "__load_and_call_bemp2sys_tsfilter_release:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsfilter_release\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_release]\n");

void __load_and_call_bemp2sys_tsfilter_release();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsfilter_release = &__load_and_call_bemp2sys_tsfilter_release;

static __attribute__ ((used)) void
__load_bemp2sys_tsfilter_release(void) {
  sprx_dlsym(__handle, "bemp2sys_tsfilter_release", &__ptr_bemp2sys_tsfilter_release);
}

asm(".intel_syntax noprefix\n"
    ".global bemp2sys_tsfilter_sendmessage\n"
    ".type bemp2sys_tsfilter_sendmessage @function\n"
    "bemp2sys_tsfilter_sendmessage:\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_sendmessage]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_bemp2sys_tsfilter_sendmessage\n"
    ".type __load_and_call_bemp2sys_tsfilter_sendmessage @function\n"
    "__load_and_call_bemp2sys_tsfilter_sendmessage:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_bemp2sys_tsfilter_sendmessage\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_bemp2sys_tsfilter_sendmessage]\n");

void __load_and_call_bemp2sys_tsfilter_sendmessage();
static __attribute__ ((used)) void* __ptr_bemp2sys_tsfilter_sendmessage = &__load_and_call_bemp2sys_tsfilter_sendmessage;

static __attribute__ ((used)) void
__load_bemp2sys_tsfilter_sendmessage(void) {
  sprx_dlsym(__handle, "bemp2sys_tsfilter_sendmessage", &__ptr_bemp2sys_tsfilter_sendmessage);
}
