/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceNpSns", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceNpSnsFacebookAbortRequest\n"
    ".type sceNpSnsFacebookAbortRequest @function\n"
    "sceNpSnsFacebookAbortRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsFacebookAbortRequest]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsFacebookAbortRequest\n"
    ".type __load_and_call_sceNpSnsFacebookAbortRequest @function\n"
    "__load_and_call_sceNpSnsFacebookAbortRequest:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsFacebookAbortRequest\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsFacebookAbortRequest]\n");

void __load_and_call_sceNpSnsFacebookAbortRequest();
static __attribute__ ((used)) void* __ptr_sceNpSnsFacebookAbortRequest = &__load_and_call_sceNpSnsFacebookAbortRequest;

static __attribute__ ((used)) void
__load_sceNpSnsFacebookAbortRequest(void) {
  sprx_dlsym(__handle, "sceNpSnsFacebookAbortRequest", &__ptr_sceNpSnsFacebookAbortRequest);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsFacebookCreateRequest\n"
    ".type sceNpSnsFacebookCreateRequest @function\n"
    "sceNpSnsFacebookCreateRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsFacebookCreateRequest]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsFacebookCreateRequest\n"
    ".type __load_and_call_sceNpSnsFacebookCreateRequest @function\n"
    "__load_and_call_sceNpSnsFacebookCreateRequest:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsFacebookCreateRequest\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsFacebookCreateRequest]\n");

void __load_and_call_sceNpSnsFacebookCreateRequest();
static __attribute__ ((used)) void* __ptr_sceNpSnsFacebookCreateRequest = &__load_and_call_sceNpSnsFacebookCreateRequest;

static __attribute__ ((used)) void
__load_sceNpSnsFacebookCreateRequest(void) {
  sprx_dlsym(__handle, "sceNpSnsFacebookCreateRequest", &__ptr_sceNpSnsFacebookCreateRequest);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsFacebookDeleteRequest\n"
    ".type sceNpSnsFacebookDeleteRequest @function\n"
    "sceNpSnsFacebookDeleteRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsFacebookDeleteRequest]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsFacebookDeleteRequest\n"
    ".type __load_and_call_sceNpSnsFacebookDeleteRequest @function\n"
    "__load_and_call_sceNpSnsFacebookDeleteRequest:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsFacebookDeleteRequest\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsFacebookDeleteRequest]\n");

void __load_and_call_sceNpSnsFacebookDeleteRequest();
static __attribute__ ((used)) void* __ptr_sceNpSnsFacebookDeleteRequest = &__load_and_call_sceNpSnsFacebookDeleteRequest;

static __attribute__ ((used)) void
__load_sceNpSnsFacebookDeleteRequest(void) {
  sprx_dlsym(__handle, "sceNpSnsFacebookDeleteRequest", &__ptr_sceNpSnsFacebookDeleteRequest);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsFacebookGetAccessToken\n"
    ".type sceNpSnsFacebookGetAccessToken @function\n"
    "sceNpSnsFacebookGetAccessToken:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsFacebookGetAccessToken]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsFacebookGetAccessToken\n"
    ".type __load_and_call_sceNpSnsFacebookGetAccessToken @function\n"
    "__load_and_call_sceNpSnsFacebookGetAccessToken:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsFacebookGetAccessToken\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsFacebookGetAccessToken]\n");

void __load_and_call_sceNpSnsFacebookGetAccessToken();
static __attribute__ ((used)) void* __ptr_sceNpSnsFacebookGetAccessToken = &__load_and_call_sceNpSnsFacebookGetAccessToken;

static __attribute__ ((used)) void
__load_sceNpSnsFacebookGetAccessToken(void) {
  sprx_dlsym(__handle, "sceNpSnsFacebookGetAccessToken", &__ptr_sceNpSnsFacebookGetAccessToken);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntAbortRequest\n"
    ".type sceNpSnsIntAbortRequest @function\n"
    "sceNpSnsIntAbortRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntAbortRequest]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntAbortRequest\n"
    ".type __load_and_call_sceNpSnsIntAbortRequest @function\n"
    "__load_and_call_sceNpSnsIntAbortRequest:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntAbortRequest\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntAbortRequest]\n");

void __load_and_call_sceNpSnsIntAbortRequest();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntAbortRequest = &__load_and_call_sceNpSnsIntAbortRequest;

static __attribute__ ((used)) void
__load_sceNpSnsIntAbortRequest(void) {
  sprx_dlsym(__handle, "sceNpSnsIntAbortRequest", &__ptr_sceNpSnsIntAbortRequest);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntCreateRequest\n"
    ".type sceNpSnsIntCreateRequest @function\n"
    "sceNpSnsIntCreateRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntCreateRequest]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntCreateRequest\n"
    ".type __load_and_call_sceNpSnsIntCreateRequest @function\n"
    "__load_and_call_sceNpSnsIntCreateRequest:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntCreateRequest\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntCreateRequest]\n");

void __load_and_call_sceNpSnsIntCreateRequest();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntCreateRequest = &__load_and_call_sceNpSnsIntCreateRequest;

static __attribute__ ((used)) void
__load_sceNpSnsIntCreateRequest(void) {
  sprx_dlsym(__handle, "sceNpSnsIntCreateRequest", &__ptr_sceNpSnsIntCreateRequest);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntDeleteRequest\n"
    ".type sceNpSnsIntDeleteRequest @function\n"
    "sceNpSnsIntDeleteRequest:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntDeleteRequest]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntDeleteRequest\n"
    ".type __load_and_call_sceNpSnsIntDeleteRequest @function\n"
    "__load_and_call_sceNpSnsIntDeleteRequest:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntDeleteRequest\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntDeleteRequest]\n");

void __load_and_call_sceNpSnsIntDeleteRequest();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntDeleteRequest = &__load_and_call_sceNpSnsIntDeleteRequest;

static __attribute__ ((used)) void
__load_sceNpSnsIntDeleteRequest(void) {
  sprx_dlsym(__handle, "sceNpSnsIntDeleteRequest", &__ptr_sceNpSnsIntDeleteRequest);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntFbGetGameAccessToken\n"
    ".type sceNpSnsIntFbGetGameAccessToken @function\n"
    "sceNpSnsIntFbGetGameAccessToken:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntFbGetGameAccessToken]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntFbGetGameAccessToken\n"
    ".type __load_and_call_sceNpSnsIntFbGetGameAccessToken @function\n"
    "__load_and_call_sceNpSnsIntFbGetGameAccessToken:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntFbGetGameAccessToken\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntFbGetGameAccessToken]\n");

void __load_and_call_sceNpSnsIntFbGetGameAccessToken();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntFbGetGameAccessToken = &__load_and_call_sceNpSnsIntFbGetGameAccessToken;

static __attribute__ ((used)) void
__load_sceNpSnsIntFbGetGameAccessToken(void) {
  sprx_dlsym(__handle, "sceNpSnsIntFbGetGameAccessToken", &__ptr_sceNpSnsIntFbGetGameAccessToken);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntFbGetGameAccessTokenAllowed\n"
    ".type sceNpSnsIntFbGetGameAccessTokenAllowed @function\n"
    "sceNpSnsIntFbGetGameAccessTokenAllowed:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntFbGetGameAccessTokenAllowed]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntFbGetGameAccessTokenAllowed\n"
    ".type __load_and_call_sceNpSnsIntFbGetGameAccessTokenAllowed @function\n"
    "__load_and_call_sceNpSnsIntFbGetGameAccessTokenAllowed:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntFbGetGameAccessTokenAllowed\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntFbGetGameAccessTokenAllowed]\n");

void __load_and_call_sceNpSnsIntFbGetGameAccessTokenAllowed();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntFbGetGameAccessTokenAllowed = &__load_and_call_sceNpSnsIntFbGetGameAccessTokenAllowed;

static __attribute__ ((used)) void
__load_sceNpSnsIntFbGetGameAccessTokenAllowed(void) {
  sprx_dlsym(__handle, "sceNpSnsIntFbGetGameAccessTokenAllowed", &__ptr_sceNpSnsIntFbGetGameAccessTokenAllowed);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntFbGetSystemAccessToken\n"
    ".type sceNpSnsIntFbGetSystemAccessToken @function\n"
    "sceNpSnsIntFbGetSystemAccessToken:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntFbGetSystemAccessToken]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntFbGetSystemAccessToken\n"
    ".type __load_and_call_sceNpSnsIntFbGetSystemAccessToken @function\n"
    "__load_and_call_sceNpSnsIntFbGetSystemAccessToken:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntFbGetSystemAccessToken\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntFbGetSystemAccessToken]\n");

void __load_and_call_sceNpSnsIntFbGetSystemAccessToken();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntFbGetSystemAccessToken = &__load_and_call_sceNpSnsIntFbGetSystemAccessToken;

static __attribute__ ((used)) void
__load_sceNpSnsIntFbGetSystemAccessToken(void) {
  sprx_dlsym(__handle, "sceNpSnsIntFbGetSystemAccessToken", &__ptr_sceNpSnsIntFbGetSystemAccessToken);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntFbGetTitleInfo\n"
    ".type sceNpSnsIntFbGetTitleInfo @function\n"
    "sceNpSnsIntFbGetTitleInfo:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntFbGetTitleInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntFbGetTitleInfo\n"
    ".type __load_and_call_sceNpSnsIntFbGetTitleInfo @function\n"
    "__load_and_call_sceNpSnsIntFbGetTitleInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntFbGetTitleInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntFbGetTitleInfo]\n");

void __load_and_call_sceNpSnsIntFbGetTitleInfo();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntFbGetTitleInfo = &__load_and_call_sceNpSnsIntFbGetTitleInfo;

static __attribute__ ((used)) void
__load_sceNpSnsIntFbGetTitleInfo(void) {
  sprx_dlsym(__handle, "sceNpSnsIntFbGetTitleInfo", &__ptr_sceNpSnsIntFbGetTitleInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntLinkedStatus\n"
    ".type sceNpSnsIntLinkedStatus @function\n"
    "sceNpSnsIntLinkedStatus:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntLinkedStatus]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntLinkedStatus\n"
    ".type __load_and_call_sceNpSnsIntLinkedStatus @function\n"
    "__load_and_call_sceNpSnsIntLinkedStatus:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntLinkedStatus\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntLinkedStatus]\n");

void __load_and_call_sceNpSnsIntLinkedStatus();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntLinkedStatus = &__load_and_call_sceNpSnsIntLinkedStatus;

static __attribute__ ((used)) void
__load_sceNpSnsIntLinkedStatus(void) {
  sprx_dlsym(__handle, "sceNpSnsIntLinkedStatus", &__ptr_sceNpSnsIntLinkedStatus);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntTwGetSystemAccessToken\n"
    ".type sceNpSnsIntTwGetSystemAccessToken @function\n"
    "sceNpSnsIntTwGetSystemAccessToken:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntTwGetSystemAccessToken]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntTwGetSystemAccessToken\n"
    ".type __load_and_call_sceNpSnsIntTwGetSystemAccessToken @function\n"
    "__load_and_call_sceNpSnsIntTwGetSystemAccessToken:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntTwGetSystemAccessToken\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntTwGetSystemAccessToken]\n");

void __load_and_call_sceNpSnsIntTwGetSystemAccessToken();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntTwGetSystemAccessToken = &__load_and_call_sceNpSnsIntTwGetSystemAccessToken;

static __attribute__ ((used)) void
__load_sceNpSnsIntTwGetSystemAccessToken(void) {
  sprx_dlsym(__handle, "sceNpSnsIntTwGetSystemAccessToken", &__ptr_sceNpSnsIntTwGetSystemAccessToken);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntUnlink\n"
    ".type sceNpSnsIntUnlink @function\n"
    "sceNpSnsIntUnlink:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntUnlink]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntUnlink\n"
    ".type __load_and_call_sceNpSnsIntUnlink @function\n"
    "__load_and_call_sceNpSnsIntUnlink:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntUnlink\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntUnlink]\n");

void __load_and_call_sceNpSnsIntUnlink();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntUnlink = &__load_and_call_sceNpSnsIntUnlink;

static __attribute__ ((used)) void
__load_sceNpSnsIntUnlink(void) {
  sprx_dlsym(__handle, "sceNpSnsIntUnlink", &__ptr_sceNpSnsIntUnlink);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntYtGetAccessToken\n"
    ".type sceNpSnsIntYtGetAccessToken @function\n"
    "sceNpSnsIntYtGetAccessToken:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntYtGetAccessToken]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntYtGetAccessToken\n"
    ".type __load_and_call_sceNpSnsIntYtGetAccessToken @function\n"
    "__load_and_call_sceNpSnsIntYtGetAccessToken:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntYtGetAccessToken\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntYtGetAccessToken]\n");

void __load_and_call_sceNpSnsIntYtGetAccessToken();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntYtGetAccessToken = &__load_and_call_sceNpSnsIntYtGetAccessToken;

static __attribute__ ((used)) void
__load_sceNpSnsIntYtGetAccessToken(void) {
  sprx_dlsym(__handle, "sceNpSnsIntYtGetAccessToken", &__ptr_sceNpSnsIntYtGetAccessToken);
}

asm(".intel_syntax noprefix\n"
    ".global sceNpSnsIntYtRefreshMasterToken\n"
    ".type sceNpSnsIntYtRefreshMasterToken @function\n"
    "sceNpSnsIntYtRefreshMasterToken:\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntYtRefreshMasterToken]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceNpSnsIntYtRefreshMasterToken\n"
    ".type __load_and_call_sceNpSnsIntYtRefreshMasterToken @function\n"
    "__load_and_call_sceNpSnsIntYtRefreshMasterToken:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceNpSnsIntYtRefreshMasterToken\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceNpSnsIntYtRefreshMasterToken]\n");

void __load_and_call_sceNpSnsIntYtRefreshMasterToken();
static __attribute__ ((used)) void* __ptr_sceNpSnsIntYtRefreshMasterToken = &__load_and_call_sceNpSnsIntYtRefreshMasterToken;

static __attribute__ ((used)) void
__load_sceNpSnsIntYtRefreshMasterToken(void) {
  sprx_dlsym(__handle, "sceNpSnsIntYtRefreshMasterToken", &__ptr_sceNpSnsIntYtRefreshMasterToken);
}
