/*
 This file was generated by trampgen.py, do not edit manually!
*/


int sprx_dlsym(unsigned int handle, const char *symname, void *addr);
int sprx_dlopen(const char* libname, unsigned short *handle);
int sprx_dlclose(unsigned short handle);


static unsigned short __handle = 0;

static void __attribute__((constructor(102)))
__constructor(void) {
  sprx_dlopen("libSceAgcDriver", &__handle);
}

static void __attribute__((destructor(102)))
__destructor(void) {
  sprx_dlclose(__handle);
}


asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverAddEqEvent\n"
    ".type sceAgcDriverAddEqEvent @function\n"
    "sceAgcDriverAddEqEvent:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverAddEqEvent]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverAddEqEvent\n"
    ".type __load_and_call_sceAgcDriverAddEqEvent @function\n"
    "__load_and_call_sceAgcDriverAddEqEvent:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverAddEqEvent\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverAddEqEvent]\n");

void __load_and_call_sceAgcDriverAddEqEvent();
static __attribute__ ((used)) void* __ptr_sceAgcDriverAddEqEvent = &__load_and_call_sceAgcDriverAddEqEvent;

static __attribute__ ((used)) void
__load_sceAgcDriverAddEqEvent(void) {
  sprx_dlsym(__handle, "sceAgcDriverAddEqEvent", &__ptr_sceAgcDriverAddEqEvent);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverAgrSubmitDcb\n"
    ".type sceAgcDriverAgrSubmitDcb @function\n"
    "sceAgcDriverAgrSubmitDcb:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverAgrSubmitDcb]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverAgrSubmitDcb\n"
    ".type __load_and_call_sceAgcDriverAgrSubmitDcb @function\n"
    "__load_and_call_sceAgcDriverAgrSubmitDcb:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverAgrSubmitDcb\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverAgrSubmitDcb]\n");

void __load_and_call_sceAgcDriverAgrSubmitDcb();
static __attribute__ ((used)) void* __ptr_sceAgcDriverAgrSubmitDcb = &__load_and_call_sceAgcDriverAgrSubmitDcb;

static __attribute__ ((used)) void
__load_sceAgcDriverAgrSubmitDcb(void) {
  sprx_dlsym(__handle, "sceAgcDriverAgrSubmitDcb", &__ptr_sceAgcDriverAgrSubmitDcb);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverAgrSubmitMultiDcbs\n"
    ".type sceAgcDriverAgrSubmitMultiDcbs @function\n"
    "sceAgcDriverAgrSubmitMultiDcbs:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverAgrSubmitMultiDcbs]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverAgrSubmitMultiDcbs\n"
    ".type __load_and_call_sceAgcDriverAgrSubmitMultiDcbs @function\n"
    "__load_and_call_sceAgcDriverAgrSubmitMultiDcbs:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverAgrSubmitMultiDcbs\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverAgrSubmitMultiDcbs]\n");

void __load_and_call_sceAgcDriverAgrSubmitMultiDcbs();
static __attribute__ ((used)) void* __ptr_sceAgcDriverAgrSubmitMultiDcbs = &__load_and_call_sceAgcDriverAgrSubmitMultiDcbs;

static __attribute__ ((used)) void
__load_sceAgcDriverAgrSubmitMultiDcbs(void) {
  sprx_dlsym(__handle, "sceAgcDriverAgrSubmitMultiDcbs", &__ptr_sceAgcDriverAgrSubmitMultiDcbs);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverCreateQueue\n"
    ".type sceAgcDriverCreateQueue @function\n"
    "sceAgcDriverCreateQueue:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverCreateQueue]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverCreateQueue\n"
    ".type __load_and_call_sceAgcDriverCreateQueue @function\n"
    "__load_and_call_sceAgcDriverCreateQueue:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverCreateQueue\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverCreateQueue]\n");

void __load_and_call_sceAgcDriverCreateQueue();
static __attribute__ ((used)) void* __ptr_sceAgcDriverCreateQueue = &__load_and_call_sceAgcDriverCreateQueue;

static __attribute__ ((used)) void
__load_sceAgcDriverCreateQueue(void) {
  sprx_dlsym(__handle, "sceAgcDriverCreateQueue", &__ptr_sceAgcDriverCreateQueue);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverCwsrResumeAcq\n"
    ".type sceAgcDriverCwsrResumeAcq @function\n"
    "sceAgcDriverCwsrResumeAcq:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverCwsrResumeAcq]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverCwsrResumeAcq\n"
    ".type __load_and_call_sceAgcDriverCwsrResumeAcq @function\n"
    "__load_and_call_sceAgcDriverCwsrResumeAcq:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverCwsrResumeAcq\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverCwsrResumeAcq]\n");

void __load_and_call_sceAgcDriverCwsrResumeAcq();
static __attribute__ ((used)) void* __ptr_sceAgcDriverCwsrResumeAcq = &__load_and_call_sceAgcDriverCwsrResumeAcq;

static __attribute__ ((used)) void
__load_sceAgcDriverCwsrResumeAcq(void) {
  sprx_dlsym(__handle, "sceAgcDriverCwsrResumeAcq", &__ptr_sceAgcDriverCwsrResumeAcq);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverCwsrSuspendAcq\n"
    ".type sceAgcDriverCwsrSuspendAcq @function\n"
    "sceAgcDriverCwsrSuspendAcq:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverCwsrSuspendAcq]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverCwsrSuspendAcq\n"
    ".type __load_and_call_sceAgcDriverCwsrSuspendAcq @function\n"
    "__load_and_call_sceAgcDriverCwsrSuspendAcq:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverCwsrSuspendAcq\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverCwsrSuspendAcq]\n");

void __load_and_call_sceAgcDriverCwsrSuspendAcq();
static __attribute__ ((used)) void* __ptr_sceAgcDriverCwsrSuspendAcq = &__load_and_call_sceAgcDriverCwsrSuspendAcq;

static __attribute__ ((used)) void
__load_sceAgcDriverCwsrSuspendAcq(void) {
  sprx_dlsym(__handle, "sceAgcDriverCwsrSuspendAcq", &__ptr_sceAgcDriverCwsrSuspendAcq);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverDebugHardwareStatus\n"
    ".type sceAgcDriverDebugHardwareStatus @function\n"
    "sceAgcDriverDebugHardwareStatus:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverDebugHardwareStatus]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverDebugHardwareStatus\n"
    ".type __load_and_call_sceAgcDriverDebugHardwareStatus @function\n"
    "__load_and_call_sceAgcDriverDebugHardwareStatus:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverDebugHardwareStatus\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverDebugHardwareStatus]\n");

void __load_and_call_sceAgcDriverDebugHardwareStatus();
static __attribute__ ((used)) void* __ptr_sceAgcDriverDebugHardwareStatus = &__load_and_call_sceAgcDriverDebugHardwareStatus;

static __attribute__ ((used)) void
__load_sceAgcDriverDebugHardwareStatus(void) {
  sprx_dlsym(__handle, "sceAgcDriverDebugHardwareStatus", &__ptr_sceAgcDriverDebugHardwareStatus);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverDeleteEqEvent\n"
    ".type sceAgcDriverDeleteEqEvent @function\n"
    "sceAgcDriverDeleteEqEvent:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverDeleteEqEvent]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverDeleteEqEvent\n"
    ".type __load_and_call_sceAgcDriverDeleteEqEvent @function\n"
    "__load_and_call_sceAgcDriverDeleteEqEvent:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverDeleteEqEvent\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverDeleteEqEvent]\n");

void __load_and_call_sceAgcDriverDeleteEqEvent();
static __attribute__ ((used)) void* __ptr_sceAgcDriverDeleteEqEvent = &__load_and_call_sceAgcDriverDeleteEqEvent;

static __attribute__ ((used)) void
__load_sceAgcDriverDeleteEqEvent(void) {
  sprx_dlsym(__handle, "sceAgcDriverDeleteEqEvent", &__ptr_sceAgcDriverDeleteEqEvent);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverDestroyQueue\n"
    ".type sceAgcDriverDestroyQueue @function\n"
    "sceAgcDriverDestroyQueue:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverDestroyQueue]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverDestroyQueue\n"
    ".type __load_and_call_sceAgcDriverDestroyQueue @function\n"
    "__load_and_call_sceAgcDriverDestroyQueue:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverDestroyQueue\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverDestroyQueue]\n");

void __load_and_call_sceAgcDriverDestroyQueue();
static __attribute__ ((used)) void* __ptr_sceAgcDriverDestroyQueue = &__load_and_call_sceAgcDriverDestroyQueue;

static __attribute__ ((used)) void
__load_sceAgcDriverDestroyQueue(void) {
  sprx_dlsym(__handle, "sceAgcDriverDestroyQueue", &__ptr_sceAgcDriverDestroyQueue);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverFindResourcesPublic\n"
    ".type sceAgcDriverFindResourcesPublic @function\n"
    "sceAgcDriverFindResourcesPublic:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverFindResourcesPublic]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverFindResourcesPublic\n"
    ".type __load_and_call_sceAgcDriverFindResourcesPublic @function\n"
    "__load_and_call_sceAgcDriverFindResourcesPublic:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverFindResourcesPublic\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverFindResourcesPublic]\n");

void __load_and_call_sceAgcDriverFindResourcesPublic();
static __attribute__ ((used)) void* __ptr_sceAgcDriverFindResourcesPublic = &__load_and_call_sceAgcDriverFindResourcesPublic;

static __attribute__ ((used)) void
__load_sceAgcDriverFindResourcesPublic(void) {
  sprx_dlsym(__handle, "sceAgcDriverFindResourcesPublic", &__ptr_sceAgcDriverFindResourcesPublic);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetEqContextId\n"
    ".type sceAgcDriverGetEqContextId @function\n"
    "sceAgcDriverGetEqContextId:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetEqContextId]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetEqContextId\n"
    ".type __load_and_call_sceAgcDriverGetEqContextId @function\n"
    "__load_and_call_sceAgcDriverGetEqContextId:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetEqContextId\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetEqContextId]\n");

void __load_and_call_sceAgcDriverGetEqContextId();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetEqContextId = &__load_and_call_sceAgcDriverGetEqContextId;

static __attribute__ ((used)) void
__load_sceAgcDriverGetEqContextId(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetEqContextId", &__ptr_sceAgcDriverGetEqContextId);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetEqEventType\n"
    ".type sceAgcDriverGetEqEventType @function\n"
    "sceAgcDriverGetEqEventType:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetEqEventType]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetEqEventType\n"
    ".type __load_and_call_sceAgcDriverGetEqEventType @function\n"
    "__load_and_call_sceAgcDriverGetEqEventType:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetEqEventType\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetEqEventType]\n");

void __load_and_call_sceAgcDriverGetEqEventType();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetEqEventType = &__load_and_call_sceAgcDriverGetEqEventType;

static __attribute__ ((used)) void
__load_sceAgcDriverGetEqEventType(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetEqEventType", &__ptr_sceAgcDriverGetEqEventType);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetGpuRefClks\n"
    ".type sceAgcDriverGetGpuRefClks @function\n"
    "sceAgcDriverGetGpuRefClks:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetGpuRefClks]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetGpuRefClks\n"
    ".type __load_and_call_sceAgcDriverGetGpuRefClks @function\n"
    "__load_and_call_sceAgcDriverGetGpuRefClks:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetGpuRefClks\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetGpuRefClks]\n");

void __load_and_call_sceAgcDriverGetGpuRefClks();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetGpuRefClks = &__load_and_call_sceAgcDriverGetGpuRefClks;

static __attribute__ ((used)) void
__load_sceAgcDriverGetGpuRefClks(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetGpuRefClks", &__ptr_sceAgcDriverGetGpuRefClks);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetHsOffchipParam\n"
    ".type sceAgcDriverGetHsOffchipParam @function\n"
    "sceAgcDriverGetHsOffchipParam:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetHsOffchipParam]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetHsOffchipParam\n"
    ".type __load_and_call_sceAgcDriverGetHsOffchipParam @function\n"
    "__load_and_call_sceAgcDriverGetHsOffchipParam:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetHsOffchipParam\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetHsOffchipParam]\n");

void __load_and_call_sceAgcDriverGetHsOffchipParam();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetHsOffchipParam = &__load_and_call_sceAgcDriverGetHsOffchipParam;

static __attribute__ ((used)) void
__load_sceAgcDriverGetHsOffchipParam(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetHsOffchipParam", &__ptr_sceAgcDriverGetHsOffchipParam);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetOwnerName\n"
    ".type sceAgcDriverGetOwnerName @function\n"
    "sceAgcDriverGetOwnerName:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetOwnerName]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetOwnerName\n"
    ".type __load_and_call_sceAgcDriverGetOwnerName @function\n"
    "__load_and_call_sceAgcDriverGetOwnerName:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetOwnerName\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetOwnerName]\n");

void __load_and_call_sceAgcDriverGetOwnerName();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetOwnerName = &__load_and_call_sceAgcDriverGetOwnerName;

static __attribute__ ((used)) void
__load_sceAgcDriverGetOwnerName(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetOwnerName", &__ptr_sceAgcDriverGetOwnerName);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetRegShadowInfo\n"
    ".type sceAgcDriverGetRegShadowInfo @function\n"
    "sceAgcDriverGetRegShadowInfo:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetRegShadowInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetRegShadowInfo\n"
    ".type __load_and_call_sceAgcDriverGetRegShadowInfo @function\n"
    "__load_and_call_sceAgcDriverGetRegShadowInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetRegShadowInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetRegShadowInfo]\n");

void __load_and_call_sceAgcDriverGetRegShadowInfo();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetRegShadowInfo = &__load_and_call_sceAgcDriverGetRegShadowInfo;

static __attribute__ ((used)) void
__load_sceAgcDriverGetRegShadowInfo(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetRegShadowInfo", &__ptr_sceAgcDriverGetRegShadowInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetRegShadowInfoAgr\n"
    ".type sceAgcDriverGetRegShadowInfoAgr @function\n"
    "sceAgcDriverGetRegShadowInfoAgr:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetRegShadowInfoAgr]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetRegShadowInfoAgr\n"
    ".type __load_and_call_sceAgcDriverGetRegShadowInfoAgr @function\n"
    "__load_and_call_sceAgcDriverGetRegShadowInfoAgr:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetRegShadowInfoAgr\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetRegShadowInfoAgr]\n");

void __load_and_call_sceAgcDriverGetRegShadowInfoAgr();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetRegShadowInfoAgr = &__load_and_call_sceAgcDriverGetRegShadowInfoAgr;

static __attribute__ ((used)) void
__load_sceAgcDriverGetRegShadowInfoAgr(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetRegShadowInfoAgr", &__ptr_sceAgcDriverGetRegShadowInfoAgr);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetReservedDmemForAgc\n"
    ".type sceAgcDriverGetReservedDmemForAgc @function\n"
    "sceAgcDriverGetReservedDmemForAgc:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetReservedDmemForAgc]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetReservedDmemForAgc\n"
    ".type __load_and_call_sceAgcDriverGetReservedDmemForAgc @function\n"
    "__load_and_call_sceAgcDriverGetReservedDmemForAgc:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetReservedDmemForAgc\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetReservedDmemForAgc]\n");

void __load_and_call_sceAgcDriverGetReservedDmemForAgc();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetReservedDmemForAgc = &__load_and_call_sceAgcDriverGetReservedDmemForAgc;

static __attribute__ ((used)) void
__load_sceAgcDriverGetReservedDmemForAgc(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetReservedDmemForAgc", &__ptr_sceAgcDriverGetReservedDmemForAgc);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetResourceBaseAddressAndSizeInBytes\n"
    ".type sceAgcDriverGetResourceBaseAddressAndSizeInBytes @function\n"
    "sceAgcDriverGetResourceBaseAddressAndSizeInBytes:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceBaseAddressAndSizeInBytes]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetResourceBaseAddressAndSizeInBytes\n"
    ".type __load_and_call_sceAgcDriverGetResourceBaseAddressAndSizeInBytes @function\n"
    "__load_and_call_sceAgcDriverGetResourceBaseAddressAndSizeInBytes:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetResourceBaseAddressAndSizeInBytes\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceBaseAddressAndSizeInBytes]\n");

void __load_and_call_sceAgcDriverGetResourceBaseAddressAndSizeInBytes();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetResourceBaseAddressAndSizeInBytes = &__load_and_call_sceAgcDriverGetResourceBaseAddressAndSizeInBytes;

static __attribute__ ((used)) void
__load_sceAgcDriverGetResourceBaseAddressAndSizeInBytes(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetResourceBaseAddressAndSizeInBytes", &__ptr_sceAgcDriverGetResourceBaseAddressAndSizeInBytes);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetResourceName\n"
    ".type sceAgcDriverGetResourceName @function\n"
    "sceAgcDriverGetResourceName:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceName]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetResourceName\n"
    ".type __load_and_call_sceAgcDriverGetResourceName @function\n"
    "__load_and_call_sceAgcDriverGetResourceName:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetResourceName\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceName]\n");

void __load_and_call_sceAgcDriverGetResourceName();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetResourceName = &__load_and_call_sceAgcDriverGetResourceName;

static __attribute__ ((used)) void
__load_sceAgcDriverGetResourceName(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetResourceName", &__ptr_sceAgcDriverGetResourceName);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetResourceShaderGuid\n"
    ".type sceAgcDriverGetResourceShaderGuid @function\n"
    "sceAgcDriverGetResourceShaderGuid:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceShaderGuid]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetResourceShaderGuid\n"
    ".type __load_and_call_sceAgcDriverGetResourceShaderGuid @function\n"
    "__load_and_call_sceAgcDriverGetResourceShaderGuid:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetResourceShaderGuid\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceShaderGuid]\n");

void __load_and_call_sceAgcDriverGetResourceShaderGuid();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetResourceShaderGuid = &__load_and_call_sceAgcDriverGetResourceShaderGuid;

static __attribute__ ((used)) void
__load_sceAgcDriverGetResourceShaderGuid(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetResourceShaderGuid", &__ptr_sceAgcDriverGetResourceShaderGuid);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetResourceType\n"
    ".type sceAgcDriverGetResourceType @function\n"
    "sceAgcDriverGetResourceType:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceType]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetResourceType\n"
    ".type __load_and_call_sceAgcDriverGetResourceType @function\n"
    "__load_and_call_sceAgcDriverGetResourceType:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetResourceType\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceType]\n");

void __load_and_call_sceAgcDriverGetResourceType();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetResourceType = &__load_and_call_sceAgcDriverGetResourceType;

static __attribute__ ((used)) void
__load_sceAgcDriverGetResourceType(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetResourceType", &__ptr_sceAgcDriverGetResourceType);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetResourceUserData\n"
    ".type sceAgcDriverGetResourceUserData @function\n"
    "sceAgcDriverGetResourceUserData:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceUserData]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetResourceUserData\n"
    ".type __load_and_call_sceAgcDriverGetResourceUserData @function\n"
    "__load_and_call_sceAgcDriverGetResourceUserData:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetResourceUserData\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetResourceUserData]\n");

void __load_and_call_sceAgcDriverGetResourceUserData();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetResourceUserData = &__load_and_call_sceAgcDriverGetResourceUserData;

static __attribute__ ((used)) void
__load_sceAgcDriverGetResourceUserData(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetResourceUserData", &__ptr_sceAgcDriverGetResourceUserData);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetSetFlipPacketSizeInDwords\n"
    ".type sceAgcDriverGetSetFlipPacketSizeInDwords @function\n"
    "sceAgcDriverGetSetFlipPacketSizeInDwords:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetSetFlipPacketSizeInDwords]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetSetFlipPacketSizeInDwords\n"
    ".type __load_and_call_sceAgcDriverGetSetFlipPacketSizeInDwords @function\n"
    "__load_and_call_sceAgcDriverGetSetFlipPacketSizeInDwords:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetSetFlipPacketSizeInDwords\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetSetFlipPacketSizeInDwords]\n");

void __load_and_call_sceAgcDriverGetSetFlipPacketSizeInDwords();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetSetFlipPacketSizeInDwords = &__load_and_call_sceAgcDriverGetSetFlipPacketSizeInDwords;

static __attribute__ ((used)) void
__load_sceAgcDriverGetSetFlipPacketSizeInDwords(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetSetFlipPacketSizeInDwords", &__ptr_sceAgcDriverGetSetFlipPacketSizeInDwords);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetSetWorkloadCompletePacketSize\n"
    ".type sceAgcDriverGetSetWorkloadCompletePacketSize @function\n"
    "sceAgcDriverGetSetWorkloadCompletePacketSize:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetSetWorkloadCompletePacketSize]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetSetWorkloadCompletePacketSize\n"
    ".type __load_and_call_sceAgcDriverGetSetWorkloadCompletePacketSize @function\n"
    "__load_and_call_sceAgcDriverGetSetWorkloadCompletePacketSize:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetSetWorkloadCompletePacketSize\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetSetWorkloadCompletePacketSize]\n");

void __load_and_call_sceAgcDriverGetSetWorkloadCompletePacketSize();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetSetWorkloadCompletePacketSize = &__load_and_call_sceAgcDriverGetSetWorkloadCompletePacketSize;

static __attribute__ ((used)) void
__load_sceAgcDriverGetSetWorkloadCompletePacketSize(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetSetWorkloadCompletePacketSize", &__ptr_sceAgcDriverGetSetWorkloadCompletePacketSize);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetSetWorkloadsActivePacketSize\n"
    ".type sceAgcDriverGetSetWorkloadsActivePacketSize @function\n"
    "sceAgcDriverGetSetWorkloadsActivePacketSize:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetSetWorkloadsActivePacketSize]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetSetWorkloadsActivePacketSize\n"
    ".type __load_and_call_sceAgcDriverGetSetWorkloadsActivePacketSize @function\n"
    "__load_and_call_sceAgcDriverGetSetWorkloadsActivePacketSize:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetSetWorkloadsActivePacketSize\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetSetWorkloadsActivePacketSize]\n");

void __load_and_call_sceAgcDriverGetSetWorkloadsActivePacketSize();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetSetWorkloadsActivePacketSize = &__load_and_call_sceAgcDriverGetSetWorkloadsActivePacketSize;

static __attribute__ ((used)) void
__load_sceAgcDriverGetSetWorkloadsActivePacketSize(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetSetWorkloadsActivePacketSize", &__ptr_sceAgcDriverGetSetWorkloadsActivePacketSize);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetTFRing\n"
    ".type sceAgcDriverGetTFRing @function\n"
    "sceAgcDriverGetTFRing:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetTFRing]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetTFRing\n"
    ".type __load_and_call_sceAgcDriverGetTFRing @function\n"
    "__load_and_call_sceAgcDriverGetTFRing:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetTFRing\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetTFRing]\n");

void __load_and_call_sceAgcDriverGetTFRing();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetTFRing = &__load_and_call_sceAgcDriverGetTFRing;

static __attribute__ ((used)) void
__load_sceAgcDriverGetTFRing(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetTFRing", &__ptr_sceAgcDriverGetTFRing);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetTraceInitiator\n"
    ".type sceAgcDriverGetTraceInitiator @function\n"
    "sceAgcDriverGetTraceInitiator:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetTraceInitiator]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetTraceInitiator\n"
    ".type __load_and_call_sceAgcDriverGetTraceInitiator @function\n"
    "__load_and_call_sceAgcDriverGetTraceInitiator:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetTraceInitiator\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetTraceInitiator]\n");

void __load_and_call_sceAgcDriverGetTraceInitiator();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetTraceInitiator = &__load_and_call_sceAgcDriverGetTraceInitiator;

static __attribute__ ((used)) void
__load_sceAgcDriverGetTraceInitiator(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetTraceInitiator", &__ptr_sceAgcDriverGetTraceInitiator);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetWaitRenderingPacketSizeInDwords\n"
    ".type sceAgcDriverGetWaitRenderingPacketSizeInDwords @function\n"
    "sceAgcDriverGetWaitRenderingPacketSizeInDwords:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetWaitRenderingPacketSizeInDwords]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetWaitRenderingPacketSizeInDwords\n"
    ".type __load_and_call_sceAgcDriverGetWaitRenderingPacketSizeInDwords @function\n"
    "__load_and_call_sceAgcDriverGetWaitRenderingPacketSizeInDwords:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetWaitRenderingPacketSizeInDwords\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetWaitRenderingPacketSizeInDwords]\n");

void __load_and_call_sceAgcDriverGetWaitRenderingPacketSizeInDwords();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetWaitRenderingPacketSizeInDwords = &__load_and_call_sceAgcDriverGetWaitRenderingPacketSizeInDwords;

static __attribute__ ((used)) void
__load_sceAgcDriverGetWaitRenderingPacketSizeInDwords(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetWaitRenderingPacketSizeInDwords", &__ptr_sceAgcDriverGetWaitRenderingPacketSizeInDwords);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverGetWorkloadStreamInfo\n"
    ".type sceAgcDriverGetWorkloadStreamInfo @function\n"
    "sceAgcDriverGetWorkloadStreamInfo:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetWorkloadStreamInfo]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverGetWorkloadStreamInfo\n"
    ".type __load_and_call_sceAgcDriverGetWorkloadStreamInfo @function\n"
    "__load_and_call_sceAgcDriverGetWorkloadStreamInfo:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverGetWorkloadStreamInfo\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverGetWorkloadStreamInfo]\n");

void __load_and_call_sceAgcDriverGetWorkloadStreamInfo();
static __attribute__ ((used)) void* __ptr_sceAgcDriverGetWorkloadStreamInfo = &__load_and_call_sceAgcDriverGetWorkloadStreamInfo;

static __attribute__ ((used)) void
__load_sceAgcDriverGetWorkloadStreamInfo(void) {
  sprx_dlsym(__handle, "sceAgcDriverGetWorkloadStreamInfo", &__ptr_sceAgcDriverGetWorkloadStreamInfo);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverIDHSSubmit\n"
    ".type sceAgcDriverIDHSSubmit @function\n"
    "sceAgcDriverIDHSSubmit:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverIDHSSubmit]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverIDHSSubmit\n"
    ".type __load_and_call_sceAgcDriverIDHSSubmit @function\n"
    "__load_and_call_sceAgcDriverIDHSSubmit:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverIDHSSubmit\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverIDHSSubmit]\n");

void __load_and_call_sceAgcDriverIDHSSubmit();
static __attribute__ ((used)) void* __ptr_sceAgcDriverIDHSSubmit = &__load_and_call_sceAgcDriverIDHSSubmit;

static __attribute__ ((used)) void
__load_sceAgcDriverIDHSSubmit(void) {
  sprx_dlsym(__handle, "sceAgcDriverIDHSSubmit", &__ptr_sceAgcDriverIDHSSubmit);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverInitResourceRegistration\n"
    ".type sceAgcDriverInitResourceRegistration @function\n"
    "sceAgcDriverInitResourceRegistration:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverInitResourceRegistration]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverInitResourceRegistration\n"
    ".type __load_and_call_sceAgcDriverInitResourceRegistration @function\n"
    "__load_and_call_sceAgcDriverInitResourceRegistration:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverInitResourceRegistration\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverInitResourceRegistration]\n");

void __load_and_call_sceAgcDriverInitResourceRegistration();
static __attribute__ ((used)) void* __ptr_sceAgcDriverInitResourceRegistration = &__load_and_call_sceAgcDriverInitResourceRegistration;

static __attribute__ ((used)) void
__load_sceAgcDriverInitResourceRegistration(void) {
  sprx_dlsym(__handle, "sceAgcDriverInitResourceRegistration", &__ptr_sceAgcDriverInitResourceRegistration);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverIsCaptureInProgress\n"
    ".type sceAgcDriverIsCaptureInProgress @function\n"
    "sceAgcDriverIsCaptureInProgress:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverIsCaptureInProgress]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverIsCaptureInProgress\n"
    ".type __load_and_call_sceAgcDriverIsCaptureInProgress @function\n"
    "__load_and_call_sceAgcDriverIsCaptureInProgress:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverIsCaptureInProgress\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverIsCaptureInProgress]\n");

void __load_and_call_sceAgcDriverIsCaptureInProgress();
static __attribute__ ((used)) void* __ptr_sceAgcDriverIsCaptureInProgress = &__load_and_call_sceAgcDriverIsCaptureInProgress;

static __attribute__ ((used)) void
__load_sceAgcDriverIsCaptureInProgress(void) {
  sprx_dlsym(__handle, "sceAgcDriverIsCaptureInProgress", &__ptr_sceAgcDriverIsCaptureInProgress);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverIsSubmitValidationEnabled\n"
    ".type sceAgcDriverIsSubmitValidationEnabled @function\n"
    "sceAgcDriverIsSubmitValidationEnabled:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverIsSubmitValidationEnabled]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverIsSubmitValidationEnabled\n"
    ".type __load_and_call_sceAgcDriverIsSubmitValidationEnabled @function\n"
    "__load_and_call_sceAgcDriverIsSubmitValidationEnabled:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverIsSubmitValidationEnabled\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverIsSubmitValidationEnabled]\n");

void __load_and_call_sceAgcDriverIsSubmitValidationEnabled();
static __attribute__ ((used)) void* __ptr_sceAgcDriverIsSubmitValidationEnabled = &__load_and_call_sceAgcDriverIsSubmitValidationEnabled;

static __attribute__ ((used)) void
__load_sceAgcDriverIsSubmitValidationEnabled(void) {
  sprx_dlsym(__handle, "sceAgcDriverIsSubmitValidationEnabled", &__ptr_sceAgcDriverIsSubmitValidationEnabled);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverIsTraceInProgress\n"
    ".type sceAgcDriverIsTraceInProgress @function\n"
    "sceAgcDriverIsTraceInProgress:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverIsTraceInProgress]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverIsTraceInProgress\n"
    ".type __load_and_call_sceAgcDriverIsTraceInProgress @function\n"
    "__load_and_call_sceAgcDriverIsTraceInProgress:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverIsTraceInProgress\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverIsTraceInProgress]\n");

void __load_and_call_sceAgcDriverIsTraceInProgress();
static __attribute__ ((used)) void* __ptr_sceAgcDriverIsTraceInProgress = &__load_and_call_sceAgcDriverIsTraceInProgress;

static __attribute__ ((used)) void
__load_sceAgcDriverIsTraceInProgress(void) {
  sprx_dlsym(__handle, "sceAgcDriverIsTraceInProgress", &__ptr_sceAgcDriverIsTraceInProgress);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverModuleRegistration\n"
    ".type sceAgcDriverModuleRegistration @function\n"
    "sceAgcDriverModuleRegistration:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverModuleRegistration]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverModuleRegistration\n"
    ".type __load_and_call_sceAgcDriverModuleRegistration @function\n"
    "__load_and_call_sceAgcDriverModuleRegistration:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverModuleRegistration\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverModuleRegistration]\n");

void __load_and_call_sceAgcDriverModuleRegistration();
static __attribute__ ((used)) void* __ptr_sceAgcDriverModuleRegistration = &__load_and_call_sceAgcDriverModuleRegistration;

static __attribute__ ((used)) void
__load_sceAgcDriverModuleRegistration(void) {
  sprx_dlsym(__handle, "sceAgcDriverModuleRegistration", &__ptr_sceAgcDriverModuleRegistration);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverNotifyDefaultStates\n"
    ".type sceAgcDriverNotifyDefaultStates @function\n"
    "sceAgcDriverNotifyDefaultStates:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverNotifyDefaultStates]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverNotifyDefaultStates\n"
    ".type __load_and_call_sceAgcDriverNotifyDefaultStates @function\n"
    "__load_and_call_sceAgcDriverNotifyDefaultStates:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverNotifyDefaultStates\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverNotifyDefaultStates]\n");

void __load_and_call_sceAgcDriverNotifyDefaultStates();
static __attribute__ ((used)) void* __ptr_sceAgcDriverNotifyDefaultStates = &__load_and_call_sceAgcDriverNotifyDefaultStates;

static __attribute__ ((used)) void
__load_sceAgcDriverNotifyDefaultStates(void) {
  sprx_dlsym(__handle, "sceAgcDriverNotifyDefaultStates", &__ptr_sceAgcDriverNotifyDefaultStates);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverPassInfoDownward\n"
    ".type sceAgcDriverPassInfoDownward @function\n"
    "sceAgcDriverPassInfoDownward:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverPassInfoDownward]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverPassInfoDownward\n"
    ".type __load_and_call_sceAgcDriverPassInfoDownward @function\n"
    "__load_and_call_sceAgcDriverPassInfoDownward:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverPassInfoDownward\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverPassInfoDownward]\n");

void __load_and_call_sceAgcDriverPassInfoDownward();
static __attribute__ ((used)) void* __ptr_sceAgcDriverPassInfoDownward = &__load_and_call_sceAgcDriverPassInfoDownward;

static __attribute__ ((used)) void
__load_sceAgcDriverPassInfoDownward(void) {
  sprx_dlsym(__handle, "sceAgcDriverPassInfoDownward", &__ptr_sceAgcDriverPassInfoDownward);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverPatchClearState\n"
    ".type sceAgcDriverPatchClearState @function\n"
    "sceAgcDriverPatchClearState:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverPatchClearState]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverPatchClearState\n"
    ".type __load_and_call_sceAgcDriverPatchClearState @function\n"
    "__load_and_call_sceAgcDriverPatchClearState:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverPatchClearState\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverPatchClearState]\n");

void __load_and_call_sceAgcDriverPatchClearState();
static __attribute__ ((used)) void* __ptr_sceAgcDriverPatchClearState = &__load_and_call_sceAgcDriverPatchClearState;

static __attribute__ ((used)) void
__load_sceAgcDriverPatchClearState(void) {
  sprx_dlsym(__handle, "sceAgcDriverPatchClearState", &__ptr_sceAgcDriverPatchClearState);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverQueryResourceRegistrationUserMemoryRequirements\n"
    ".type sceAgcDriverQueryResourceRegistrationUserMemoryRequirements @function\n"
    "sceAgcDriverQueryResourceRegistrationUserMemoryRequirements:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements\n"
    ".type __load_and_call_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements @function\n"
    "__load_and_call_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements]\n");

void __load_and_call_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements();
static __attribute__ ((used)) void* __ptr_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements = &__load_and_call_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements;

static __attribute__ ((used)) void
__load_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements(void) {
  sprx_dlsym(__handle, "sceAgcDriverQueryResourceRegistrationUserMemoryRequirements", &__ptr_sceAgcDriverQueryResourceRegistrationUserMemoryRequirements);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverRegisterGdsResource\n"
    ".type sceAgcDriverRegisterGdsResource @function\n"
    "sceAgcDriverRegisterGdsResource:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRegisterGdsResource]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverRegisterGdsResource\n"
    ".type __load_and_call_sceAgcDriverRegisterGdsResource @function\n"
    "__load_and_call_sceAgcDriverRegisterGdsResource:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverRegisterGdsResource\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRegisterGdsResource]\n");

void __load_and_call_sceAgcDriverRegisterGdsResource();
static __attribute__ ((used)) void* __ptr_sceAgcDriverRegisterGdsResource = &__load_and_call_sceAgcDriverRegisterGdsResource;

static __attribute__ ((used)) void
__load_sceAgcDriverRegisterGdsResource(void) {
  sprx_dlsym(__handle, "sceAgcDriverRegisterGdsResource", &__ptr_sceAgcDriverRegisterGdsResource);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverRegisterOwner\n"
    ".type sceAgcDriverRegisterOwner @function\n"
    "sceAgcDriverRegisterOwner:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRegisterOwner]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverRegisterOwner\n"
    ".type __load_and_call_sceAgcDriverRegisterOwner @function\n"
    "__load_and_call_sceAgcDriverRegisterOwner:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverRegisterOwner\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRegisterOwner]\n");

void __load_and_call_sceAgcDriverRegisterOwner();
static __attribute__ ((used)) void* __ptr_sceAgcDriverRegisterOwner = &__load_and_call_sceAgcDriverRegisterOwner;

static __attribute__ ((used)) void
__load_sceAgcDriverRegisterOwner(void) {
  sprx_dlsym(__handle, "sceAgcDriverRegisterOwner", &__ptr_sceAgcDriverRegisterOwner);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverRegisterResource\n"
    ".type sceAgcDriverRegisterResource @function\n"
    "sceAgcDriverRegisterResource:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRegisterResource]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverRegisterResource\n"
    ".type __load_and_call_sceAgcDriverRegisterResource @function\n"
    "__load_and_call_sceAgcDriverRegisterResource:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverRegisterResource\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRegisterResource]\n");

void __load_and_call_sceAgcDriverRegisterResource();
static __attribute__ ((used)) void* __ptr_sceAgcDriverRegisterResource = &__load_and_call_sceAgcDriverRegisterResource;

static __attribute__ ((used)) void
__load_sceAgcDriverRegisterResource(void) {
  sprx_dlsym(__handle, "sceAgcDriverRegisterResource", &__ptr_sceAgcDriverRegisterResource);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverRegisterWorkloadStream\n"
    ".type sceAgcDriverRegisterWorkloadStream @function\n"
    "sceAgcDriverRegisterWorkloadStream:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRegisterWorkloadStream]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverRegisterWorkloadStream\n"
    ".type __load_and_call_sceAgcDriverRegisterWorkloadStream @function\n"
    "__load_and_call_sceAgcDriverRegisterWorkloadStream:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverRegisterWorkloadStream\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRegisterWorkloadStream]\n");

void __load_and_call_sceAgcDriverRegisterWorkloadStream();
static __attribute__ ((used)) void* __ptr_sceAgcDriverRegisterWorkloadStream = &__load_and_call_sceAgcDriverRegisterWorkloadStream;

static __attribute__ ((used)) void
__load_sceAgcDriverRegisterWorkloadStream(void) {
  sprx_dlsym(__handle, "sceAgcDriverRegisterWorkloadStream", &__ptr_sceAgcDriverRegisterWorkloadStream);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverRequestCaptureStart\n"
    ".type sceAgcDriverRequestCaptureStart @function\n"
    "sceAgcDriverRequestCaptureStart:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRequestCaptureStart]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverRequestCaptureStart\n"
    ".type __load_and_call_sceAgcDriverRequestCaptureStart @function\n"
    "__load_and_call_sceAgcDriverRequestCaptureStart:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverRequestCaptureStart\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRequestCaptureStart]\n");

void __load_and_call_sceAgcDriverRequestCaptureStart();
static __attribute__ ((used)) void* __ptr_sceAgcDriverRequestCaptureStart = &__load_and_call_sceAgcDriverRequestCaptureStart;

static __attribute__ ((used)) void
__load_sceAgcDriverRequestCaptureStart(void) {
  sprx_dlsym(__handle, "sceAgcDriverRequestCaptureStart", &__ptr_sceAgcDriverRequestCaptureStart);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverRequestCaptureStop\n"
    ".type sceAgcDriverRequestCaptureStop @function\n"
    "sceAgcDriverRequestCaptureStop:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRequestCaptureStop]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverRequestCaptureStop\n"
    ".type __load_and_call_sceAgcDriverRequestCaptureStop @function\n"
    "__load_and_call_sceAgcDriverRequestCaptureStop:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverRequestCaptureStop\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverRequestCaptureStop]\n");

void __load_and_call_sceAgcDriverRequestCaptureStop();
static __attribute__ ((used)) void* __ptr_sceAgcDriverRequestCaptureStop = &__load_and_call_sceAgcDriverRequestCaptureStop;

static __attribute__ ((used)) void
__load_sceAgcDriverRequestCaptureStop(void) {
  sprx_dlsym(__handle, "sceAgcDriverRequestCaptureStop", &__ptr_sceAgcDriverRequestCaptureStop);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSetFlip\n"
    ".type sceAgcDriverSetFlip @function\n"
    "sceAgcDriverSetFlip:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetFlip]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSetFlip\n"
    ".type __load_and_call_sceAgcDriverSetFlip @function\n"
    "__load_and_call_sceAgcDriverSetFlip:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSetFlip\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetFlip]\n");

void __load_and_call_sceAgcDriverSetFlip();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSetFlip = &__load_and_call_sceAgcDriverSetFlip;

static __attribute__ ((used)) void
__load_sceAgcDriverSetFlip(void) {
  sprx_dlsym(__handle, "sceAgcDriverSetFlip", &__ptr_sceAgcDriverSetFlip);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSetHsOffchipParam\n"
    ".type sceAgcDriverSetHsOffchipParam @function\n"
    "sceAgcDriverSetHsOffchipParam:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetHsOffchipParam]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSetHsOffchipParam\n"
    ".type __load_and_call_sceAgcDriverSetHsOffchipParam @function\n"
    "__load_and_call_sceAgcDriverSetHsOffchipParam:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSetHsOffchipParam\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetHsOffchipParam]\n");

void __load_and_call_sceAgcDriverSetHsOffchipParam();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSetHsOffchipParam = &__load_and_call_sceAgcDriverSetHsOffchipParam;

static __attribute__ ((used)) void
__load_sceAgcDriverSetHsOffchipParam(void) {
  sprx_dlsym(__handle, "sceAgcDriverSetHsOffchipParam", &__ptr_sceAgcDriverSetHsOffchipParam);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSetResourceUserData\n"
    ".type sceAgcDriverSetResourceUserData @function\n"
    "sceAgcDriverSetResourceUserData:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetResourceUserData]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSetResourceUserData\n"
    ".type __load_and_call_sceAgcDriverSetResourceUserData @function\n"
    "__load_and_call_sceAgcDriverSetResourceUserData:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSetResourceUserData\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetResourceUserData]\n");

void __load_and_call_sceAgcDriverSetResourceUserData();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSetResourceUserData = &__load_and_call_sceAgcDriverSetResourceUserData;

static __attribute__ ((used)) void
__load_sceAgcDriverSetResourceUserData(void) {
  sprx_dlsym(__handle, "sceAgcDriverSetResourceUserData", &__ptr_sceAgcDriverSetResourceUserData);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSetTFRing\n"
    ".type sceAgcDriverSetTFRing @function\n"
    "sceAgcDriverSetTFRing:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetTFRing]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSetTFRing\n"
    ".type __load_and_call_sceAgcDriverSetTFRing @function\n"
    "__load_and_call_sceAgcDriverSetTFRing:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSetTFRing\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetTFRing]\n");

void __load_and_call_sceAgcDriverSetTFRing();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSetTFRing = &__load_and_call_sceAgcDriverSetTFRing;

static __attribute__ ((used)) void
__load_sceAgcDriverSetTFRing(void) {
  sprx_dlsym(__handle, "sceAgcDriverSetTFRing", &__ptr_sceAgcDriverSetTFRing);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSetWorkloadComplete\n"
    ".type sceAgcDriverSetWorkloadComplete @function\n"
    "sceAgcDriverSetWorkloadComplete:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetWorkloadComplete]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSetWorkloadComplete\n"
    ".type __load_and_call_sceAgcDriverSetWorkloadComplete @function\n"
    "__load_and_call_sceAgcDriverSetWorkloadComplete:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSetWorkloadComplete\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetWorkloadComplete]\n");

void __load_and_call_sceAgcDriverSetWorkloadComplete();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSetWorkloadComplete = &__load_and_call_sceAgcDriverSetWorkloadComplete;

static __attribute__ ((used)) void
__load_sceAgcDriverSetWorkloadComplete(void) {
  sprx_dlsym(__handle, "sceAgcDriverSetWorkloadComplete", &__ptr_sceAgcDriverSetWorkloadComplete);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSetWorkloadsActive\n"
    ".type sceAgcDriverSetWorkloadsActive @function\n"
    "sceAgcDriverSetWorkloadsActive:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetWorkloadsActive]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSetWorkloadsActive\n"
    ".type __load_and_call_sceAgcDriverSetWorkloadsActive @function\n"
    "__load_and_call_sceAgcDriverSetWorkloadsActive:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSetWorkloadsActive\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetWorkloadsActive]\n");

void __load_and_call_sceAgcDriverSetWorkloadsActive();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSetWorkloadsActive = &__load_and_call_sceAgcDriverSetWorkloadsActive;

static __attribute__ ((used)) void
__load_sceAgcDriverSetWorkloadsActive(void) {
  sprx_dlsym(__handle, "sceAgcDriverSetWorkloadsActive", &__ptr_sceAgcDriverSetWorkloadsActive);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSetupAsyncGraphics\n"
    ".type sceAgcDriverSetupAsyncGraphics @function\n"
    "sceAgcDriverSetupAsyncGraphics:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetupAsyncGraphics]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSetupAsyncGraphics\n"
    ".type __load_and_call_sceAgcDriverSetupAsyncGraphics @function\n"
    "__load_and_call_sceAgcDriverSetupAsyncGraphics:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSetupAsyncGraphics\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetupAsyncGraphics]\n");

void __load_and_call_sceAgcDriverSetupAsyncGraphics();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSetupAsyncGraphics = &__load_and_call_sceAgcDriverSetupAsyncGraphics;

static __attribute__ ((used)) void
__load_sceAgcDriverSetupAsyncGraphics(void) {
  sprx_dlsym(__handle, "sceAgcDriverSetupAsyncGraphics", &__ptr_sceAgcDriverSetupAsyncGraphics);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSetupRegisterShadow\n"
    ".type sceAgcDriverSetupRegisterShadow @function\n"
    "sceAgcDriverSetupRegisterShadow:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetupRegisterShadow]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSetupRegisterShadow\n"
    ".type __load_and_call_sceAgcDriverSetupRegisterShadow @function\n"
    "__load_and_call_sceAgcDriverSetupRegisterShadow:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSetupRegisterShadow\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSetupRegisterShadow]\n");

void __load_and_call_sceAgcDriverSetupRegisterShadow();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSetupRegisterShadow = &__load_and_call_sceAgcDriverSetupRegisterShadow;

static __attribute__ ((used)) void
__load_sceAgcDriverSetupRegisterShadow(void) {
  sprx_dlsym(__handle, "sceAgcDriverSetupRegisterShadow", &__ptr_sceAgcDriverSetupRegisterShadow);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSubmitAcb\n"
    ".type sceAgcDriverSubmitAcb @function\n"
    "sceAgcDriverSubmitAcb:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitAcb]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSubmitAcb\n"
    ".type __load_and_call_sceAgcDriverSubmitAcb @function\n"
    "__load_and_call_sceAgcDriverSubmitAcb:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSubmitAcb\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitAcb]\n");

void __load_and_call_sceAgcDriverSubmitAcb();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSubmitAcb = &__load_and_call_sceAgcDriverSubmitAcb;

static __attribute__ ((used)) void
__load_sceAgcDriverSubmitAcb(void) {
  sprx_dlsym(__handle, "sceAgcDriverSubmitAcb", &__ptr_sceAgcDriverSubmitAcb);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSubmitCommandBuffer\n"
    ".type sceAgcDriverSubmitCommandBuffer @function\n"
    "sceAgcDriverSubmitCommandBuffer:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitCommandBuffer]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSubmitCommandBuffer\n"
    ".type __load_and_call_sceAgcDriverSubmitCommandBuffer @function\n"
    "__load_and_call_sceAgcDriverSubmitCommandBuffer:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSubmitCommandBuffer\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitCommandBuffer]\n");

void __load_and_call_sceAgcDriverSubmitCommandBuffer();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSubmitCommandBuffer = &__load_and_call_sceAgcDriverSubmitCommandBuffer;

static __attribute__ ((used)) void
__load_sceAgcDriverSubmitCommandBuffer(void) {
  sprx_dlsym(__handle, "sceAgcDriverSubmitCommandBuffer", &__ptr_sceAgcDriverSubmitCommandBuffer);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSubmitDcb\n"
    ".type sceAgcDriverSubmitDcb @function\n"
    "sceAgcDriverSubmitDcb:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitDcb]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSubmitDcb\n"
    ".type __load_and_call_sceAgcDriverSubmitDcb @function\n"
    "__load_and_call_sceAgcDriverSubmitDcb:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSubmitDcb\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitDcb]\n");

void __load_and_call_sceAgcDriverSubmitDcb();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSubmitDcb = &__load_and_call_sceAgcDriverSubmitDcb;

static __attribute__ ((used)) void
__load_sceAgcDriverSubmitDcb(void) {
  sprx_dlsym(__handle, "sceAgcDriverSubmitDcb", &__ptr_sceAgcDriverSubmitDcb);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSubmitMultiAcbs\n"
    ".type sceAgcDriverSubmitMultiAcbs @function\n"
    "sceAgcDriverSubmitMultiAcbs:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitMultiAcbs]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSubmitMultiAcbs\n"
    ".type __load_and_call_sceAgcDriverSubmitMultiAcbs @function\n"
    "__load_and_call_sceAgcDriverSubmitMultiAcbs:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSubmitMultiAcbs\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitMultiAcbs]\n");

void __load_and_call_sceAgcDriverSubmitMultiAcbs();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSubmitMultiAcbs = &__load_and_call_sceAgcDriverSubmitMultiAcbs;

static __attribute__ ((used)) void
__load_sceAgcDriverSubmitMultiAcbs(void) {
  sprx_dlsym(__handle, "sceAgcDriverSubmitMultiAcbs", &__ptr_sceAgcDriverSubmitMultiAcbs);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSubmitMultiCommandBuffers\n"
    ".type sceAgcDriverSubmitMultiCommandBuffers @function\n"
    "sceAgcDriverSubmitMultiCommandBuffers:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitMultiCommandBuffers]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSubmitMultiCommandBuffers\n"
    ".type __load_and_call_sceAgcDriverSubmitMultiCommandBuffers @function\n"
    "__load_and_call_sceAgcDriverSubmitMultiCommandBuffers:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSubmitMultiCommandBuffers\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitMultiCommandBuffers]\n");

void __load_and_call_sceAgcDriverSubmitMultiCommandBuffers();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSubmitMultiCommandBuffers = &__load_and_call_sceAgcDriverSubmitMultiCommandBuffers;

static __attribute__ ((used)) void
__load_sceAgcDriverSubmitMultiCommandBuffers(void) {
  sprx_dlsym(__handle, "sceAgcDriverSubmitMultiCommandBuffers", &__ptr_sceAgcDriverSubmitMultiCommandBuffers);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSubmitMultiDcbs\n"
    ".type sceAgcDriverSubmitMultiDcbs @function\n"
    "sceAgcDriverSubmitMultiDcbs:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitMultiDcbs]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSubmitMultiDcbs\n"
    ".type __load_and_call_sceAgcDriverSubmitMultiDcbs @function\n"
    "__load_and_call_sceAgcDriverSubmitMultiDcbs:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSubmitMultiDcbs\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitMultiDcbs]\n");

void __load_and_call_sceAgcDriverSubmitMultiDcbs();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSubmitMultiDcbs = &__load_and_call_sceAgcDriverSubmitMultiDcbs;

static __attribute__ ((used)) void
__load_sceAgcDriverSubmitMultiDcbs(void) {
  sprx_dlsym(__handle, "sceAgcDriverSubmitMultiDcbs", &__ptr_sceAgcDriverSubmitMultiDcbs);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSubmitToHDRScopesACQ\n"
    ".type sceAgcDriverSubmitToHDRScopesACQ @function\n"
    "sceAgcDriverSubmitToHDRScopesACQ:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitToHDRScopesACQ]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSubmitToHDRScopesACQ\n"
    ".type __load_and_call_sceAgcDriverSubmitToHDRScopesACQ @function\n"
    "__load_and_call_sceAgcDriverSubmitToHDRScopesACQ:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSubmitToHDRScopesACQ\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSubmitToHDRScopesACQ]\n");

void __load_and_call_sceAgcDriverSubmitToHDRScopesACQ();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSubmitToHDRScopesACQ = &__load_and_call_sceAgcDriverSubmitToHDRScopesACQ;

static __attribute__ ((used)) void
__load_sceAgcDriverSubmitToHDRScopesACQ(void) {
  sprx_dlsym(__handle, "sceAgcDriverSubmitToHDRScopesACQ", &__ptr_sceAgcDriverSubmitToHDRScopesACQ);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSuspendPointSubmit\n"
    ".type sceAgcDriverSuspendPointSubmit @function\n"
    "sceAgcDriverSuspendPointSubmit:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSuspendPointSubmit]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSuspendPointSubmit\n"
    ".type __load_and_call_sceAgcDriverSuspendPointSubmit @function\n"
    "__load_and_call_sceAgcDriverSuspendPointSubmit:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSuspendPointSubmit\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSuspendPointSubmit]\n");

void __load_and_call_sceAgcDriverSuspendPointSubmit();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSuspendPointSubmit = &__load_and_call_sceAgcDriverSuspendPointSubmit;

static __attribute__ ((used)) void
__load_sceAgcDriverSuspendPointSubmit(void) {
  sprx_dlsym(__handle, "sceAgcDriverSuspendPointSubmit", &__ptr_sceAgcDriverSuspendPointSubmit);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSysEnableSubmitDone45Exception\n"
    ".type sceAgcDriverSysEnableSubmitDone45Exception @function\n"
    "sceAgcDriverSysEnableSubmitDone45Exception:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSysEnableSubmitDone45Exception]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSysEnableSubmitDone45Exception\n"
    ".type __load_and_call_sceAgcDriverSysEnableSubmitDone45Exception @function\n"
    "__load_and_call_sceAgcDriverSysEnableSubmitDone45Exception:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSysEnableSubmitDone45Exception\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSysEnableSubmitDone45Exception]\n");

void __load_and_call_sceAgcDriverSysEnableSubmitDone45Exception();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSysEnableSubmitDone45Exception = &__load_and_call_sceAgcDriverSysEnableSubmitDone45Exception;

static __attribute__ ((used)) void
__load_sceAgcDriverSysEnableSubmitDone45Exception(void) {
  sprx_dlsym(__handle, "sceAgcDriverSysEnableSubmitDone45Exception", &__ptr_sceAgcDriverSysEnableSubmitDone45Exception);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSysGetClientNumber\n"
    ".type sceAgcDriverSysGetClientNumber @function\n"
    "sceAgcDriverSysGetClientNumber:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSysGetClientNumber]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSysGetClientNumber\n"
    ".type __load_and_call_sceAgcDriverSysGetClientNumber @function\n"
    "__load_and_call_sceAgcDriverSysGetClientNumber:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSysGetClientNumber\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSysGetClientNumber]\n");

void __load_and_call_sceAgcDriverSysGetClientNumber();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSysGetClientNumber = &__load_and_call_sceAgcDriverSysGetClientNumber;

static __attribute__ ((used)) void
__load_sceAgcDriverSysGetClientNumber(void) {
  sprx_dlsym(__handle, "sceAgcDriverSysGetClientNumber", &__ptr_sceAgcDriverSysGetClientNumber);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSysIsGameClosed\n"
    ".type sceAgcDriverSysIsGameClosed @function\n"
    "sceAgcDriverSysIsGameClosed:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSysIsGameClosed]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSysIsGameClosed\n"
    ".type __load_and_call_sceAgcDriverSysIsGameClosed @function\n"
    "__load_and_call_sceAgcDriverSysIsGameClosed:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSysIsGameClosed\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSysIsGameClosed]\n");

void __load_and_call_sceAgcDriverSysIsGameClosed();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSysIsGameClosed = &__load_and_call_sceAgcDriverSysIsGameClosed;

static __attribute__ ((used)) void
__load_sceAgcDriverSysIsGameClosed(void) {
  sprx_dlsym(__handle, "sceAgcDriverSysIsGameClosed", &__ptr_sceAgcDriverSysIsGameClosed);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverSysSubmitFlipHandleProxy\n"
    ".type sceAgcDriverSysSubmitFlipHandleProxy @function\n"
    "sceAgcDriverSysSubmitFlipHandleProxy:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSysSubmitFlipHandleProxy]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverSysSubmitFlipHandleProxy\n"
    ".type __load_and_call_sceAgcDriverSysSubmitFlipHandleProxy @function\n"
    "__load_and_call_sceAgcDriverSysSubmitFlipHandleProxy:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverSysSubmitFlipHandleProxy\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverSysSubmitFlipHandleProxy]\n");

void __load_and_call_sceAgcDriverSysSubmitFlipHandleProxy();
static __attribute__ ((used)) void* __ptr_sceAgcDriverSysSubmitFlipHandleProxy = &__load_and_call_sceAgcDriverSysSubmitFlipHandleProxy;

static __attribute__ ((used)) void
__load_sceAgcDriverSysSubmitFlipHandleProxy(void) {
  sprx_dlsym(__handle, "sceAgcDriverSysSubmitFlipHandleProxy", &__ptr_sceAgcDriverSysSubmitFlipHandleProxy);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverTmpInitIdhs\n"
    ".type sceAgcDriverTmpInitIdhs @function\n"
    "sceAgcDriverTmpInitIdhs:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverTmpInitIdhs]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverTmpInitIdhs\n"
    ".type __load_and_call_sceAgcDriverTmpInitIdhs @function\n"
    "__load_and_call_sceAgcDriverTmpInitIdhs:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverTmpInitIdhs\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverTmpInitIdhs]\n");

void __load_and_call_sceAgcDriverTmpInitIdhs();
static __attribute__ ((used)) void* __ptr_sceAgcDriverTmpInitIdhs = &__load_and_call_sceAgcDriverTmpInitIdhs;

static __attribute__ ((used)) void
__load_sceAgcDriverTmpInitIdhs(void) {
  sprx_dlsym(__handle, "sceAgcDriverTmpInitIdhs", &__ptr_sceAgcDriverTmpInitIdhs);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverTriggerCapture\n"
    ".type sceAgcDriverTriggerCapture @function\n"
    "sceAgcDriverTriggerCapture:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverTriggerCapture]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverTriggerCapture\n"
    ".type __load_and_call_sceAgcDriverTriggerCapture @function\n"
    "__load_and_call_sceAgcDriverTriggerCapture:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverTriggerCapture\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverTriggerCapture]\n");

void __load_and_call_sceAgcDriverTriggerCapture();
static __attribute__ ((used)) void* __ptr_sceAgcDriverTriggerCapture = &__load_and_call_sceAgcDriverTriggerCapture;

static __attribute__ ((used)) void
__load_sceAgcDriverTriggerCapture(void) {
  sprx_dlsym(__handle, "sceAgcDriverTriggerCapture", &__ptr_sceAgcDriverTriggerCapture);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUnregisterAllResourcesForOwner\n"
    ".type sceAgcDriverUnregisterAllResourcesForOwner @function\n"
    "sceAgcDriverUnregisterAllResourcesForOwner:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUnregisterAllResourcesForOwner]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUnregisterAllResourcesForOwner\n"
    ".type __load_and_call_sceAgcDriverUnregisterAllResourcesForOwner @function\n"
    "__load_and_call_sceAgcDriverUnregisterAllResourcesForOwner:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUnregisterAllResourcesForOwner\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUnregisterAllResourcesForOwner]\n");

void __load_and_call_sceAgcDriverUnregisterAllResourcesForOwner();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUnregisterAllResourcesForOwner = &__load_and_call_sceAgcDriverUnregisterAllResourcesForOwner;

static __attribute__ ((used)) void
__load_sceAgcDriverUnregisterAllResourcesForOwner(void) {
  sprx_dlsym(__handle, "sceAgcDriverUnregisterAllResourcesForOwner", &__ptr_sceAgcDriverUnregisterAllResourcesForOwner);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUnregisterOwnerAndResources\n"
    ".type sceAgcDriverUnregisterOwnerAndResources @function\n"
    "sceAgcDriverUnregisterOwnerAndResources:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUnregisterOwnerAndResources]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUnregisterOwnerAndResources\n"
    ".type __load_and_call_sceAgcDriverUnregisterOwnerAndResources @function\n"
    "__load_and_call_sceAgcDriverUnregisterOwnerAndResources:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUnregisterOwnerAndResources\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUnregisterOwnerAndResources]\n");

void __load_and_call_sceAgcDriverUnregisterOwnerAndResources();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUnregisterOwnerAndResources = &__load_and_call_sceAgcDriverUnregisterOwnerAndResources;

static __attribute__ ((used)) void
__load_sceAgcDriverUnregisterOwnerAndResources(void) {
  sprx_dlsym(__handle, "sceAgcDriverUnregisterOwnerAndResources", &__ptr_sceAgcDriverUnregisterOwnerAndResources);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUnregisterResource\n"
    ".type sceAgcDriverUnregisterResource @function\n"
    "sceAgcDriverUnregisterResource:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUnregisterResource]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUnregisterResource\n"
    ".type __load_and_call_sceAgcDriverUnregisterResource @function\n"
    "__load_and_call_sceAgcDriverUnregisterResource:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUnregisterResource\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUnregisterResource]\n");

void __load_and_call_sceAgcDriverUnregisterResource();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUnregisterResource = &__load_and_call_sceAgcDriverUnregisterResource;

static __attribute__ ((used)) void
__load_sceAgcDriverUnregisterResource(void) {
  sprx_dlsym(__handle, "sceAgcDriverUnregisterResource", &__ptr_sceAgcDriverUnregisterResource);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUnregisterWorkloadStream\n"
    ".type sceAgcDriverUnregisterWorkloadStream @function\n"
    "sceAgcDriverUnregisterWorkloadStream:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUnregisterWorkloadStream]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUnregisterWorkloadStream\n"
    ".type __load_and_call_sceAgcDriverUnregisterWorkloadStream @function\n"
    "__load_and_call_sceAgcDriverUnregisterWorkloadStream:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUnregisterWorkloadStream\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUnregisterWorkloadStream]\n");

void __load_and_call_sceAgcDriverUnregisterWorkloadStream();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUnregisterWorkloadStream = &__load_and_call_sceAgcDriverUnregisterWorkloadStream;

static __attribute__ ((used)) void
__load_sceAgcDriverUnregisterWorkloadStream(void) {
  sprx_dlsym(__handle, "sceAgcDriverUnregisterWorkloadStream", &__ptr_sceAgcDriverUnregisterWorkloadStream);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUserDataGetPacketSize\n"
    ".type sceAgcDriverUserDataGetPacketSize @function\n"
    "sceAgcDriverUserDataGetPacketSize:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataGetPacketSize]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUserDataGetPacketSize\n"
    ".type __load_and_call_sceAgcDriverUserDataGetPacketSize @function\n"
    "__load_and_call_sceAgcDriverUserDataGetPacketSize:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUserDataGetPacketSize\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataGetPacketSize]\n");

void __load_and_call_sceAgcDriverUserDataGetPacketSize();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUserDataGetPacketSize = &__load_and_call_sceAgcDriverUserDataGetPacketSize;

static __attribute__ ((used)) void
__load_sceAgcDriverUserDataGetPacketSize(void) {
  sprx_dlsym(__handle, "sceAgcDriverUserDataGetPacketSize", &__ptr_sceAgcDriverUserDataGetPacketSize);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUserDataImmediateWrite\n"
    ".type sceAgcDriverUserDataImmediateWrite @function\n"
    "sceAgcDriverUserDataImmediateWrite:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataImmediateWrite]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUserDataImmediateWrite\n"
    ".type __load_and_call_sceAgcDriverUserDataImmediateWrite @function\n"
    "__load_and_call_sceAgcDriverUserDataImmediateWrite:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUserDataImmediateWrite\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataImmediateWrite]\n");

void __load_and_call_sceAgcDriverUserDataImmediateWrite();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUserDataImmediateWrite = &__load_and_call_sceAgcDriverUserDataImmediateWrite;

static __attribute__ ((used)) void
__load_sceAgcDriverUserDataImmediateWrite(void) {
  sprx_dlsym(__handle, "sceAgcDriverUserDataImmediateWrite", &__ptr_sceAgcDriverUserDataImmediateWrite);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUserDataWritePacket\n"
    ".type sceAgcDriverUserDataWritePacket @function\n"
    "sceAgcDriverUserDataWritePacket:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataWritePacket]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUserDataWritePacket\n"
    ".type __load_and_call_sceAgcDriverUserDataWritePacket @function\n"
    "__load_and_call_sceAgcDriverUserDataWritePacket:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUserDataWritePacket\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataWritePacket]\n");

void __load_and_call_sceAgcDriverUserDataWritePacket();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUserDataWritePacket = &__load_and_call_sceAgcDriverUserDataWritePacket;

static __attribute__ ((used)) void
__load_sceAgcDriverUserDataWritePacket(void) {
  sprx_dlsym(__handle, "sceAgcDriverUserDataWritePacket", &__ptr_sceAgcDriverUserDataWritePacket);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUserDataWritePopMarker\n"
    ".type sceAgcDriverUserDataWritePopMarker @function\n"
    "sceAgcDriverUserDataWritePopMarker:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataWritePopMarker]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUserDataWritePopMarker\n"
    ".type __load_and_call_sceAgcDriverUserDataWritePopMarker @function\n"
    "__load_and_call_sceAgcDriverUserDataWritePopMarker:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUserDataWritePopMarker\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataWritePopMarker]\n");

void __load_and_call_sceAgcDriverUserDataWritePopMarker();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUserDataWritePopMarker = &__load_and_call_sceAgcDriverUserDataWritePopMarker;

static __attribute__ ((used)) void
__load_sceAgcDriverUserDataWritePopMarker(void) {
  sprx_dlsym(__handle, "sceAgcDriverUserDataWritePopMarker", &__ptr_sceAgcDriverUserDataWritePopMarker);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUserDataWritePushMarker\n"
    ".type sceAgcDriverUserDataWritePushMarker @function\n"
    "sceAgcDriverUserDataWritePushMarker:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataWritePushMarker]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUserDataWritePushMarker\n"
    ".type __load_and_call_sceAgcDriverUserDataWritePushMarker @function\n"
    "__load_and_call_sceAgcDriverUserDataWritePushMarker:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUserDataWritePushMarker\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataWritePushMarker]\n");

void __load_and_call_sceAgcDriverUserDataWritePushMarker();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUserDataWritePushMarker = &__load_and_call_sceAgcDriverUserDataWritePushMarker;

static __attribute__ ((used)) void
__load_sceAgcDriverUserDataWritePushMarker(void) {
  sprx_dlsym(__handle, "sceAgcDriverUserDataWritePushMarker", &__ptr_sceAgcDriverUserDataWritePushMarker);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverUserDataWriteSetMarker\n"
    ".type sceAgcDriverUserDataWriteSetMarker @function\n"
    "sceAgcDriverUserDataWriteSetMarker:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataWriteSetMarker]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverUserDataWriteSetMarker\n"
    ".type __load_and_call_sceAgcDriverUserDataWriteSetMarker @function\n"
    "__load_and_call_sceAgcDriverUserDataWriteSetMarker:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverUserDataWriteSetMarker\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverUserDataWriteSetMarker]\n");

void __load_and_call_sceAgcDriverUserDataWriteSetMarker();
static __attribute__ ((used)) void* __ptr_sceAgcDriverUserDataWriteSetMarker = &__load_and_call_sceAgcDriverUserDataWriteSetMarker;

static __attribute__ ((used)) void
__load_sceAgcDriverUserDataWriteSetMarker(void) {
  sprx_dlsym(__handle, "sceAgcDriverUserDataWriteSetMarker", &__ptr_sceAgcDriverUserDataWriteSetMarker);
}

asm(".intel_syntax noprefix\n"
    ".global sceAgcDriverWaitUntilSafeForRendering\n"
    ".type sceAgcDriverWaitUntilSafeForRendering @function\n"
    "sceAgcDriverWaitUntilSafeForRendering:\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverWaitUntilSafeForRendering]\n");

asm(".intel_syntax noprefix\n"
    ".local __load_and_call_sceAgcDriverWaitUntilSafeForRendering\n"
    ".type __load_and_call_sceAgcDriverWaitUntilSafeForRendering @function\n"
    "__load_and_call_sceAgcDriverWaitUntilSafeForRendering:\n"
    "push rdi\n"
    "push rsi\n"
    "push rdx\n"
    "push rcx\n"
    "push r8\n"
    "push r9\n"
    "call __load_sceAgcDriverWaitUntilSafeForRendering\n"
    "pop r9\n"
    "pop r8\n"
    "pop rcx\n"
    "pop rdx\n"
    "pop rsi\n"
    "pop rdi\n"
    "jmp qword ptr [rip + __ptr_sceAgcDriverWaitUntilSafeForRendering]\n");

void __load_and_call_sceAgcDriverWaitUntilSafeForRendering();
static __attribute__ ((used)) void* __ptr_sceAgcDriverWaitUntilSafeForRendering = &__load_and_call_sceAgcDriverWaitUntilSafeForRendering;

static __attribute__ ((used)) void
__load_sceAgcDriverWaitUntilSafeForRendering(void) {
  sprx_dlsym(__handle, "sceAgcDriverWaitUntilSafeForRendering", &__ptr_sceAgcDriverWaitUntilSafeForRendering);
}
